// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod'

/**
 * AdditionalFormatResponseModel
 */
export const zAdditionalFormatResponseModel = z.object({
  requested_format: z.string(),
  file_extension: z.string(),
  content_type: z.string(),
  is_base64_encoded: z.boolean(),
  content: z.string(),
})

/**
 * AddVoiceIVCResponseModel
 */
export const zAddVoiceIvcResponseModel = z.object({
  voice_id: z.string(),
  requires_verification: z.boolean(),
})

/**
 * AddVoiceResponseModel
 */
export const zAddVoiceResponseModel = z.object({
  voice_id: z.string(),
})

export const zAllowedOutputFormats = z.enum([
  'mp3_22050_32',
  'mp3_24000_48',
  'mp3_44100_32',
  'mp3_44100_64',
  'mp3_44100_96',
  'mp3_44100_128',
  'mp3_44100_192',
  'pcm_8000',
  'pcm_16000',
  'pcm_22050',
  'pcm_24000',
  'pcm_32000',
  'pcm_44100',
  'pcm_48000',
  'ulaw_8000',
  'alaw_8000',
  'opus_48000_32',
  'opus_48000_64',
  'opus_48000_96',
  'opus_48000_128',
  'opus_48000_192',
])

/**
 * Body_Add_a_language_to_the_resource_v1_dubbing_resource__dubbing_id__language_post
 */
export const zBodyAddALanguageToTheResourceV1DubbingResourceDubbingIdLanguagePost =
  z.object({
    language: z.union([z.string(), z.unknown()]),
  })

/**
 * Body_Add_shared_voice_v1_voices_add__public_user_id___voice_id__post
 */
export const zBodyAddSharedVoiceV1VoicesAddPublicUserIdVoiceIdPost = z.object({
  new_name: z.string(),
  bookmarked: z.boolean().optional().default(true),
})

/**
 * Body_Add_voice_v1_voices_add_post
 */
export const zBodyAddVoiceV1VoicesAddPost = z.object({
  name: z.string(),
  files: z.array(z.string()),
  remove_background_noise: z.boolean().optional().default(false),
  description: z.union([z.string(), z.unknown()]).optional(),
  labels: z
    .union([z.record(z.string(), z.string()), z.string(), z.unknown()])
    .optional(),
})

/**
 * Body_Audio_Isolation_Stream_v1_audio_isolation_stream_post
 */
export const zBodyAudioIsolationStreamV1AudioIsolationStreamPost = z.object({
  audio: z.string(),
  file_format: z
    .union([z.enum(['pcm_s16le_16', 'other']), z.unknown()])
    .optional(),
})

/**
 * Body_Audio_Isolation_v1_audio_isolation_post
 */
export const zBodyAudioIsolationV1AudioIsolationPost = z.object({
  audio: z.string(),
  file_format: z
    .union([z.enum(['pcm_s16le_16', 'other']), z.unknown()])
    .optional(),
  preview_b64: z.union([z.string(), z.unknown()]).optional(),
})

/**
 * Body_Create_a_new_speaker_v1_dubbing_resource__dubbing_id__speaker_post
 */
export const zBodyCreateANewSpeakerV1DubbingResourceDubbingIdSpeakerPost =
  z.object({
    speaker_name: z.union([z.string(), z.unknown()]).optional(),
    voice_id: z.union([z.string(), z.unknown()]).optional(),
    voice_stability: z.union([z.number(), z.unknown()]).optional(),
    voice_similarity: z.union([z.number(), z.unknown()]).optional(),
    voice_style: z.union([z.number(), z.unknown()]).optional(),
  })

/**
 * Body_Create_a_new_voice_from_voice_preview_v1_text_to_voice_post
 */
export const zBodyCreateANewVoiceFromVoicePreviewV1TextToVoicePost = z.object({
  voice_name: z.string(),
  voice_description: z.string().min(20).max(1000),
  generated_voice_id: z.string(),
  labels: z.union([z.record(z.string(), z.string()), z.unknown()]).optional(),
  played_not_selected_voice_ids: z
    .union([z.array(z.string()), z.unknown()])
    .optional(),
})

/**
 * Body_Create_forced_alignment_v1_forced_alignment_post
 */
export const zBodyCreateForcedAlignmentV1ForcedAlignmentPost = z.object({
  file: z.string(),
  text: z.string(),
})

/**
 * Body_Dub_a_video_or_an_audio_file_v1_dubbing_post
 */
export const zBodyDubAVideoOrAnAudioFileV1DubbingPost = z.object({
  file: z.union([z.string(), z.unknown()]).optional(),
  csv_file: z.union([z.string(), z.unknown()]).optional(),
  foreground_audio_file: z.union([z.string(), z.unknown()]).optional(),
  background_audio_file: z.union([z.string(), z.unknown()]).optional(),
  name: z.union([z.string(), z.unknown()]).optional(),
  source_url: z.union([z.string(), z.unknown()]).optional(),
  source_lang: z.string().optional().default('auto'),
  target_lang: z.union([z.string(), z.unknown()]).optional(),
  target_accent: z.union([z.string(), z.unknown()]).optional(),
  num_speakers: z.int().optional().default(0),
  watermark: z.boolean().optional().default(false),
  start_time: z.union([z.int(), z.unknown()]).optional(),
  end_time: z.union([z.int(), z.unknown()]).optional(),
  highest_resolution: z.boolean().optional().default(false),
  drop_background_audio: z.boolean().optional().default(false),
  use_profanity_filter: z.union([z.boolean(), z.unknown()]).optional(),
  dubbing_studio: z.boolean().optional().default(false),
  disable_voice_cloning: z.boolean().optional().default(false),
  mode: z.enum(['automatic', 'manual']).optional().default('automatic'),
  csv_fps: z.union([z.number(), z.unknown()]).optional(),
})

/**
 * Body_Dubs_all_or_some_segments_and_languages_v1_dubbing_resource__dubbing_id__dub_post
 */
export const zBodyDubsAllOrSomeSegmentsAndLanguagesV1DubbingResourceDubbingIdDubPost =
  z.object({
    segments: z.array(z.string()),
    languages: z.union([z.array(z.string()), z.unknown()]),
  })

/**
 * Body_Edit_voice_v1_voices__voice_id__edit_post
 */
export const zBodyEditVoiceV1VoicesVoiceIdEditPost = z.object({
  name: z.string(),
  files: z.array(z.string()).optional(),
  remove_background_noise: z.boolean().optional().default(false),
  description: z.union([z.string(), z.unknown()]).optional(),
  labels: z
    .union([z.record(z.string(), z.string()), z.string(), z.unknown()])
    .optional(),
  moderate_metadata: z.boolean().optional().default(false),
})

/**
 * Body_Get_similar_library_voices_v1_similar_voices_post
 */
export const zBodyGetSimilarLibraryVoicesV1SimilarVoicesPost = z.object({
  audio_file: z.string().optional(),
  similarity_threshold: z.union([z.number(), z.unknown()]).optional(),
  top_k: z.union([z.int(), z.unknown()]).optional(),
})

/**
 * Body_Move_segments_between_speakers_v1_dubbing_resource__dubbing_id__migrate_segments_post
 */
export const zBodyMoveSegmentsBetweenSpeakersV1DubbingResourceDubbingIdMigrateSegmentsPost =
  z.object({
    segment_ids: z.array(z.string()),
    speaker_id: z.string(),
  })

/**
 * Body_Sound_Generation_v1_sound_generation_post
 */
export const zBodySoundGenerationV1SoundGenerationPost = z.object({
  text: z.string(),
  loop: z.boolean().optional().default(false),
  duration_seconds: z.union([z.number(), z.unknown()]).optional(),
  prompt_influence: z.union([z.number(), z.unknown()]).optional(),
  model_id: z.string().optional().default('eleven_text_to_sound_v2'),
})

/**
 * Body_Speech_to_Speech_Streaming_v1_speech_to_speech__voice_id__stream_post
 */
export const zBodySpeechToSpeechStreamingV1SpeechToSpeechVoiceIdStreamPost =
  z.object({
    audio: z.string(),
    model_id: z.string().optional().default('eleven_english_sts_v2'),
    voice_settings: z.union([z.string(), z.unknown()]).optional(),
    seed: z.union([z.int(), z.unknown()]).optional(),
    remove_background_noise: z.boolean().optional().default(false),
    file_format: z
      .union([z.enum(['pcm_s16le_16', 'other']), z.unknown()])
      .optional(),
  })

/**
 * Body_Speech_to_Speech_v1_speech_to_speech__voice_id__post
 */
export const zBodySpeechToSpeechV1SpeechToSpeechVoiceIdPost = z.object({
  audio: z.string(),
  model_id: z.string().optional().default('eleven_english_sts_v2'),
  voice_settings: z.union([z.string(), z.unknown()]).optional(),
  seed: z.union([z.int(), z.unknown()]).optional(),
  remove_background_noise: z.boolean().optional().default(false),
  file_format: z
    .union([z.enum(['pcm_s16le_16', 'other']), z.unknown()])
    .optional(),
})

/**
 * Body_Transcribes_segments_v1_dubbing_resource__dubbing_id__transcribe_post
 */
export const zBodyTranscribesSegmentsV1DubbingResourceDubbingIdTranscribePost =
  z.object({
    segments: z.array(z.string()),
  })

/**
 * Body_Translates_all_or_some_segments_and_languages_v1_dubbing_resource__dubbing_id__translate_post
 */
export const zBodyTranslatesAllOrSomeSegmentsAndLanguagesV1DubbingResourceDubbingIdTranslatePost =
  z.object({
    segments: z.array(z.string()),
    languages: z.union([z.array(z.string()), z.unknown()]),
  })

/**
 * Body_Video_to_Music_v1_music_video_to_music_post
 */
export const zBodyVideoToMusicV1MusicVideoToMusicPost = z.object({
  videos: z.array(z.string()).min(1).max(10),
  description: z.union([z.string().min(1).max(1000), z.unknown()]).optional(),
  tags: z.array(z.string()).min(0).max(10).optional().default([]),
  model_id: z.enum(['music_v1']).optional().default('music_v1'),
  sign_with_c2pa: z.boolean().optional().default(false),
})

/**
 * CharacterAlignmentResponseModel
 */
export const zCharacterAlignmentResponseModel = z.object({
  characters: z.array(z.string()),
  character_start_times_seconds: z.array(z.number()),
  character_end_times_seconds: z.array(z.number()),
})

/**
 * AudioWithTimestampsResponseModel
 */
export const zAudioWithTimestampsResponseModel = z.object({
  audio_base64: z.string(),
  alignment: z
    .union([zCharacterAlignmentResponseModel, z.unknown()])
    .optional(),
  normalized_alignment: z
    .union([zCharacterAlignmentResponseModel, z.unknown()])
    .optional(),
})

/**
 * DetectedEntity
 */
export const zDetectedEntity = z.object({
  text: z.string(),
  entity_type: z.string(),
  start_char: z.int(),
  end_char: z.int(),
})

/**
 * DialogueInput
 */
export const zDialogueInput = z.object({
  text: z.string(),
  voice_id: z.string(),
})

/**
 * DocxExportOptions
 */
export const zDocxExportOptions = z.object({
  include_speakers: z.boolean().optional().default(true),
  include_timestamps: z.boolean().optional().default(true),
  format: z.string(),
  segment_on_silence_longer_than_s: z
    .union([z.number(), z.unknown()])
    .optional(),
  max_segment_duration_s: z.union([z.number(), z.unknown()]).optional(),
  max_segment_chars: z.union([z.int(), z.unknown()]).optional(),
})

/**
 * DoDubbingResponseModel
 */
export const zDoDubbingResponseModel = z.object({
  dubbing_id: z.string(),
  expected_duration_sec: z.number(),
})

/**
 * DubbingRenderResponseModel
 */
export const zDubbingRenderResponseModel = z.object({
  version: z.int(),
  render_id: z.string(),
})

/**
 * EditVoiceResponseModel
 */
export const zEditVoiceResponseModel = z.object({
  status: z.string(),
})

/**
 * EditVoiceSettingsResponseModel
 */
export const zEditVoiceSettingsResponseModel = z.object({
  status: z.string(),
})

/**
 * ForcedAlignmentCharacterResponseModel
 *
 * Model representing a single character with its timing information from the aligner.
 */
export const zForcedAlignmentCharacterResponseModel = z.object({
  text: z.string(),
  start: z.number(),
  end: z.number(),
})

/**
 * ForcedAlignmentWordResponseModel
 *
 * Model representing a single word with its timing information from the aligner.
 */
export const zForcedAlignmentWordResponseModel = z.object({
  text: z.string(),
  start: z.number(),
  end: z.number(),
  loss: z.number(),
})

/**
 * ForcedAlignmentResponseModel
 *
 * Model representing the response from the aligner service.
 */
export const zForcedAlignmentResponseModel = z.object({
  characters: z.array(zForcedAlignmentCharacterResponseModel),
  words: z.array(zForcedAlignmentWordResponseModel),
  loss: z.number(),
})

/**
 * HtmlExportOptions
 */
export const zHtmlExportOptions = z.object({
  include_speakers: z.boolean().optional().default(true),
  include_timestamps: z.boolean().optional().default(true),
  format: z.string(),
  segment_on_silence_longer_than_s: z
    .union([z.number(), z.unknown()])
    .optional(),
  max_segment_duration_s: z.union([z.number(), z.unknown()]).optional(),
  max_segment_chars: z.union([z.int(), z.unknown()]).optional(),
})

/**
 * LanguageAddedResponse
 */
export const zLanguageAddedResponse = z.object({
  version: z.int(),
})

/**
 * ManualVerificationFileResponseModel
 */
export const zManualVerificationFileResponseModel = z.object({
  file_id: z.string(),
  file_name: z.string(),
  mime_type: z.string(),
  size_bytes: z.int(),
  upload_date_unix: z.int(),
})

/**
 * ManualVerificationResponseModel
 */
export const zManualVerificationResponseModel = z.object({
  extra_text: z.string(),
  request_time_unix: z.int(),
  files: z.array(zManualVerificationFileResponseModel),
})

/**
 * ModelSettingsResponseModel
 */
export const zModelSettingsResponseModel = z.object({
  stability: z.union([z.number().gte(0).lte(1), z.unknown()]).optional(),
})

export const zNonStreamingOutputFormats = z.enum([
  'wav_8000',
  'wav_16000',
  'wav_22050',
  'wav_24000',
  'wav_32000',
  'wav_44100',
  'wav_48000',
])

/**
 * PdfExportOptions
 */
export const zPdfExportOptions = z.object({
  include_speakers: z.boolean().optional().default(true),
  include_timestamps: z.boolean().optional().default(true),
  format: z.string(),
  segment_on_silence_longer_than_s: z
    .union([z.number(), z.unknown()])
    .optional(),
  max_segment_duration_s: z.union([z.number(), z.unknown()]).optional(),
  max_segment_chars: z.union([z.int(), z.unknown()]).optional(),
})

/**
 * PronunciationDictionaryVersionLocatorRequestModel
 */
export const zPronunciationDictionaryVersionLocatorRequestModel = z.object({
  pronunciation_dictionary_id: z.string(),
  version_id: z.union([z.string(), z.unknown()]).optional(),
})

/**
 * Body_Text_to_dialogue__multi_voice__streaming_v1_text_to_dialogue_stream_post
 */
export const zBodyTextToDialogueMultiVoiceStreamingV1TextToDialogueStreamPost =
  z.object({
    inputs: z.array(zDialogueInput),
    model_id: z.string().optional().default('eleven_v3'),
    language_code: z.union([z.string(), z.unknown()]).optional(),
    settings: z.union([zModelSettingsResponseModel, z.unknown()]).optional(),
    pronunciation_dictionary_locators: z
      .union([
        z.array(zPronunciationDictionaryVersionLocatorRequestModel),
        z.unknown(),
      ])
      .optional(),
    seed: z.union([z.int(), z.unknown()]).optional(),
    apply_text_normalization: z
      .enum(['auto', 'on', 'off'])
      .optional()
      .default('auto'),
  })

/**
 * Body_Text_to_dialogue__multi_voice__v1_text_to_dialogue_post
 */
export const zBodyTextToDialogueMultiVoiceV1TextToDialoguePost = z.object({
  inputs: z.array(zDialogueInput),
  model_id: z.string().optional().default('eleven_v3'),
  language_code: z.union([z.string(), z.unknown()]).optional(),
  settings: z.union([zModelSettingsResponseModel, z.unknown()]).optional(),
  pronunciation_dictionary_locators: z
    .union([
      z.array(zPronunciationDictionaryVersionLocatorRequestModel),
      z.unknown(),
    ])
    .optional(),
  seed: z.union([z.int(), z.unknown()]).optional(),
  apply_text_normalization: z
    .enum(['auto', 'on', 'off'])
    .optional()
    .default('auto'),
})

/**
 * Body_text_to_dialogue_full_with_timestamps
 */
export const zBodyTextToDialogueFullWithTimestamps = z.object({
  inputs: z.array(zDialogueInput),
  model_id: z.string().optional().default('eleven_v3'),
  language_code: z.union([z.string(), z.unknown()]).optional(),
  settings: z.union([zModelSettingsResponseModel, z.unknown()]).optional(),
  pronunciation_dictionary_locators: z
    .union([
      z.array(zPronunciationDictionaryVersionLocatorRequestModel),
      z.unknown(),
    ])
    .optional(),
  seed: z.union([z.int(), z.unknown()]).optional(),
  apply_text_normalization: z
    .enum(['auto', 'on', 'off'])
    .optional()
    .default('auto'),
})

/**
 * Body_text_to_dialogue_stream_with_timestamps
 */
export const zBodyTextToDialogueStreamWithTimestamps = z.object({
  inputs: z.array(zDialogueInput),
  model_id: z.string().optional().default('eleven_v3'),
  language_code: z.union([z.string(), z.unknown()]).optional(),
  settings: z.union([zModelSettingsResponseModel, z.unknown()]).optional(),
  pronunciation_dictionary_locators: z
    .union([
      z.array(zPronunciationDictionaryVersionLocatorRequestModel),
      z.unknown(),
    ])
    .optional(),
  seed: z.union([z.int(), z.unknown()]).optional(),
  apply_text_normalization: z
    .enum(['auto', 'on', 'off'])
    .optional()
    .default('auto'),
})

/**
 * ReaderResourceResponseModel
 */
export const zReaderResourceResponseModel = z.object({
  resource_type: z.enum(['read', 'collection']),
  resource_id: z.string(),
})

/**
 * RecordingResponseModel
 */
export const zRecordingResponseModel = z.object({
  recording_id: z.string(),
  mime_type: z.string(),
  size_bytes: z.int(),
  upload_date_unix: z.int(),
  transcription: z.string(),
})

/**
 * RenderType
 */
export const zRenderType = z.enum([
  'mp4',
  'aac',
  'mp3',
  'wav',
  'aaf',
  'tracks_zip',
  'clips_zip',
  'zip',
])

/**
 * Body_Render_audio_or_video_for_the_given_language_v1_dubbing_resource__dubbing_id__render__language__post
 */
export const zBodyRenderAudioOrVideoForTheGivenLanguageV1DubbingResourceDubbingIdRenderLanguagePost =
  z.object({
    render_type: zRenderType,
    normalize_volume: z.union([z.boolean(), z.unknown()]).optional(),
  })

/**
 * SegmentCreatePayload
 */
export const zSegmentCreatePayload = z.object({
  start_time: z.number(),
  end_time: z.number(),
  text: z.union([z.string(), z.unknown()]).optional(),
  translations: z
    .union([z.record(z.string(), z.string()), z.unknown()])
    .optional(),
})

/**
 * SegmentCreateResponse
 */
export const zSegmentCreateResponse = z.object({
  version: z.int(),
  new_segment: z.string(),
})

/**
 * SegmentDubResponse
 */
export const zSegmentDubResponse = z.object({
  version: z.int(),
})

/**
 * SegmentedJsonExportOptions
 */
export const zSegmentedJsonExportOptions = z.object({
  include_speakers: z.boolean().optional().default(true),
  include_timestamps: z.boolean().optional().default(true),
  format: z.string(),
  segment_on_silence_longer_than_s: z
    .union([z.number(), z.unknown()])
    .optional(),
  max_segment_duration_s: z.union([z.number(), z.unknown()]).optional(),
  max_segment_chars: z.union([z.int(), z.unknown()]).optional(),
})

/**
 * SegmentMigrationResponse
 */
export const zSegmentMigrationResponse = z.object({
  version: z.int(),
})

/**
 * SegmentTranscriptionResponse
 */
export const zSegmentTranscriptionResponse = z.object({
  version: z.int(),
})

/**
 * SegmentTranslationResponse
 */
export const zSegmentTranslationResponse = z.object({
  version: z.int(),
})

/**
 * SpeakerCreatedResponse
 */
export const zSpeakerCreatedResponse = z.object({
  version: z.int(),
  speaker_id: z.string(),
})

/**
 * SpeechToTextCharacterResponseModel
 */
export const zSpeechToTextCharacterResponseModel = z.object({
  text: z.string(),
  start: z.union([z.number(), z.unknown()]).optional(),
  end: z.union([z.number(), z.unknown()]).optional(),
})

/**
 * SpeechToTextWebhookResponseModel
 */
export const zSpeechToTextWebhookResponseModel = z.object({
  message: z.string(),
  request_id: z.string(),
  transcription_id: z.union([z.string(), z.unknown()]).optional(),
})

/**
 * SpeechToTextWordResponseModel
 *
 * Word-level detail of the transcription with timing information.
 */
export const zSpeechToTextWordResponseModel = z.object({
  text: z.string(),
  start: z.union([z.number(), z.unknown()]).optional(),
  end: z.union([z.number(), z.unknown()]).optional(),
  type: z.enum(['word', 'spacing', 'audio_event']),
  speaker_id: z.union([z.string(), z.unknown()]).optional(),
  logprob: z.number(),
  characters: z
    .union([z.array(zSpeechToTextCharacterResponseModel), z.unknown()])
    .optional(),
})

/**
 * SpeechToTextChunkResponseModel
 *
 * Chunk-level detail of the transcription with timing information.
 */
export const zSpeechToTextChunkResponseModel = z.object({
  language_code: z.string(),
  language_probability: z.number(),
  text: z.string(),
  words: z.array(zSpeechToTextWordResponseModel),
  channel_index: z.union([z.int(), z.unknown()]).optional(),
  additional_formats: z
    .union([
      z.array(z.union([zAdditionalFormatResponseModel, z.unknown()])),
      z.unknown(),
    ])
    .optional(),
  transcription_id: z.union([z.string(), z.unknown()]).optional(),
  entities: z.union([z.array(zDetectedEntity), z.unknown()]).optional(),
  audio_duration_secs: z.union([z.number(), z.unknown()]).optional(),
})

/**
 * MultichannelSpeechToTextResponseModel
 *
 * Response model for multichannel speech-to-text transcription.
 */
export const zMultichannelSpeechToTextResponseModel = z.object({
  transcripts: z.array(zSpeechToTextChunkResponseModel),
  transcription_id: z.union([z.string(), z.unknown()]).optional(),
  audio_duration_secs: z.union([z.number(), z.unknown()]).optional(),
})

/**
 * SrtExportOptions
 */
export const zSrtExportOptions = z.object({
  max_characters_per_line: z.union([z.int(), z.unknown()]).optional(),
  include_speakers: z.boolean().optional().default(false),
  include_timestamps: z.boolean().optional().default(true),
  format: z.string(),
  segment_on_silence_longer_than_s: z
    .union([z.number(), z.unknown()])
    .optional(),
  max_segment_duration_s: z.union([z.number(), z.unknown()]).optional(),
  max_segment_chars: z.union([z.int(), z.unknown()]).optional(),
})

/**
 * StreamingAudioChunkWithTimestampsResponseModel
 */
export const zStreamingAudioChunkWithTimestampsResponseModel = z.object({
  audio_base64: z.string(),
  alignment: z
    .union([zCharacterAlignmentResponseModel, z.unknown()])
    .optional(),
  normalized_alignment: z
    .union([zCharacterAlignmentResponseModel, z.unknown()])
    .optional(),
})

/**
 * TxtExportOptions
 */
export const zTxtExportOptions = z.object({
  max_characters_per_line: z.union([z.int(), z.unknown()]).optional(),
  include_speakers: z.boolean().optional().default(true),
  include_timestamps: z.boolean().optional().default(true),
  format: z.string(),
  segment_on_silence_longer_than_s: z
    .union([z.number(), z.unknown()])
    .optional(),
  max_segment_duration_s: z.union([z.number(), z.unknown()]).optional(),
  max_segment_chars: z.union([z.int(), z.unknown()]).optional(),
})

/**
 * ExportOptions
 */
export const zExportOptions = z.discriminatedUnion('format', [
  zSegmentedJsonExportOptions.extend({ format: z.literal('segmented_json') }),
  zDocxExportOptions.extend({ format: z.literal('docx') }),
  zPdfExportOptions.extend({ format: z.literal('pdf') }),
  zTxtExportOptions.extend({ format: z.literal('txt') }),
  zHtmlExportOptions.extend({ format: z.literal('html') }),
  zSrtExportOptions.extend({ format: z.literal('srt') }),
])

/**
 * AdditionalFormats
 */
export const zAdditionalFormats = z.array(zExportOptions).max(10)

/**
 * Body_Speech_to_Text_v1_speech_to_text_post
 */
export const zBodySpeechToTextV1SpeechToTextPost = z.object({
  model_id: z.enum(['scribe_v1', 'scribe_v2']),
  file: z.union([z.string(), z.unknown()]).optional(),
  language_code: z.union([z.string(), z.unknown()]).optional(),
  tag_audio_events: z.boolean().optional().default(true),
  num_speakers: z.union([z.int().gte(1).lte(32), z.unknown()]).optional(),
  timestamps_granularity: z
    .enum(['none', 'word', 'character'])
    .optional()
    .default('word'),
  diarize: z.boolean().optional().default(false),
  diarization_threshold: z
    .union([z.number().gte(0.1).lte(0.4), z.unknown()])
    .optional(),
  additional_formats: zAdditionalFormats.optional(),
  file_format: z.enum(['pcm_s16le_16', 'other']).optional().default('other'),
  cloud_storage_url: z.union([z.string(), z.unknown()]).optional(),
  source_url: z.union([z.string(), z.unknown()]).optional(),
  webhook: z.boolean().optional().default(false),
  webhook_id: z.union([z.string(), z.unknown()]).optional(),
  temperature: z.union([z.number().gte(0).lte(2), z.unknown()]).optional(),
  seed: z.union([z.int().gte(0).lte(2147483647), z.unknown()]).optional(),
  use_multi_channel: z.boolean().optional().default(false),
  webhook_metadata: z
    .union([z.string(), z.record(z.string(), z.unknown()), z.unknown()])
    .optional(),
  entity_detection: z
    .union([z.string(), z.array(z.string()), z.unknown()])
    .optional(),
  no_verbatim: z.boolean().optional().default(false),
  detect_speaker_roles: z.boolean().optional().default(false),
  entity_redaction: z
    .union([z.string(), z.array(z.string()), z.unknown()])
    .optional(),
  entity_redaction_mode: z
    .string()
    .optional()
    .default('enumerated_entity_type'),
  keyterms: z.array(z.string()).optional().default([]),
})

/**
 * UtteranceResponseModel
 */
export const zUtteranceResponseModel = z.object({
  start: z.number(),
  end: z.number(),
})

/**
 * SpeakerResponseModel
 */
export const zSpeakerResponseModel = z.object({
  speaker_id: z.string(),
  duration_secs: z.number(),
  utterances: z
    .union([z.array(zUtteranceResponseModel), z.unknown()])
    .optional(),
})

/**
 * SpeakerSeparationResponseModel
 */
export const zSpeakerSeparationResponseModel = z.object({
  voice_id: z.string(),
  sample_id: z.string(),
  status: z.enum(['not_started', 'pending', 'completed', 'failed']),
  speakers: z
    .union([z.record(z.string(), zSpeakerResponseModel), z.unknown()])
    .optional(),
  selected_speaker_ids: z.union([z.array(z.string()), z.unknown()]).optional(),
})

/**
 * SampleResponseModel
 */
export const zSampleResponseModel = z.object({
  sample_id: z.string(),
  file_name: z.string(),
  mime_type: z.string(),
  size_bytes: z.int(),
  hash: z.string(),
  duration_secs: z.union([z.number(), z.unknown()]).optional(),
  remove_background_noise: z.union([z.boolean(), z.unknown()]).optional(),
  has_isolated_audio: z.union([z.boolean(), z.unknown()]).optional(),
  has_isolated_audio_preview: z.union([z.boolean(), z.unknown()]).optional(),
  speaker_separation: z
    .union([zSpeakerSeparationResponseModel, z.unknown()])
    .optional(),
  trim_start: z.union([z.int(), z.unknown()]).optional(),
  trim_end: z.union([z.int(), z.unknown()]).optional(),
})

/**
 * ValidationError
 */
export const zValidationError = z.object({
  loc: z.array(z.union([z.string(), z.int()])),
  msg: z.string(),
  type: z.string(),
})

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
  detail: z.array(zValidationError).optional(),
})

/**
 * VerificationAttemptResponseModel
 */
export const zVerificationAttemptResponseModel = z.object({
  text: z.string(),
  date_unix: z.int(),
  accepted: z.boolean(),
  similarity: z.number(),
  levenshtein_distance: z.number(),
  recording: z.union([zRecordingResponseModel, z.unknown()]).optional(),
})

/**
 * FineTuningResponseModel
 */
export const zFineTuningResponseModel = z.object({
  is_allowed_to_fine_tune: z.boolean(),
  state: z.record(
    z.string(),
    z.enum([
      'not_started',
      'queued',
      'fine_tuning',
      'fine_tuned',
      'failed',
      'delayed',
    ]),
  ),
  verification_failures: z.array(z.string()),
  verification_attempts_count: z.int(),
  manual_verification_requested: z.boolean(),
  language: z.union([z.string(), z.unknown()]).optional(),
  progress: z.union([z.record(z.string(), z.number()), z.unknown()]).optional(),
  message: z.union([z.record(z.string(), z.string()), z.unknown()]).optional(),
  dataset_duration_seconds: z.union([z.number(), z.unknown()]).optional(),
  verification_attempts: z
    .union([z.array(zVerificationAttemptResponseModel), z.unknown()])
    .optional(),
  slice_ids: z.union([z.array(z.string()), z.unknown()]).optional(),
  manual_verification: z
    .union([zManualVerificationResponseModel, z.unknown()])
    .optional(),
  max_verification_attempts: z.union([z.int(), z.unknown()]).optional(),
  next_max_verification_attempts_reset_unix_ms: z
    .union([z.int(), z.unknown()])
    .optional(),
})

/**
 * VerifiedVoiceLanguageResponseModel
 */
export const zVerifiedVoiceLanguageResponseModel = z.object({
  language: z.string(),
  model_id: z.string(),
  accent: z.union([z.string(), z.unknown()]).optional(),
  locale: z.union([z.string(), z.unknown()]).optional(),
  preview_url: z.union([z.string(), z.unknown()]).optional(),
})

/**
 * LibraryVoiceResponseModel
 */
export const zLibraryVoiceResponseModel = z.object({
  public_owner_id: z.string(),
  voice_id: z.string(),
  date_unix: z.int(),
  name: z.string(),
  accent: z.string(),
  gender: z.string(),
  age: z.string(),
  descriptive: z.string(),
  use_case: z.string(),
  category: z.enum([
    'generated',
    'cloned',
    'premade',
    'professional',
    'famous',
    'high_quality',
  ]),
  language: z.union([z.string(), z.unknown()]).optional(),
  locale: z.union([z.string(), z.unknown()]).optional(),
  description: z.union([z.string(), z.unknown()]).optional(),
  preview_url: z.union([z.string(), z.unknown()]).optional(),
  usage_character_count_1y: z.int(),
  usage_character_count_7d: z.int(),
  play_api_usage_character_count_1y: z.int(),
  cloned_by_count: z.int(),
  rate: z.union([z.number(), z.unknown()]).optional(),
  fiat_rate: z.union([z.number(), z.unknown()]).optional(),
  free_users_allowed: z.boolean(),
  live_moderation_enabled: z.boolean(),
  featured: z.boolean(),
  verified_languages: z
    .union([z.array(zVerifiedVoiceLanguageResponseModel), z.unknown()])
    .optional(),
  notice_period: z.union([z.int(), z.unknown()]).optional(),
  instagram_username: z.union([z.string(), z.unknown()]).optional(),
  twitter_username: z.union([z.string(), z.unknown()]).optional(),
  youtube_username: z.union([z.string(), z.unknown()]).optional(),
  tiktok_username: z.union([z.string(), z.unknown()]).optional(),
  image_url: z.union([z.string(), z.unknown()]).optional(),
  is_added_by_user: z.union([z.boolean(), z.unknown()]).optional(),
  is_bookmarked: z.union([z.boolean(), z.unknown()]).optional(),
})

/**
 * GetLibraryVoicesResponseModel
 */
export const zGetLibraryVoicesResponseModel = z.object({
  voices: z.array(zLibraryVoiceResponseModel),
  has_more: z.boolean(),
  total_count: z.int().optional().default(0),
  last_sort_id: z.union([z.string(), z.unknown()]).optional(),
})

/**
 * VoiceDesignRequestModel
 */
export const zVoiceDesignRequestModel = z.object({
  voice_description: z.string().min(20).max(1000),
  model_id: z
    .enum(['eleven_multilingual_ttv_v2', 'eleven_ttv_v3'])
    .optional()
    .default('eleven_multilingual_ttv_v2'),
  text: z.union([z.string().min(100).max(1000), z.unknown()]).optional(),
  auto_generate_text: z.boolean().optional().default(false),
  loudness: z.number().gte(-1).lte(1).optional().default(0.5),
  seed: z.union([z.int().gte(0).lte(2147483647), z.unknown()]).optional(),
  guidance_scale: z.number().gte(0).lte(100).optional().default(5),
  stream_previews: z.boolean().optional().default(false),
  should_enhance: z.boolean().optional().default(false),
  remixing_session_id: z.union([z.string(), z.unknown()]).optional(),
  remixing_session_iteration_id: z.union([z.string(), z.unknown()]).optional(),
  quality: z.union([z.number().gte(-1).lte(1), z.unknown()]).optional(),
  reference_audio_base64: z.union([z.string(), z.unknown()]).optional(),
  prompt_strength: z.union([z.number().gte(0).lte(1), z.unknown()]).optional(),
})

/**
 * VoicePreviewResponseModel
 */
export const zVoicePreviewResponseModel = z.object({
  audio_base_64: z.string(),
  generated_voice_id: z.string(),
  media_type: z.string(),
  duration_secs: z.number(),
  language: z.union([z.string(), z.unknown()]),
})

/**
 * VoicePreviewsRequestModel
 */
export const zVoicePreviewsRequestModel = z.object({
  voice_description: z.string().min(20).max(1000),
  text: z.union([z.string().min(100).max(1000), z.unknown()]).optional(),
  auto_generate_text: z.boolean().optional().default(false),
  loudness: z.number().gte(-1).lte(1).optional().default(0.5),
  quality: z.number().gte(-1).lte(1).optional().default(0.9),
  seed: z.union([z.int().gte(0).lte(2147483647), z.unknown()]).optional(),
  guidance_scale: z.number().gte(0).lte(100).optional().default(5),
  should_enhance: z.boolean().optional().default(false),
})

/**
 * VoicePreviewsResponseModel
 */
export const zVoicePreviewsResponseModel = z.object({
  previews: z.array(zVoicePreviewResponseModel),
  text: z.string(),
})

/**
 * VoiceRemixRequestModel
 */
export const zVoiceRemixRequestModel = z.object({
  voice_description: z.string().min(5).max(1000),
  text: z.union([z.string().min(100).max(1000), z.unknown()]).optional(),
  auto_generate_text: z.boolean().optional().default(false),
  loudness: z.number().gte(-1).lte(1).optional().default(0.5),
  seed: z.union([z.int().gte(0).lte(2147483647), z.unknown()]).optional(),
  guidance_scale: z.number().gte(0).lte(100).optional().default(2),
  stream_previews: z.boolean().optional().default(false),
  remixing_session_id: z.union([z.string(), z.unknown()]).optional(),
  remixing_session_iteration_id: z.union([z.string(), z.unknown()]).optional(),
  prompt_strength: z.union([z.number().gte(0).lte(1), z.unknown()]).optional(),
})

/**
 * VoiceSegment
 */
export const zVoiceSegment = z.object({
  voice_id: z.string(),
  start_time_seconds: z.number(),
  end_time_seconds: z.number(),
  character_start_index: z.int(),
  character_end_index: z.int(),
  dialogue_input_index: z.int(),
})

/**
 * AudioWithTimestampsAndVoiceSegmentsResponseModel
 */
export const zAudioWithTimestampsAndVoiceSegmentsResponseModel = z.object({
  audio_base64: z.string(),
  alignment: z
    .union([zCharacterAlignmentResponseModel, z.unknown()])
    .optional(),
  normalized_alignment: z
    .union([zCharacterAlignmentResponseModel, z.unknown()])
    .optional(),
  voice_segments: z.array(zVoiceSegment),
})

/**
 * StreamingAudioChunkWithTimestampsAndVoiceSegmentsResponseModel
 */
export const zStreamingAudioChunkWithTimestampsAndVoiceSegmentsResponseModel =
  z.object({
    audio_base64: z.string(),
    alignment: z
      .union([zCharacterAlignmentResponseModel, z.unknown()])
      .optional(),
    normalized_alignment: z
      .union([zCharacterAlignmentResponseModel, z.unknown()])
      .optional(),
    voice_segments: z.array(zVoiceSegment),
  })

/**
 * VoiceSettingsResponseModel
 */
export const zVoiceSettingsResponseModel = z.object({
  stability: z.union([z.number().gte(0).lte(1), z.unknown()]).optional(),
  use_speaker_boost: z.union([z.boolean(), z.unknown()]).optional(),
  similarity_boost: z.union([z.number().gte(0).lte(1), z.unknown()]).optional(),
  style: z.union([z.number(), z.unknown()]).optional(),
  speed: z.union([z.number(), z.unknown()]).optional(),
})

/**
 * Body_text_to_speech_full
 */
export const zBodyTextToSpeechFull = z.object({
  text: z.string(),
  model_id: z.string().optional().default('eleven_multilingual_v2'),
  language_code: z.union([z.string(), z.unknown()]).optional(),
  voice_settings: z
    .union([zVoiceSettingsResponseModel, z.unknown()])
    .optional(),
  pronunciation_dictionary_locators: z
    .union([
      z.array(zPronunciationDictionaryVersionLocatorRequestModel),
      z.unknown(),
    ])
    .optional(),
  seed: z.union([z.int(), z.unknown()]).optional(),
  previous_text: z.union([z.string(), z.unknown()]).optional(),
  next_text: z.union([z.string(), z.unknown()]).optional(),
  previous_request_ids: z.union([z.array(z.string()), z.unknown()]).optional(),
  next_request_ids: z.union([z.array(z.string()), z.unknown()]).optional(),
  use_pvc_as_ivc: z.boolean().optional().default(false),
  apply_text_normalization: z
    .enum(['auto', 'on', 'off'])
    .optional()
    .default('auto'),
  apply_language_text_normalization: z.boolean().optional().default(false),
})

/**
 * Body_text_to_speech_full_with_timestamps
 */
export const zBodyTextToSpeechFullWithTimestamps = z.object({
  text: z.string(),
  model_id: z.string().optional().default('eleven_multilingual_v2'),
  language_code: z.union([z.string(), z.unknown()]).optional(),
  voice_settings: z
    .union([zVoiceSettingsResponseModel, z.unknown()])
    .optional(),
  pronunciation_dictionary_locators: z
    .array(zPronunciationDictionaryVersionLocatorRequestModel)
    .optional(),
  seed: z.union([z.int(), z.unknown()]).optional(),
  previous_text: z.union([z.string(), z.unknown()]).optional(),
  next_text: z.union([z.string(), z.unknown()]).optional(),
  previous_request_ids: z.array(z.string()).optional(),
  next_request_ids: z.array(z.string()).optional(),
  use_pvc_as_ivc: z.boolean().optional().default(false),
  apply_text_normalization: z
    .enum(['auto', 'on', 'off'])
    .optional()
    .default('auto'),
  apply_language_text_normalization: z.boolean().optional().default(false),
})

/**
 * Body_text_to_speech_stream
 */
export const zBodyTextToSpeechStream = z.object({
  text: z.string(),
  model_id: z.string().optional().default('eleven_multilingual_v2'),
  language_code: z.union([z.string(), z.unknown()]).optional(),
  voice_settings: z
    .union([zVoiceSettingsResponseModel, z.unknown()])
    .optional(),
  pronunciation_dictionary_locators: z
    .union([
      z.array(zPronunciationDictionaryVersionLocatorRequestModel),
      z.unknown(),
    ])
    .optional(),
  seed: z.union([z.int(), z.unknown()]).optional(),
  previous_text: z.union([z.string(), z.unknown()]).optional(),
  next_text: z.union([z.string(), z.unknown()]).optional(),
  previous_request_ids: z.union([z.array(z.string()), z.unknown()]).optional(),
  next_request_ids: z.union([z.array(z.string()), z.unknown()]).optional(),
  use_pvc_as_ivc: z.boolean().optional().default(false),
  apply_text_normalization: z
    .enum(['auto', 'on', 'off'])
    .optional()
    .default('auto'),
  apply_language_text_normalization: z.boolean().optional().default(false),
})

/**
 * Body_text_to_speech_stream_with_timestamps
 */
export const zBodyTextToSpeechStreamWithTimestamps = z.object({
  text: z.string(),
  model_id: z.string().optional().default('eleven_multilingual_v2'),
  language_code: z.union([z.string(), z.unknown()]).optional(),
  voice_settings: z
    .union([zVoiceSettingsResponseModel, z.unknown()])
    .optional(),
  pronunciation_dictionary_locators: z
    .union([
      z.array(zPronunciationDictionaryVersionLocatorRequestModel),
      z.unknown(),
    ])
    .optional(),
  seed: z.union([z.int(), z.unknown()]).optional(),
  previous_text: z.union([z.string(), z.unknown()]).optional(),
  next_text: z.union([z.string(), z.unknown()]).optional(),
  previous_request_ids: z.union([z.array(z.string()), z.unknown()]).optional(),
  next_request_ids: z.union([z.array(z.string()), z.unknown()]).optional(),
  use_pvc_as_ivc: z.boolean().optional().default(false),
  apply_text_normalization: z
    .enum(['auto', 'on', 'off'])
    .optional()
    .default('auto'),
  apply_language_text_normalization: z.boolean().optional().default(false),
})

/**
 * VoiceSharingModerationCheckResponseModel
 */
export const zVoiceSharingModerationCheckResponseModel = z.object({
  date_checked_unix: z.union([z.int(), z.unknown()]).optional(),
  name_value: z.union([z.string(), z.unknown()]).optional(),
  name_check: z.union([z.boolean(), z.unknown()]).optional(),
  description_value: z.union([z.string(), z.unknown()]).optional(),
  description_check: z.union([z.boolean(), z.unknown()]).optional(),
  sample_ids: z.union([z.array(z.string()), z.unknown()]).optional(),
  sample_checks: z.union([z.array(z.number()), z.unknown()]).optional(),
  captcha_ids: z.union([z.array(z.string()), z.unknown()]).optional(),
  captcha_checks: z.union([z.array(z.number()), z.unknown()]).optional(),
})

/**
 * VoiceSharingResponseModel
 */
export const zVoiceSharingResponseModel = z.object({
  status: z.enum(['enabled', 'disabled', 'copied', 'copied_disabled']),
  history_item_sample_id: z.union([z.string(), z.unknown()]).optional(),
  date_unix: z.int(),
  whitelisted_emails: z.array(z.string()),
  public_owner_id: z.string(),
  original_voice_id: z.string(),
  financial_rewards_enabled: z.boolean(),
  free_users_allowed: z.boolean(),
  live_moderation_enabled: z.boolean(),
  rate: z.union([z.number(), z.unknown()]).optional(),
  fiat_rate: z.union([z.number(), z.unknown()]).optional(),
  notice_period: z.int(),
  disable_at_unix: z.union([z.int(), z.unknown()]).optional(),
  voice_mixing_allowed: z.boolean(),
  featured: z.boolean(),
  category: z.enum([
    'generated',
    'cloned',
    'premade',
    'professional',
    'famous',
    'high_quality',
  ]),
  reader_app_enabled: z.union([z.boolean(), z.unknown()]).optional(),
  image_url: z.union([z.string(), z.unknown()]).optional(),
  ban_reason: z.union([z.string(), z.unknown()]).optional(),
  liked_by_count: z.int(),
  cloned_by_count: z.int(),
  name: z.string(),
  description: z.union([z.string(), z.unknown()]).optional(),
  labels: z.record(z.string(), z.string()),
  review_status: z.enum([
    'not_requested',
    'pending',
    'declined',
    'allowed',
    'allowed_with_changes',
  ]),
  review_message: z.union([z.string(), z.unknown()]).optional(),
  enabled_in_library: z.boolean(),
  instagram_username: z.union([z.string(), z.unknown()]).optional(),
  twitter_username: z.union([z.string(), z.unknown()]).optional(),
  youtube_username: z.union([z.string(), z.unknown()]).optional(),
  tiktok_username: z.union([z.string(), z.unknown()]).optional(),
  moderation_check: z
    .union([zVoiceSharingModerationCheckResponseModel, z.unknown()])
    .optional(),
  reader_restricted_on: z
    .union([z.array(zReaderResourceResponseModel), z.unknown()])
    .optional(),
})

/**
 * VoiceVerificationResponseModel
 */
export const zVoiceVerificationResponseModel = z.object({
  requires_verification: z.boolean(),
  is_verified: z.boolean(),
  verification_failures: z.array(z.string()),
  verification_attempts_count: z.int(),
  language: z.union([z.string(), z.unknown()]).optional(),
  verification_attempts: z
    .union([z.array(zVerificationAttemptResponseModel), z.unknown()])
    .optional(),
})

/**
 * VoiceResponseModel
 */
export const zVoiceResponseModel = z.object({
  voice_id: z.string(),
  name: z.string(),
  samples: z.union([z.array(zSampleResponseModel), z.unknown()]).optional(),
  category: z.enum([
    'generated',
    'cloned',
    'premade',
    'professional',
    'famous',
    'high_quality',
  ]),
  fine_tuning: z.union([zFineTuningResponseModel, z.unknown()]).optional(),
  labels: z.record(z.string(), z.string()),
  description: z.union([z.string(), z.unknown()]).optional(),
  preview_url: z.union([z.string(), z.unknown()]).optional(),
  available_for_tiers: z.array(z.string()),
  settings: z.union([zVoiceSettingsResponseModel, z.unknown()]).optional(),
  sharing: z.union([zVoiceSharingResponseModel, z.unknown()]).optional(),
  high_quality_base_model_ids: z.array(z.string()),
  verified_languages: z
    .union([z.array(zVerifiedVoiceLanguageResponseModel), z.unknown()])
    .optional(),
  collection_ids: z.union([z.array(z.string()), z.unknown()]).optional(),
  safety_control: z
    .union([
      z.enum([
        'NONE',
        'BAN',
        'CAPTCHA',
        'ENTERPRISE_BAN',
        'ENTERPRISE_CAPTCHA',
      ]),
      z.unknown(),
    ])
    .optional(),
  voice_verification: z
    .union([zVoiceVerificationResponseModel, z.unknown()])
    .optional(),
  permission_on_resource: z.union([z.string(), z.unknown()]).optional(),
  is_owner: z.union([z.boolean(), z.unknown()]).optional(),
  is_legacy: z.boolean().optional().default(false),
  is_mixed: z.boolean().optional().default(false),
  favorited_at_unix: z.union([z.int(), z.unknown()]).optional(),
  created_at_unix: z.union([z.int(), z.unknown()]).optional(),
  is_bookmarked: z.union([z.boolean(), z.unknown()]).optional(),
  recording_quality: z
    .union([z.enum(['studio', 'good', 'ok', 'poor', 'bad']), z.unknown()])
    .optional(),
  labelling_status: z
    .union([z.enum(['in_review', 'review_complete']), z.unknown()])
    .optional(),
  recording_quality_reason: z.union([z.string(), z.unknown()]).optional(),
})

export const zAudioIsolationBody = zBodyAudioIsolationV1AudioIsolationPost

export const zAudioIsolationHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

/**
 * Successful Response
 */
export const zAudioIsolationResponse = z.string()

export const zAudioIsolationStreamBody =
  zBodyAudioIsolationStreamV1AudioIsolationStreamPost

export const zAudioIsolationStreamHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

/**
 * Successful Response
 */
export const zAudioIsolationStreamResponse = z.string()

export const zCreateDubbingBody = zBodyDubAVideoOrAnAudioFileV1DubbingPost

export const zCreateDubbingHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

/**
 * Successful Response
 */
export const zCreateDubbingResponse = zDoDubbingResponseModel

export const zDubBody =
  zBodyDubsAllOrSomeSegmentsAndLanguagesV1DubbingResourceDubbingIdDubPost

export const zDubHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

export const zDubPath = z.object({
  dubbing_id: z.string(),
})

/**
 * Successful Response
 */
export const zDubResponse = zSegmentDubResponse

export const zAddLanguageBody =
  zBodyAddALanguageToTheResourceV1DubbingResourceDubbingIdLanguagePost

export const zAddLanguageHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

export const zAddLanguagePath = z.object({
  dubbing_id: z.string(),
})

/**
 * Successful Response
 */
export const zAddLanguageResponse = zLanguageAddedResponse

export const zMigrateSegmentsBody =
  zBodyMoveSegmentsBetweenSpeakersV1DubbingResourceDubbingIdMigrateSegmentsPost

export const zMigrateSegmentsHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

export const zMigrateSegmentsPath = z.object({
  dubbing_id: z.string(),
})

/**
 * Successful Response
 */
export const zMigrateSegmentsResponse = zSegmentMigrationResponse

export const zRenderBody =
  zBodyRenderAudioOrVideoForTheGivenLanguageV1DubbingResourceDubbingIdRenderLanguagePost

export const zRenderHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

export const zRenderPath = z.object({
  dubbing_id: z.string(),
  language: z.string(),
})

/**
 * Successful Response
 */
export const zRenderResponse = zDubbingRenderResponseModel

export const zCreateSpeakerBody =
  zBodyCreateANewSpeakerV1DubbingResourceDubbingIdSpeakerPost

export const zCreateSpeakerHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

export const zCreateSpeakerPath = z.object({
  dubbing_id: z.string(),
})

/**
 * Successful Response
 */
export const zCreateSpeakerResponse = zSpeakerCreatedResponse

export const zCreateClipBody = zSegmentCreatePayload

export const zCreateClipHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

export const zCreateClipPath = z.object({
  dubbing_id: z.string(),
  speaker_id: z.string(),
})

/**
 * Successful Response
 */
export const zCreateClipResponse = zSegmentCreateResponse

export const zTranscribeBody =
  zBodyTranscribesSegmentsV1DubbingResourceDubbingIdTranscribePost

export const zTranscribeHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

export const zTranscribePath = z.object({
  dubbing_id: z.string(),
})

/**
 * Successful Response
 */
export const zTranscribeResponse = zSegmentTranscriptionResponse

export const zTranslateBody =
  zBodyTranslatesAllOrSomeSegmentsAndLanguagesV1DubbingResourceDubbingIdTranslatePost

export const zTranslateHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

export const zTranslatePath = z.object({
  dubbing_id: z.string(),
})

/**
 * Successful Response
 */
export const zTranslateResponse = zSegmentTranslationResponse

export const zForcedAlignmentBody =
  zBodyCreateForcedAlignmentV1ForcedAlignmentPost

export const zForcedAlignmentHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

/**
 * Successful Response
 */
export const zForcedAlignmentResponse = zForcedAlignmentResponseModel

export const zVideoToMusicBody = zBodyVideoToMusicV1MusicVideoToMusicPost

export const zVideoToMusicHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

export const zVideoToMusicQuery = z.object({
  output_format: zAllowedOutputFormats.optional(),
})

/**
 * Generated audio file matching the video. Content-Type and file extension depend on the output_format parameter (default mp3).
 */
export const zVideoToMusicResponse = z.string()

export const zGetSimilarLibraryVoicesBody =
  zBodyGetSimilarLibraryVoicesV1SimilarVoicesPost

export const zGetSimilarLibraryVoicesHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

/**
 * Successful Response
 */
export const zGetSimilarLibraryVoicesResponse = zGetLibraryVoicesResponseModel

export const zSoundGenerationBody = zBodySoundGenerationV1SoundGenerationPost

export const zSoundGenerationHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

export const zSoundGenerationQuery = z.object({
  output_format: zAllowedOutputFormats.optional(),
})

/**
 * The generated sound effect as an MP3 file
 */
export const zSoundGenerationResponse = z.string()

export const zSpeechToSpeechFullBody =
  zBodySpeechToSpeechV1SpeechToSpeechVoiceIdPost

export const zSpeechToSpeechFullHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

export const zSpeechToSpeechFullPath = z.object({
  voice_id: z.string(),
})

export const zSpeechToSpeechFullQuery = z.object({
  enable_logging: z.boolean().optional().default(true),
  optimize_streaming_latency: z.union([z.int(), z.unknown()]).optional(),
  output_format: z
    .enum([
      'alaw_8000',
      'mp3_22050_32',
      'mp3_24000_48',
      'mp3_44100_128',
      'mp3_44100_192',
      'mp3_44100_32',
      'mp3_44100_64',
      'mp3_44100_96',
      'opus_48000_128',
      'opus_48000_192',
      'opus_48000_32',
      'opus_48000_64',
      'opus_48000_96',
      'pcm_16000',
      'pcm_22050',
      'pcm_24000',
      'pcm_32000',
      'pcm_44100',
      'pcm_48000',
      'pcm_8000',
      'ulaw_8000',
      'wav_16000',
      'wav_22050',
      'wav_24000',
      'wav_32000',
      'wav_44100',
      'wav_48000',
      'wav_8000',
    ])
    .optional()
    .default('mp3_44100_128'),
})

/**
 * The generated audio file
 */
export const zSpeechToSpeechFullResponse = z.string()

export const zSpeechToSpeechStreamBody =
  zBodySpeechToSpeechStreamingV1SpeechToSpeechVoiceIdStreamPost

export const zSpeechToSpeechStreamHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

export const zSpeechToSpeechStreamPath = z.object({
  voice_id: z.string(),
})

export const zSpeechToSpeechStreamQuery = z.object({
  enable_logging: z.boolean().optional().default(true),
  optimize_streaming_latency: z.union([z.int(), z.unknown()]).optional(),
  output_format: z
    .enum([
      'mp3_22050_32',
      'mp3_24000_48',
      'mp3_44100_32',
      'mp3_44100_64',
      'mp3_44100_96',
      'mp3_44100_128',
      'mp3_44100_192',
      'pcm_8000',
      'pcm_16000',
      'pcm_22050',
      'pcm_24000',
      'pcm_32000',
      'pcm_44100',
      'pcm_48000',
      'ulaw_8000',
      'alaw_8000',
      'opus_48000_32',
      'opus_48000_64',
      'opus_48000_96',
      'opus_48000_128',
      'opus_48000_192',
    ])
    .optional()
    .default('mp3_44100_128'),
})

/**
 * Streaming audio data
 */
export const zSpeechToSpeechStreamResponse = z.string()

export const zSpeechToTextBody = zBodySpeechToTextV1SpeechToTextPost

export const zSpeechToTextHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

export const zSpeechToTextQuery = z.object({
  enable_logging: z.boolean().optional().default(true),
})

export const zSpeechToTextResponse = z.union([
  z.union([
    zSpeechToTextChunkResponseModel,
    zMultichannelSpeechToTextResponseModel,
    zSpeechToTextWebhookResponseModel,
  ]),
  z.unknown(),
])

export const zTextToDialogueBody =
  zBodyTextToDialogueMultiVoiceV1TextToDialoguePost

export const zTextToDialogueHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

export const zTextToDialogueQuery = z.object({
  output_format: z
    .enum([
      'alaw_8000',
      'mp3_22050_32',
      'mp3_24000_48',
      'mp3_44100_128',
      'mp3_44100_192',
      'mp3_44100_32',
      'mp3_44100_64',
      'mp3_44100_96',
      'opus_48000_128',
      'opus_48000_192',
      'opus_48000_32',
      'opus_48000_64',
      'opus_48000_96',
      'pcm_16000',
      'pcm_22050',
      'pcm_24000',
      'pcm_32000',
      'pcm_44100',
      'pcm_48000',
      'pcm_8000',
      'ulaw_8000',
      'wav_16000',
      'wav_22050',
      'wav_24000',
      'wav_32000',
      'wav_44100',
      'wav_48000',
      'wav_8000',
    ])
    .optional()
    .default('mp3_44100_128'),
  enable_logging: z.boolean().optional().default(true),
})

/**
 * The generated audio file
 */
export const zTextToDialogueResponse = z.string()

export const zTextToDialogueStreamBody =
  zBodyTextToDialogueMultiVoiceStreamingV1TextToDialogueStreamPost

export const zTextToDialogueStreamHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

export const zTextToDialogueStreamQuery = z.object({
  output_format: zAllowedOutputFormats.optional(),
  enable_logging: z.boolean().optional().default(true),
})

/**
 * Streaming audio data
 */
export const zTextToDialogueStreamResponse = z.string()

export const zTextToDialogueStreamWithTimestampsBody =
  zBodyTextToDialogueStreamWithTimestamps

export const zTextToDialogueStreamWithTimestampsHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

export const zTextToDialogueStreamWithTimestampsQuery = z.object({
  output_format: zAllowedOutputFormats.optional(),
  enable_logging: z.boolean().optional().default(true),
})

/**
 * Stream of transcription chunks
 */
export const zTextToDialogueStreamWithTimestampsResponse =
  zStreamingAudioChunkWithTimestampsAndVoiceSegmentsResponseModel

export const zTextToDialogueFullWithTimestampsBody =
  zBodyTextToDialogueFullWithTimestamps

export const zTextToDialogueFullWithTimestampsHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

export const zTextToDialogueFullWithTimestampsQuery = z.object({
  output_format: z
    .enum([
      'alaw_8000',
      'mp3_22050_32',
      'mp3_24000_48',
      'mp3_44100_128',
      'mp3_44100_192',
      'mp3_44100_32',
      'mp3_44100_64',
      'mp3_44100_96',
      'opus_48000_128',
      'opus_48000_192',
      'opus_48000_32',
      'opus_48000_64',
      'opus_48000_96',
      'pcm_16000',
      'pcm_22050',
      'pcm_24000',
      'pcm_32000',
      'pcm_44100',
      'pcm_48000',
      'pcm_8000',
      'ulaw_8000',
      'wav_16000',
      'wav_22050',
      'wav_24000',
      'wav_32000',
      'wav_44100',
      'wav_48000',
      'wav_8000',
    ])
    .optional()
    .default('mp3_44100_128'),
  enable_logging: z.boolean().optional().default(true),
})

/**
 * Successful Response
 */
export const zTextToDialogueFullWithTimestampsResponse =
  zAudioWithTimestampsAndVoiceSegmentsResponseModel

export const zTextToSpeechFullBody = zBodyTextToSpeechFull

export const zTextToSpeechFullHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

export const zTextToSpeechFullPath = z.object({
  voice_id: z.string(),
})

export const zTextToSpeechFullQuery = z.object({
  enable_logging: z.boolean().optional().default(true),
  optimize_streaming_latency: z.union([z.int(), z.unknown()]).optional(),
  output_format: z
    .enum([
      'alaw_8000',
      'mp3_22050_32',
      'mp3_24000_48',
      'mp3_44100_128',
      'mp3_44100_192',
      'mp3_44100_32',
      'mp3_44100_64',
      'mp3_44100_96',
      'opus_48000_128',
      'opus_48000_192',
      'opus_48000_32',
      'opus_48000_64',
      'opus_48000_96',
      'pcm_16000',
      'pcm_22050',
      'pcm_24000',
      'pcm_32000',
      'pcm_44100',
      'pcm_48000',
      'pcm_8000',
      'ulaw_8000',
      'wav_16000',
      'wav_22050',
      'wav_24000',
      'wav_32000',
      'wav_44100',
      'wav_48000',
      'wav_8000',
    ])
    .optional()
    .default('mp3_44100_128'),
})

/**
 * The generated audio file
 */
export const zTextToSpeechFullResponse = z.string()

export const zTextToSpeechStreamBody = zBodyTextToSpeechStream

export const zTextToSpeechStreamHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

export const zTextToSpeechStreamPath = z.object({
  voice_id: z.string(),
})

export const zTextToSpeechStreamQuery = z.object({
  enable_logging: z.boolean().optional().default(true),
  optimize_streaming_latency: z.union([z.int(), z.unknown()]).optional(),
  output_format: z
    .enum([
      'mp3_22050_32',
      'mp3_24000_48',
      'mp3_44100_32',
      'mp3_44100_64',
      'mp3_44100_96',
      'mp3_44100_128',
      'mp3_44100_192',
      'pcm_8000',
      'pcm_16000',
      'pcm_22050',
      'pcm_24000',
      'pcm_32000',
      'pcm_44100',
      'pcm_48000',
      'ulaw_8000',
      'alaw_8000',
      'opus_48000_32',
      'opus_48000_64',
      'opus_48000_96',
      'opus_48000_128',
      'opus_48000_192',
    ])
    .optional()
    .default('mp3_44100_128'),
})

/**
 * Streaming audio data
 */
export const zTextToSpeechStreamResponse = z.string()

export const zTextToSpeechStreamWithTimestampsBody =
  zBodyTextToSpeechStreamWithTimestamps

export const zTextToSpeechStreamWithTimestampsHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

export const zTextToSpeechStreamWithTimestampsPath = z.object({
  voice_id: z.string(),
})

export const zTextToSpeechStreamWithTimestampsQuery = z.object({
  enable_logging: z.boolean().optional().default(true),
  optimize_streaming_latency: z.union([z.int(), z.unknown()]).optional(),
  output_format: z
    .enum([
      'mp3_22050_32',
      'mp3_24000_48',
      'mp3_44100_32',
      'mp3_44100_64',
      'mp3_44100_96',
      'mp3_44100_128',
      'mp3_44100_192',
      'pcm_8000',
      'pcm_16000',
      'pcm_22050',
      'pcm_24000',
      'pcm_32000',
      'pcm_44100',
      'pcm_48000',
      'ulaw_8000',
      'alaw_8000',
      'opus_48000_32',
      'opus_48000_64',
      'opus_48000_96',
      'opus_48000_128',
      'opus_48000_192',
    ])
    .optional()
    .default('mp3_44100_128'),
})

/**
 * Stream of transcription chunks
 */
export const zTextToSpeechStreamWithTimestampsResponse =
  zStreamingAudioChunkWithTimestampsResponseModel

export const zTextToSpeechFullWithTimestampsBody =
  zBodyTextToSpeechFullWithTimestamps

export const zTextToSpeechFullWithTimestampsHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

export const zTextToSpeechFullWithTimestampsPath = z.object({
  voice_id: z.string(),
})

export const zTextToSpeechFullWithTimestampsQuery = z.object({
  enable_logging: z.boolean().optional().default(true),
  optimize_streaming_latency: z.union([z.int(), z.unknown()]).optional(),
  output_format: z
    .enum([
      'alaw_8000',
      'mp3_22050_32',
      'mp3_24000_48',
      'mp3_44100_128',
      'mp3_44100_192',
      'mp3_44100_32',
      'mp3_44100_64',
      'mp3_44100_96',
      'opus_48000_128',
      'opus_48000_192',
      'opus_48000_32',
      'opus_48000_64',
      'opus_48000_96',
      'pcm_16000',
      'pcm_22050',
      'pcm_24000',
      'pcm_32000',
      'pcm_44100',
      'pcm_48000',
      'pcm_8000',
      'ulaw_8000',
      'wav_16000',
      'wav_22050',
      'wav_24000',
      'wav_32000',
      'wav_44100',
      'wav_48000',
      'wav_8000',
    ])
    .optional()
    .default('mp3_44100_128'),
})

/**
 * Successful Response
 */
export const zTextToSpeechFullWithTimestampsResponse =
  zAudioWithTimestampsResponseModel

export const zCreateVoiceBody =
  zBodyCreateANewVoiceFromVoicePreviewV1TextToVoicePost

export const zCreateVoiceHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

/**
 * Successful Response
 */
export const zCreateVoiceResponse = zVoiceResponseModel

export const zTextToVoiceRemixBody = zVoiceRemixRequestModel

export const zTextToVoiceRemixHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

export const zTextToVoiceRemixPath = z.object({
  voice_id: z.string(),
})

export const zTextToVoiceRemixQuery = z.object({
  output_format: zAllowedOutputFormats.optional(),
})

/**
 * Successful Response
 */
export const zTextToVoiceRemixResponse = zVoicePreviewsResponseModel

export const zTextToVoiceBody = zVoicePreviewsRequestModel

export const zTextToVoiceHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

export const zTextToVoiceQuery = z.object({
  output_format: zAllowedOutputFormats.optional(),
})

/**
 * Successful Response
 */
export const zTextToVoiceResponse = zVoicePreviewsResponseModel

export const zTextToVoiceDesignBody = zVoiceDesignRequestModel

export const zTextToVoiceDesignHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

export const zTextToVoiceDesignQuery = z.object({
  output_format: zAllowedOutputFormats.optional(),
})

/**
 * Successful Response
 */
export const zTextToVoiceDesignResponse = zVoicePreviewsResponseModel

export const zEditVoiceBody = zBodyEditVoiceV1VoicesVoiceIdEditPost

export const zEditVoiceHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

export const zEditVoicePath = z.object({
  voice_id: z.string(),
})

/**
 * Successful Response
 */
export const zEditVoiceResponse = zEditVoiceResponseModel

export const zEditVoiceSettingsBody = zVoiceSettingsResponseModel

export const zEditVoiceSettingsHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

export const zEditVoiceSettingsPath = z.object({
  voice_id: z.string(),
})

/**
 * Successful Response
 */
export const zEditVoiceSettingsResponse = zEditVoiceSettingsResponseModel

export const zAddVoiceBody = zBodyAddVoiceV1VoicesAddPost

export const zAddVoiceHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

/**
 * Successful Response
 */
export const zAddVoiceResponse = zAddVoiceIvcResponseModel

export const zAddSharingVoiceBody =
  zBodyAddSharedVoiceV1VoicesAddPublicUserIdVoiceIdPost

export const zAddSharingVoiceHeaders = z.object({
  'xi-api-key': z.union([z.string(), z.unknown()]).optional(),
})

export const zAddSharingVoicePath = z.object({
  public_user_id: z.string(),
  voice_id: z.string(),
})

/**
 * Successful Response
 */
export const zAddSharingVoiceResponse = zAddVoiceResponseModel
