// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod'

/**
 * Request message for PredictionService.Predict.
 */
export const zPredictRequest = z.object({
  parameters: z.unknown().optional(),
  instances: z.array(z.unknown()).optional(),
})

/**
 * Response message for [PredictionService.Predict].
 */
export const zPredictResponse = z.object({
  predictions: z.array(z.unknown()).optional(),
})

export const zGenerativelanguageModelsPredictBody = zPredictRequest

export const zGenerativelanguageModelsPredictPath = z.object({
  model: z.string(),
})

/**
 * Success
 */
export const zGenerativelanguageModelsPredictResponse = zPredictResponse
