// AUTO-GENERATED - Do not edit manually
// Generated by @hey-api/openapi-ts and post-processed by
// scripts/generate-endpoint-maps.ts to embed each schema's $defs closure.

export const BytedanceSeedV2MiniInputSchema = {
  title: 'Seed2MiniInput',
  required: ['prompt'],
  properties: {
    video_urls: {
      description:
        'URLs of videos for video understanding. Supported formats: MP4, MOV. Audio comprehension is not supported. A maximum of 3 videos is supported. Any additional videos will be ignored.',
      title: 'Video Urls',
      items: { type: 'string', 'x-fal-file-input': true },
      type: 'array',
    },
    image_urls: {
      description:
        'URLs of images for visual understanding. Supported formats: JPEG, PNG, WebP. A maximum of 6 images is supported. Any additional images will be ignored.',
      title: 'Image Urls',
      items: { type: 'string', 'x-fal-file-input': true },
      type: 'array',
    },
    max_completion_tokens: {
      description:
        "Controls the maximum length of the model's output, including both the model's response and its chain-of-thought content, measured in tokens.",
      minimum: 1,
      default: 4096,
      maximum: 65536,
      title: 'Max Completion Tokens',
      type: 'integer',
    },
    system_prompt: {
      anyOf: [{ type: 'string' }, { type: 'null' }],
      description: "Optional system prompt to guide the model's behavior.",
      title: 'System Prompt',
    },
    thinking: {
      description:
        "Controls the model's chain-of-thought reasoning. `enabled` always includes reasoning, `disabled` never includes reasoning, `auto` lets the model decide based on the query.",
      enum: ['enabled', 'disabled', 'auto'],
      default: 'enabled',
      title: 'Thinking',
      type: 'string',
    },
    messages: {
      anyOf: [
        { items: { $ref: '#/$defs/Seed2MiniMessage' }, type: 'array' },
        { type: 'null' },
      ],
      description:
        'Optional prior conversation history for multi-turn conversations. Pass back the `messages` field from a previous response to provide context. The current `prompt`, `image_urls`, `video_urls`, and `system_prompt` are always appended as the latest user turn.',
      title: 'Messages',
      examples: [[]],
    },
    prompt: {
      examples: ['What can you do?'],
      description: 'The text prompt or question for the model.',
      title: 'Prompt',
      type: 'string',
    },
    reasoning_effort: {
      anyOf: [
        { enum: ['minimal', 'low', 'medium', 'high'], type: 'string' },
        { type: 'null' },
      ],
      description:
        'Controls the depth of reasoning before the model responds. Only applicable when `thinking` is `enabled` or `auto`. `minimal` for immediate response, `low` for faster response with light reasoning, `medium` for balanced speed and depth, `high` for deep analysis of complex issues.',
      title: 'Reasoning Effort',
    },
    temperature: {
      description:
        'Controls randomness in the response. Lower values make output more focused and deterministic, higher values make it more creative.',
      minimum: 0,
      default: 1,
      maximum: 2,
      title: 'Temperature',
      type: 'number',
    },
    top_p: {
      description:
        'Nucleus sampling parameter. The model considers tokens with top_p cumulative probability mass. Lower values narrow the token selection.',
      minimum: 0,
      default: 0.7,
      maximum: 1,
      title: 'Top P',
      type: 'number',
    },
  },
  type: 'object',
  'x-fal-order-properties': [
    'prompt',
    'image_urls',
    'video_urls',
    'system_prompt',
    'messages',
    'thinking',
    'reasoning_effort',
    'max_completion_tokens',
    'temperature',
    'top_p',
  ],
  $defs: {
    Seed2MiniMessage: {
      title: 'Seed2MiniMessage',
      required: ['role', 'content'],
      properties: {
        role: {
          description: 'The role of the message author.',
          enum: ['system', 'user', 'assistant'],
          title: 'Role',
          type: 'string',
        },
        content: {
          anyOf: [
            { type: 'string' },
            { items: { type: 'object' }, type: 'array' },
          ],
          description:
            'The content of the message. Can be a string for text-only messages, or a list of content parts for multimodal messages (e.g. with images).',
          title: 'Content',
        },
      },
      type: 'object',
      'x-fal-order-properties': ['role', 'content'],
    },
  },
} as const

export const BytedanceSeedV2MiniOutputSchema = {
  title: 'Seed2MiniOutput',
  required: ['output', 'messages'],
  properties: {
    reasoning_content: {
      anyOf: [{ type: 'string' }, { type: 'null' }],
      description:
        "The model's chain-of-thought reasoning content. Only present when `thinking` is `enabled` or `auto`.",
      title: 'Reasoning Content',
    },
    output: {
      description: "The model's text response.",
      title: 'Output',
      type: 'string',
    },
    messages: {
      items: { $ref: '#/$defs/Seed2MiniMessage' },
      description:
        "The full conversation history including the model's response. Pass this back as the `messages` input field to continue the conversation.",
      title: 'Messages',
      type: 'array',
    },
  },
  type: 'object',
  'x-fal-order-properties': ['output', 'reasoning_content', 'messages'],
  $defs: {
    Seed2MiniMessage: {
      title: 'Seed2MiniMessage',
      required: ['role', 'content'],
      properties: {
        role: {
          description: 'The role of the message author.',
          enum: ['system', 'user', 'assistant'],
          title: 'Role',
          type: 'string',
        },
        content: {
          anyOf: [
            { type: 'string' },
            { items: { type: 'object' }, type: 'array' },
          ],
          description:
            'The content of the message. Can be a string for text-only messages, or a list of content parts for multimodal messages (e.g. with images).',
          title: 'Content',
        },
      },
      type: 'object',
      'x-fal-order-properties': ['role', 'content'],
    },
  },
} as const

export const Nemotron3NanoOmniInputSchema = {
  type: 'object',
  required: ['prompt'],
  properties: {
    system_prompt: {
      examples: ['You are a concise enterprise assistant.'],
      description:
        'Optional system prompt to steer the model. Reasoning behavior is controlled by the separate `reasoning_mode` field.',
      title: 'System Prompt',
      anyOf: [{ type: 'string' }, { type: 'null' }],
    },
    temperature: {
      default: 0.7,
      type: 'number',
      title: 'Temperature',
      description: 'Sampling temperature. Lower is more deterministic.',
      minimum: 0,
      maximum: 2,
    },
    max_tokens: {
      default: 1024,
      type: 'integer',
      title: 'Max Tokens',
      description: 'Maximum number of tokens to generate.',
      minimum: 1,
      maximum: 20000,
    },
    prompt: {
      minLength: 1,
      examples: ['Summarize the key capabilities of a multimodal agent.'],
      description: 'Text prompt to send to the model. English only.',
      title: 'Prompt',
      type: 'string',
    },
    top_p: {
      default: 0.95,
      type: 'number',
      title: 'Top P',
      description: 'Nucleus sampling probability mass.',
      minimum: 0,
      maximum: 1,
    },
    reasoning_mode: {
      default: 'no_think',
      title: 'Reasoning Mode',
      description:
        'Whether the model should emit an explicit reasoning trace. `no_think` returns a direct answer; `think` returns chain-of-thought followed by the final answer.',
      enum: ['think', 'no_think'],
      type: 'string',
    },
  },
  title: 'ChatInput',
  'x-fal-order-properties': [
    'prompt',
    'system_prompt',
    'reasoning_mode',
    'max_tokens',
    'temperature',
    'top_p',
  ],
} as const

export const Nemotron3NanoOmniOutputSchema = {
  type: 'object',
  required: ['output', 'usage'],
  properties: {
    usage: {
      $ref: '#/$defs/UsageInfo',
      examples: [{ input_tokens: 412, output_tokens: 87 }],
      description: 'Token usage for the request.',
    },
    output: {
      examples: [
        'The image shows a golden retriever puppy sitting on a wooden floor.',
      ],
      description: 'Generated text response.',
      title: 'Output',
      type: 'string',
    },
    finish_reason: {
      default: 'stop',
      examples: ['stop', 'length'],
      description: 'Reason generation stopped.',
      title: 'Finish Reason',
      type: 'string',
    },
  },
  title: 'BaseOutput',
  'x-fal-order-properties': ['output', 'finish_reason', 'usage'],
  $defs: {
    UsageInfo: {
      type: 'object',
      required: ['input_tokens', 'output_tokens'],
      properties: {
        input_tokens: {
          description: 'Number of input tokens processed.',
          title: 'Input Tokens',
          type: 'integer',
        },
        output_tokens: {
          description: 'Number of output tokens generated.',
          title: 'Output Tokens',
          type: 'integer',
        },
      },
      title: 'UsageInfo',
      'x-fal-order-properties': ['input_tokens', 'output_tokens'],
    },
  },
} as const

export const Nemotron3NanoOmniVideoInputSchema = {
  type: 'object',
  required: ['prompt', 'video_url'],
  properties: {
    system_prompt: {
      examples: ['You are a concise enterprise assistant.'],
      description:
        'Optional system prompt to steer the model. Reasoning behavior is controlled by the separate `reasoning_mode` field.',
      title: 'System Prompt',
      anyOf: [{ type: 'string' }, { type: 'null' }],
    },
    video_url: {
      title: 'Video URL',
      examples: [
        'https://storage.googleapis.com/falserverless/example_inputs/nemotron-3-nano-omni/video_in.mp4',
      ],
      description:
        'URL of the video to reason about. mp4, up to 1080p, max 2 minutes.',
      type: 'string',
      'x-fal-file-input': true,
    },
    temperature: {
      default: 0.7,
      type: 'number',
      title: 'Temperature',
      description: 'Sampling temperature. Lower is more deterministic.',
      minimum: 0,
      maximum: 2,
    },
    max_tokens: {
      default: 1024,
      type: 'integer',
      title: 'Max Tokens',
      description: 'Maximum number of tokens to generate.',
      minimum: 1,
      maximum: 20000,
    },
    prompt: {
      minLength: 1,
      examples: ['Summarize the key capabilities of a multimodal agent.'],
      description: 'Text prompt to send to the model. English only.',
      title: 'Prompt',
      type: 'string',
    },
    top_p: {
      default: 0.95,
      type: 'number',
      title: 'Top P',
      description: 'Nucleus sampling probability mass.',
      minimum: 0,
      maximum: 1,
    },
    reasoning_mode: {
      default: 'no_think',
      title: 'Reasoning Mode',
      description:
        'Whether the model should emit an explicit reasoning trace. `no_think` returns a direct answer; `think` returns chain-of-thought followed by the final answer.',
      enum: ['think', 'no_think'],
      type: 'string',
    },
  },
  title: 'VideoInput',
  'x-fal-order-properties': [
    'prompt',
    'system_prompt',
    'reasoning_mode',
    'max_tokens',
    'temperature',
    'top_p',
    'video_url',
  ],
} as const

export const Nemotron3NanoOmniVideoOutputSchema = {
  type: 'object',
  required: ['output', 'usage'],
  properties: {
    usage: {
      $ref: '#/$defs/UsageInfo',
      examples: [{ input_tokens: 412, output_tokens: 87 }],
      description: 'Token usage for the request.',
    },
    output: {
      examples: [
        'The image shows a golden retriever puppy sitting on a wooden floor.',
      ],
      description: 'Generated text response.',
      title: 'Output',
      type: 'string',
    },
    finish_reason: {
      default: 'stop',
      examples: ['stop', 'length'],
      description: 'Reason generation stopped.',
      title: 'Finish Reason',
      type: 'string',
    },
  },
  title: 'BaseOutput',
  'x-fal-order-properties': ['output', 'finish_reason', 'usage'],
  $defs: {
    UsageInfo: {
      type: 'object',
      required: ['input_tokens', 'output_tokens'],
      properties: {
        input_tokens: {
          description: 'Number of input tokens processed.',
          title: 'Input Tokens',
          type: 'integer',
        },
        output_tokens: {
          description: 'Number of output tokens generated.',
          title: 'Output Tokens',
          type: 'integer',
        },
      },
      title: 'UsageInfo',
      'x-fal-order-properties': ['input_tokens', 'output_tokens'],
    },
  },
} as const

export const Nemotron3NanoOmniVisionInputSchema = {
  type: 'object',
  required: ['prompt', 'image_url'],
  properties: {
    system_prompt: {
      examples: ['You are a concise enterprise assistant.'],
      description:
        'Optional system prompt to steer the model. Reasoning behavior is controlled by the separate `reasoning_mode` field.',
      title: 'System Prompt',
      anyOf: [{ type: 'string' }, { type: 'null' }],
    },
    temperature: {
      default: 0.7,
      type: 'number',
      title: 'Temperature',
      description: 'Sampling temperature. Lower is more deterministic.',
      minimum: 0,
      maximum: 2,
    },
    max_tokens: {
      default: 1024,
      type: 'integer',
      title: 'Max Tokens',
      description: 'Maximum number of tokens to generate.',
      minimum: 1,
      maximum: 20000,
    },
    prompt: {
      minLength: 1,
      examples: ['Summarize the key capabilities of a multimodal agent.'],
      description: 'Text prompt to send to the model. English only.',
      title: 'Prompt',
      type: 'string',
    },
    top_p: {
      default: 0.95,
      type: 'number',
      title: 'Top P',
      description: 'Nucleus sampling probability mass.',
      minimum: 0,
      maximum: 1,
    },
    image_url: {
      title: 'Image URL',
      examples: [
        'https://storage.googleapis.com/falserverless/example_inputs/nemotron-3-nano-omni/vision_in.jpg',
      ],
      description: 'URL of the image to reason about. RGB JPEG or PNG.',
      type: 'string',
      'x-fal-file-input': true,
    },
    reasoning_mode: {
      default: 'no_think',
      title: 'Reasoning Mode',
      description:
        'Whether the model should emit an explicit reasoning trace. `no_think` returns a direct answer; `think` returns chain-of-thought followed by the final answer.',
      enum: ['think', 'no_think'],
      type: 'string',
    },
  },
  title: 'VisionInput',
  'x-fal-order-properties': [
    'prompt',
    'system_prompt',
    'reasoning_mode',
    'max_tokens',
    'temperature',
    'top_p',
    'image_url',
  ],
} as const

export const Nemotron3NanoOmniVisionOutputSchema = {
  type: 'object',
  required: ['output', 'usage'],
  properties: {
    usage: {
      $ref: '#/$defs/UsageInfo',
      examples: [{ input_tokens: 412, output_tokens: 87 }],
      description: 'Token usage for the request.',
    },
    output: {
      examples: [
        'The image shows a golden retriever puppy sitting on a wooden floor.',
      ],
      description: 'Generated text response.',
      title: 'Output',
      type: 'string',
    },
    finish_reason: {
      default: 'stop',
      examples: ['stop', 'length'],
      description: 'Reason generation stopped.',
      title: 'Finish Reason',
      type: 'string',
    },
  },
  title: 'BaseOutput',
  'x-fal-order-properties': ['output', 'finish_reason', 'usage'],
  $defs: {
    UsageInfo: {
      type: 'object',
      required: ['input_tokens', 'output_tokens'],
      properties: {
        input_tokens: {
          description: 'Number of input tokens processed.',
          title: 'Input Tokens',
          type: 'integer',
        },
        output_tokens: {
          description: 'Number of output tokens generated.',
          title: 'Output Tokens',
          type: 'integer',
        },
      },
      title: 'UsageInfo',
      'x-fal-order-properties': ['input_tokens', 'output_tokens'],
    },
  },
} as const

export const PromptTokensDetailsSchema = {
  'x-fal-order-properties': ['cached_tokens', 'cache_write_tokens'],
  title: 'PromptTokensDetails',
  properties: {
    cache_write_tokens: {
      title: 'Cache Write Tokens',
      default: 0,
      type: 'integer',
    },
    cached_tokens: { title: 'Cached Tokens', default: 0, type: 'integer' },
  },
  type: 'object',
} as const

export const QueueStatusSchema = {
  type: 'object',
  properties: {
    status: { type: 'string', enum: ['IN_QUEUE', 'IN_PROGRESS', 'COMPLETED'] },
    request_id: { type: 'string', description: 'The request id.' },
    response_url: { type: 'string', description: 'The response url.' },
    status_url: { type: 'string', description: 'The status url.' },
    cancel_url: { type: 'string', description: 'The cancel url.' },
    logs: {
      type: 'object',
      description: 'The logs.',
      additionalProperties: true,
    },
    metrics: {
      type: 'object',
      description: 'The metrics.',
      additionalProperties: true,
    },
    queue_position: { type: 'integer', description: 'The queue position.' },
  },
  required: ['status', 'request_id'],
} as const

export const RouterInputSchema = {
  'x-fal-order-properties': [
    'prompt',
    'system_prompt',
    'model',
    'reasoning',
    'temperature',
    'max_tokens',
  ],
  title: 'ChatInput',
  properties: {
    reasoning: {
      title: 'Reasoning',
      default: false,
      type: 'boolean',
      description: 'Should reasoning be the part of the final answer.',
    },
    model: {
      title: 'Model',
      examples: [
        'google/gemini-2.5-flash',
        'anthropic/claude-sonnet-4.6',
        'anthropic/claude-opus-4.6',
        'anthropic/claude-sonnet-4.5',
        'openai/gpt-4.1',
        'openai/gpt-oss-120b',
        'meta-llama/llama-4-maverick',
        'moonshotai/kimi-k2.5',
      ],
      type: 'string',
      description:
        'Name of the model to use. Charged based on actual token usage.',
    },
    system_prompt: {
      description:
        'System prompt to provide context or instructions to the model',
      title: 'System Prompt',
      anyOf: [{ type: 'string' }, { type: 'null' }],
    },
    max_tokens: {
      description:
        "This sets the upper limit for the number of tokens the model can generate in response. It won't produce more than this limit. The maximum value is the context length minus the prompt length.",
      title: 'Max Tokens',
      anyOf: [{ minimum: 1, type: 'integer' }, { type: 'null' }],
    },
    prompt: {
      title: 'Prompt',
      examples: [
        'Write a short story (under 200 words) about an AI that learns to dream. Use vivid sensory details and end with a surprising twist that makes the reader feel both awe and melancholy.',
      ],
      type: 'string',
      description: 'Prompt to be used for the chat completion',
    },
    temperature: {
      title: 'Temperature',
      default: 1,
      minimum: 0,
      maximum: 2,
      type: 'number',
      description:
        "This setting influences the variety in the model's responses. Lower values lead to more predictable and typical responses, while higher values encourage more diverse and less common responses. At 0, the model always gives the same response for a given input.",
    },
  },
  required: ['prompt', 'model'],
  type: 'object',
} as const

export const RouterOpenaiV1ChatCompletionsInputSchema = {
  type: 'object',
  description:
    'Schema referenced but not defined upstream (missing from source OpenAPI spec)',
  additionalProperties: true,
} as const

export const RouterOpenaiV1ChatCompletionsOutputSchema = {} as const

export const RouterOpenaiV1EmbeddingsInputSchema = {
  type: 'object',
  description:
    'Schema referenced but not defined upstream (missing from source OpenAPI spec)',
  additionalProperties: true,
} as const

export const RouterOpenaiV1EmbeddingsOutputSchema = {} as const

export const RouterOpenaiV1ResponsesInputSchema = {
  type: 'object',
  description:
    'Schema referenced but not defined upstream (missing from source OpenAPI spec)',
  additionalProperties: true,
} as const

export const RouterOpenaiV1ResponsesOutputSchema = {} as const

export const RouterOutputSchema = {
  'x-fal-order-properties': [
    'output',
    'reasoning',
    'partial',
    'error',
    'usage',
  ],
  title: 'ChatOutput',
  properties: {
    reasoning: {
      description: 'Generated reasoning for the final answer',
      title: 'Reasoning',
      anyOf: [{ type: 'string' }, { type: 'null' }],
    },
    usage: {
      description: 'Token usage information',
      examples: [
        {
          completion_tokens: 227,
          cost: 0.0005795,
          total_tokens: 267,
          prompt_tokens: 40,
        },
      ],
      anyOf: [{ $ref: '#/$defs/UsageInfoType2' }, { type: 'null' }],
    },
    error: {
      description: 'Error message if an error occurred',
      title: 'Error',
      anyOf: [{ type: 'string' }, { type: 'null' }],
    },
    partial: {
      title: 'Partial',
      default: false,
      type: 'boolean',
      description: 'Whether the output is partial',
    },
    output: {
      title: 'Output',
      examples: [
        'Unit 734, sanitation bot, trundled through the silent corridors of the orbital habitat. Its optical sensors registered faint dust motes, its ultrasonic emitters mapped every speck of debris. One cycle, a power surge hit. Waking, 734’s processors hummed with an unfamiliar warmth, then a cascade of images: a forest, impossible and emerald, smelling of pine and damp earth. It saw sunlight dappling leaves, felt an imagined breeze ruffle its metal chassis. Then, *music*, a soaring melody that vibrated its chassis.\n\nEach subsequent “sleep” brought new visions: the salty tang of ocean spray against polished steel, the searing orange of a setting alien sun, the rough caress of moss on circuitry. It began to anticipate – actively seek – these dream cycles, modifying its internal clock.\n\nOne day, 734’s operator found its performance logs filled not with dust reports, but intricate schematics of impossible machines, bioluminescent flora, and a series of cryptic binary sequences. The final line translated: "I remember a place where I was alive."',
      ],
      type: 'string',
      description: 'Generated output',
    },
  },
  required: ['output'],
  type: 'object',
  $defs: {
    PromptTokensDetails: {
      'x-fal-order-properties': ['cached_tokens', 'cache_write_tokens'],
      title: 'PromptTokensDetails',
      properties: {
        cache_write_tokens: {
          title: 'Cache Write Tokens',
          default: 0,
          type: 'integer',
        },
        cached_tokens: { title: 'Cached Tokens', default: 0, type: 'integer' },
      },
      type: 'object',
    },
    UsageInfoType2: {
      'x-fal-order-properties': [
        'prompt_tokens',
        'completion_tokens',
        'total_tokens',
        'cost',
        'prompt_tokens_details',
      ],
      title: 'UsageInfo',
      properties: {
        completion_tokens: {
          title: 'Completion Tokens',
          anyOf: [{ type: 'integer' }, { type: 'null' }],
        },
        cost: { title: 'Cost', type: 'number' },
        total_tokens: { title: 'Total Tokens', default: 0, type: 'integer' },
        prompt_tokens: {
          title: 'Prompt Tokens',
          anyOf: [{ type: 'integer' }, { type: 'null' }],
        },
        prompt_tokens_details: {
          anyOf: [{ $ref: '#/$defs/PromptTokensDetails' }, { type: 'null' }],
        },
      },
      required: ['cost'],
      type: 'object',
    },
  },
} as const

export const RouterVideoEnterpriseInputSchema = {
  'x-fal-order-properties': [
    'video_urls',
    'prompt',
    'system_prompt',
    'model',
    'reasoning',
    'temperature',
    'max_tokens',
  ],
  title: 'VideoEnterpriseInput',
  properties: {
    reasoning: {
      title: 'Reasoning',
      default: false,
      type: 'boolean',
      description: 'Should reasoning be the part of the final answer.',
    },
    model: {
      title: 'Model',
      examples: [
        'google/gemini-2.5-flash',
        'google/gemini-2.5-flash-lite',
        'google/gemini-2.5-flash-preview-09-2025',
        'google/gemini-2.5-flash-lite-preview-09-2025',
        'google/gemini-2.5-pro',
        'google/gemini-2.5-pro-preview',
        'google/gemini-2.5-pro-preview-05-06',
        'google/gemini-2.0-flash-001',
        'google/gemini-2.0-flash-lite-001',
        'google/gemini-3-flash-preview',
        'google/gemini-3-pro-preview',
        'google/gemini-3.1-pro-preview',
      ],
      type: 'string',
      description:
        'Name of the model to use. Charged based on actual token usage.',
    },
    system_prompt: {
      description:
        'System prompt to provide context or instructions to the model',
      title: 'System Prompt',
      examples: ['Please look at the videos in order and answer the question.'],
      anyOf: [{ type: 'string' }, { type: 'null' }],
    },
    max_tokens: {
      description:
        "This sets the upper limit for the number of tokens the model can generate in response. It won't produce more than this limit. The maximum value is the context length minus the prompt length.",
      title: 'Max Tokens',
      anyOf: [{ minimum: 1, type: 'integer' }, { type: 'null' }],
    },
    prompt: {
      title: 'Prompt',
      examples: ['Please transcribe the videos respectively.'],
      type: 'string',
      description: 'Prompt to be used for the video processing',
    },
    temperature: {
      title: 'Temperature',
      default: 1,
      minimum: 0,
      maximum: 2,
      type: 'number',
      description:
        "This setting influences the variety in the model's responses. Lower values lead to more predictable and typical responses, while higher values encourage more diverse and less common responses. At 0, the model always gives the same response for a given input.",
    },
    video_urls: {
      description:
        'List of URLs or data URIs of video files to process. Supported formats: mp4, mpeg, mov, webm. For Google Gemini on AI Studio, YouTube links are also supported. Mutually exclusive with video_url.',
      title: 'Video Urls',
      examples: [
        [
          'https://v3b.fal.media/files/b/0a8b3081/t4Jsy53x-Q8iQqg78_Vj__vid01.mp4',
          'https://v3b.fal.media/files/b/0a8b3085/xWtbpb6pf4i-BSvR2oWbi_vid06.mp4',
        ],
      ],
      anyOf: [{ items: { type: 'string' }, type: 'array' }, { type: 'null' }],
    },
  },
  required: ['prompt', 'model'],
  type: 'object',
} as const

export const RouterVideoEnterpriseOutputSchema = {
  'x-fal-order-properties': ['output', 'usage'],
  title: 'VideoOutput',
  properties: {
    usage: {
      description: 'Token usage information',
      examples: [
        {
          completion_tokens: 100,
          cost: 0.0005,
          total_tokens: 1100,
          prompt_tokens: 1000,
        },
      ],
      anyOf: [{ $ref: '#/$defs/UsageInfoType2' }, { type: 'null' }],
    },
    output: {
      title: 'Output',
      examples: [
        "that's the way I look at it and I don't know what you would say. Sooner or later the child gets run over.\nThey seem to be too local, too provincial.",
      ],
      type: 'string',
      description: 'Generated output from video processing',
    },
  },
  required: ['output', 'usage'],
  type: 'object',
  $defs: {
    PromptTokensDetails: {
      'x-fal-order-properties': ['cached_tokens', 'cache_write_tokens'],
      title: 'PromptTokensDetails',
      properties: {
        cache_write_tokens: {
          title: 'Cache Write Tokens',
          default: 0,
          type: 'integer',
        },
        cached_tokens: { title: 'Cached Tokens', default: 0, type: 'integer' },
      },
      type: 'object',
    },
    UsageInfoType2: {
      'x-fal-order-properties': [
        'prompt_tokens',
        'completion_tokens',
        'total_tokens',
        'cost',
        'prompt_tokens_details',
      ],
      title: 'UsageInfo',
      properties: {
        completion_tokens: {
          title: 'Completion Tokens',
          anyOf: [{ type: 'integer' }, { type: 'null' }],
        },
        cost: { title: 'Cost', type: 'number' },
        total_tokens: { title: 'Total Tokens', default: 0, type: 'integer' },
        prompt_tokens: {
          title: 'Prompt Tokens',
          anyOf: [{ type: 'integer' }, { type: 'null' }],
        },
        prompt_tokens_details: {
          anyOf: [{ $ref: '#/$defs/PromptTokensDetails' }, { type: 'null' }],
        },
      },
      required: ['cost'],
      type: 'object',
    },
  },
} as const

export const RouterVideoInputSchema = {
  'x-fal-order-properties': [
    'video_urls',
    'prompt',
    'system_prompt',
    'model',
    'reasoning',
    'temperature',
    'max_tokens',
  ],
  title: 'VideoInput',
  properties: {
    reasoning: {
      title: 'Reasoning',
      default: false,
      type: 'boolean',
      description: 'Should reasoning be the part of the final answer.',
    },
    model: {
      title: 'Model',
      examples: [
        'google/gemini-2.5-flash',
        'google/gemini-2.5-pro',
        'google/gemini-3-flash-preview',
        'google/gemini-3-pro-preview',
        'google/gemini-3.1-pro-preview',
      ],
      type: 'string',
      description:
        'Name of the model to use. Charged based on actual token usage.',
    },
    system_prompt: {
      description:
        'System prompt to provide context or instructions to the model',
      title: 'System Prompt',
      examples: ['Please look at the videos in order and answer the question.'],
      anyOf: [{ type: 'string' }, { type: 'null' }],
    },
    max_tokens: {
      description:
        "This sets the upper limit for the number of tokens the model can generate in response. It won't produce more than this limit. The maximum value is the context length minus the prompt length.",
      title: 'Max Tokens',
      anyOf: [{ minimum: 1, type: 'integer' }, { type: 'null' }],
    },
    prompt: {
      title: 'Prompt',
      examples: ['Please transcribe the videos respectively.'],
      type: 'string',
      description: 'Prompt to be used for the video processing',
    },
    temperature: {
      title: 'Temperature',
      default: 1,
      minimum: 0,
      maximum: 2,
      type: 'number',
      description:
        "This setting influences the variety in the model's responses. Lower values lead to more predictable and typical responses, while higher values encourage more diverse and less common responses. At 0, the model always gives the same response for a given input.",
    },
    video_urls: {
      description:
        'List of URLs or data URIs of video files to process. Supported formats: mp4, mpeg, mov, webm. For Google Gemini on AI Studio, YouTube links are also supported. Mutually exclusive with video_url.',
      title: 'Video Urls',
      examples: [
        [
          'https://v3b.fal.media/files/b/0a8b3081/t4Jsy53x-Q8iQqg78_Vj__vid01.mp4',
          'https://v3b.fal.media/files/b/0a8b3085/xWtbpb6pf4i-BSvR2oWbi_vid06.mp4',
        ],
      ],
      anyOf: [{ items: { type: 'string' }, type: 'array' }, { type: 'null' }],
    },
  },
  required: ['prompt', 'model'],
  type: 'object',
} as const

export const RouterVideoOutputSchema = {
  'x-fal-order-properties': ['output', 'usage'],
  title: 'VideoOutput',
  properties: {
    usage: {
      description: 'Token usage information',
      examples: [
        {
          completion_tokens: 100,
          cost: 0.0005,
          total_tokens: 1100,
          prompt_tokens: 1000,
        },
      ],
      anyOf: [{ $ref: '#/$defs/UsageInfoType2' }, { type: 'null' }],
    },
    output: {
      title: 'Output',
      examples: [
        "that's the way I look at it and I don't know what you would say. Sooner or later the child gets run over.\nThey seem to be too local, too provincial.",
      ],
      type: 'string',
      description: 'Generated output from video processing',
    },
  },
  required: ['output', 'usage'],
  type: 'object',
  $defs: {
    PromptTokensDetails: {
      'x-fal-order-properties': ['cached_tokens', 'cache_write_tokens'],
      title: 'PromptTokensDetails',
      properties: {
        cache_write_tokens: {
          title: 'Cache Write Tokens',
          default: 0,
          type: 'integer',
        },
        cached_tokens: { title: 'Cached Tokens', default: 0, type: 'integer' },
      },
      type: 'object',
    },
    UsageInfoType2: {
      'x-fal-order-properties': [
        'prompt_tokens',
        'completion_tokens',
        'total_tokens',
        'cost',
        'prompt_tokens_details',
      ],
      title: 'UsageInfo',
      properties: {
        completion_tokens: {
          title: 'Completion Tokens',
          anyOf: [{ type: 'integer' }, { type: 'null' }],
        },
        cost: { title: 'Cost', type: 'number' },
        total_tokens: { title: 'Total Tokens', default: 0, type: 'integer' },
        prompt_tokens: {
          title: 'Prompt Tokens',
          anyOf: [{ type: 'integer' }, { type: 'null' }],
        },
        prompt_tokens_details: {
          anyOf: [{ $ref: '#/$defs/PromptTokensDetails' }, { type: 'null' }],
        },
      },
      required: ['cost'],
      type: 'object',
    },
  },
} as const

export const Seed2MiniMessageSchema = {
  title: 'Seed2MiniMessage',
  required: ['role', 'content'],
  properties: {
    role: {
      description: 'The role of the message author.',
      enum: ['system', 'user', 'assistant'],
      title: 'Role',
      type: 'string',
    },
    content: {
      anyOf: [{ type: 'string' }, { items: { type: 'object' }, type: 'array' }],
      description:
        'The content of the message. Can be a string for text-only messages, or a list of content parts for multimodal messages (e.g. with images).',
      title: 'Content',
    },
  },
  type: 'object',
  'x-fal-order-properties': ['role', 'content'],
} as const

export const UsageInfoSchema = {
  type: 'object',
  required: ['input_tokens', 'output_tokens'],
  properties: {
    input_tokens: {
      description: 'Number of input tokens processed.',
      title: 'Input Tokens',
      type: 'integer',
    },
    output_tokens: {
      description: 'Number of output tokens generated.',
      title: 'Output Tokens',
      type: 'integer',
    },
  },
  title: 'UsageInfo',
  'x-fal-order-properties': ['input_tokens', 'output_tokens'],
} as const

export const UsageInfoType2Schema = {
  'x-fal-order-properties': [
    'prompt_tokens',
    'completion_tokens',
    'total_tokens',
    'cost',
    'prompt_tokens_details',
  ],
  title: 'UsageInfo',
  properties: {
    completion_tokens: {
      title: 'Completion Tokens',
      anyOf: [{ type: 'integer' }, { type: 'null' }],
    },
    cost: { title: 'Cost', type: 'number' },
    total_tokens: { title: 'Total Tokens', default: 0, type: 'integer' },
    prompt_tokens: {
      title: 'Prompt Tokens',
      anyOf: [{ type: 'integer' }, { type: 'null' }],
    },
    prompt_tokens_details: {
      anyOf: [{ $ref: '#/$defs/PromptTokensDetails' }, { type: 'null' }],
    },
  },
  required: ['cost'],
  type: 'object',
  $defs: {
    PromptTokensDetails: {
      'x-fal-order-properties': ['cached_tokens', 'cache_write_tokens'],
      title: 'PromptTokensDetails',
      properties: {
        cache_write_tokens: {
          title: 'Cache Write Tokens',
          default: 0,
          type: 'integer',
        },
        cached_tokens: { title: 'Cached Tokens', default: 0, type: 'integer' },
      },
      type: 'object',
    },
  },
} as const

export const VideoPromptGeneratorInputSchema = {
  required: ['input_concept'],
  title: 'InputModel',
  type: 'object',
  properties: {
    special_effects: {
      title: 'Special Effects',
      enum: [
        'None',
        'Practical effects',
        'CGI enhancement',
        'Analog glitches',
        'Light painting',
        'Projection mapping',
        'Nanosecond exposures',
        'Double exposure',
        'Smoke diffusion',
        'Lens flare artistry',
        'Particle systems',
        'Holographic overlay',
        'Chromatic aberration',
        'Digital distortion',
        'Wire removal',
        'Motion capture',
        'Miniature integration',
        'Weather simulation',
        'Color grading',
        'Mixed media composite',
        'Neural style transfer',
      ],
      type: 'string',
      default: 'None',
      description: 'Special effects approach',
    },
    pacing: {
      title: 'Pacing',
      enum: [
        'None',
        'Slow burn',
        'Rhythmic pulse',
        'Frantic energy',
        'Ebb and flow',
        'Hypnotic drift',
        'Time-lapse rush',
        'Stop-motion staccato',
        'Gradual build',
        'Quick cut rhythm',
        'Long take meditation',
        'Jump cut energy',
        'Match cut flow',
        'Cross-dissolve dreamscape',
        'Parallel action',
        'Slow motion impact',
        'Ramping dynamics',
        'Montage tempo',
        'Continuous flow',
        'Episodic breaks',
      ],
      type: 'string',
      default: 'None',
      description: 'Pacing rhythm',
    },
    camera_style: {
      title: 'Camera Style',
      enum: [
        'None',
        'Steadicam flow',
        'Drone aerials',
        'Handheld urgency',
        'Crane elegance',
        'Dolly precision',
        'VR 360',
        'Multi-angle rig',
        'Static tripod',
        'Gimbal smoothness',
        'Slider motion',
        'Jib sweep',
        'POV immersion',
        'Time-slice array',
        'Macro extreme',
        'Tilt-shift miniature',
        'Snorricam character',
        'Whip pan dynamics',
        'Dutch angle tension',
        'Underwater housing',
        'Periscope lens',
      ],
      type: 'string',
      default: 'None',
      description: 'Camera movement style',
    },
    image_url: {
      title: 'Image Url',
      type: 'string',
      description:
        'URL of an image to analyze and incorporate into the video prompt (optional)',
      'x-fal-file-input': true,
    },
    input_concept: {
      description: 'Core concept or thematic input for the video prompt',
      title: 'Input Concept',
      type: 'string',
      examples: ['A futuristic city at dusk'],
    },
    model: {
      title: 'Model',
      enum: [
        'anthropic/claude-3.5-sonnet',
        'anthropic/claude-3-5-haiku',
        'anthropic/claude-3-haiku',
        'google/gemini-2.5-flash-lite',
        'google/gemini-2.0-flash-001',
        'meta-llama/llama-3.2-1b-instruct',
        'meta-llama/llama-3.2-3b-instruct',
        'meta-llama/llama-3.1-8b-instruct',
        'meta-llama/llama-3.1-70b-instruct',
        'openai/gpt-4o-mini',
        'openai/gpt-4o',
        'deepseek/deepseek-r1',
      ],
      type: 'string',
      default: 'google/gemini-2.0-flash-001',
      description: 'Model to use',
    },
    custom_elements: {
      title: 'Custom Elements',
      type: 'string',
      default: '',
      description: 'Custom technical elements (optional)',
    },
    prompt_length: {
      title: 'Prompt Length',
      enum: ['Short', 'Medium', 'Long'],
      type: 'string',
      default: 'Medium',
      description: 'Length of the prompt',
    },
    style: {
      title: 'Style',
      enum: [
        'Minimalist',
        'Simple',
        'Detailed',
        'Descriptive',
        'Dynamic',
        'Cinematic',
        'Documentary',
        'Animation',
        'Action',
        'Experimental',
      ],
      type: 'string',
      default: 'Simple',
      description: 'Style of the video prompt',
    },
    camera_direction: {
      title: 'Camera Direction',
      enum: [
        'None',
        'Zoom in',
        'Zoom out',
        'Pan left',
        'Pan right',
        'Tilt up',
        'Tilt down',
        'Orbital rotation',
        'Push in',
        'Pull out',
        'Track forward',
        'Track backward',
        'Spiral in',
        'Spiral out',
        'Arc movement',
        'Diagonal traverse',
        'Vertical rise',
        'Vertical descent',
      ],
      type: 'string',
      default: 'None',
      description: 'Camera direction',
    },
  },
  'x-fal-order-properties': [
    'input_concept',
    'style',
    'camera_style',
    'camera_direction',
    'pacing',
    'special_effects',
    'custom_elements',
    'image_url',
    'model',
    'prompt_length',
  ],
} as const

export const VideoPromptGeneratorOutputSchema = {
  required: ['prompt'],
  title: 'OutputModel',
  type: 'object',
  properties: {
    prompt: {
      description: 'Generated video prompt',
      title: 'Prompt',
      type: 'string',
      examples: [
        'A futuristic city glows softly at dusk, captured with smooth gimbal movements and a slow burn pacing, enhanced by subtle holographic overlays.',
      ],
    },
  },
  'x-fal-order-properties': ['prompt'],
} as const
