// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod'

/**
 * Error data for BadGatewayResponse
 */
export const zBadGatewayResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Bad Gateway - Provider/upstream API failure
 */
export const zBadGatewayResponse = z.object({
  error: zBadGatewayResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

/**
 * Error data for BadRequestResponse
 */
export const zBadRequestResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Bad Request - Invalid request parameters or malformed input
 */
export const zBadRequestResponse = z.object({
  error: zBadRequestResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

/**
 * Price per million prompt tokens
 */
export const zBigNumberUnion = z.string()

/**
 * Error data for EdgeNetworkTimeoutResponse
 */
export const zEdgeNetworkTimeoutResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Infrastructure Timeout - Provider request timed out at edge network
 */
export const zEdgeNetworkTimeoutResponse = z.object({
  error: zEdgeNetworkTimeoutResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

/**
 * Embeddings response containing embedding vectors
 */
export const zEmbeddingsResponse = z.object({
  data: z.array(
    z.object({
      embedding: z.union([z.array(z.number()), z.string()]),
      index: z.int().optional(),
      object: z.enum(['embedding']),
    }),
  ),
  id: z.string().optional(),
  model: z.string(),
  object: z.enum(['list']),
  usage: z
    .object({
      cost: z.number().optional(),
      prompt_tokens: z.int(),
      prompt_tokens_details: z
        .object({
          audio_tokens: z.int().optional(),
          file_tokens: z.int().optional(),
          image_tokens: z.int().optional(),
          text_tokens: z.int().optional(),
          video_tokens: z.int().optional(),
        })
        .optional(),
      total_tokens: z.int(),
    })
    .optional(),
})

/**
 * Error data for InternalServerResponse
 */
export const zInternalServerResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Internal Server Error - Unexpected server error
 */
export const zInternalServerResponse = z.object({
  error: zInternalServerResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

export const zMultimodalMedia = z.object({
  data: z.string(),
  format: z.string().optional(),
})

export const zContentPartInputAudio = z.object({
  input_audio: zMultimodalMedia,
  type: z.enum(['input_audio']),
})

export const zContentPartInputFile = z.object({
  input_file: zMultimodalMedia,
  type: z.enum(['input_file']),
})

export const zContentPartInputVideo = z.object({
  input_video: zMultimodalMedia,
  type: z.enum(['input_video']),
})

/**
 * Error data for NotFoundResponse
 */
export const zNotFoundResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Not Found - Resource does not exist
 */
export const zNotFoundResponse = z.object({
  error: zNotFoundResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

/**
 * Error data for PaymentRequiredResponse
 */
export const zPaymentRequiredResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Payment Required - Insufficient credits or quota to complete request
 */
export const zPaymentRequiredResponse = z.object({
  error: zPaymentRequiredResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

/**
 * Percentile-based latency cutoffs. All specified cutoffs must be met for an endpoint to be preferred.
 */
export const zPercentileLatencyCutoffs = z.object({
  p50: z.number().nullish(),
  p75: z.number().nullish(),
  p90: z.number().nullish(),
  p99: z.number().nullish(),
})

/**
 * Percentile-based throughput cutoffs. All specified cutoffs must be met for an endpoint to be preferred.
 */
export const zPercentileThroughputCutoffs = z.object({
  p50: z.number().nullish(),
  p75: z.number().nullish(),
  p90: z.number().nullish(),
  p99: z.number().nullish(),
})

/**
 * Preferred maximum latency (in seconds). Can be a number (applies to p50) or an object with percentile-specific cutoffs. Endpoints above the threshold(s) may still be used, but are deprioritized in routing. When using fallback models, this may cause a fallback model to be used instead of the primary model if it meets the threshold.
 */
export const zPreferredMaxLatency = z.union([
  z.number(),
  zPercentileLatencyCutoffs,
  z.unknown(),
])

/**
 * Preferred minimum throughput (in tokens per second). Can be a number (applies to p50) or an object with percentile-specific cutoffs. Endpoints below the threshold(s) may still be used, but are deprioritized in routing. When using fallback models, this may cause a fallback model to be used instead of the primary model if it meets the threshold.
 */
export const zPreferredMinThroughput = z.union([
  z.number(),
  zPercentileThroughputCutoffs,
  z.unknown(),
])

export const zProviderName = z.enum([
  'AkashML',
  'AI21',
  'AionLabs',
  'Alibaba',
  'Ambient',
  'Baidu',
  'Amazon Bedrock',
  'Amazon Nova',
  'Anthropic',
  'Arcee AI',
  'AtlasCloud',
  'Avian',
  'Azure',
  'BaseTen',
  'BytePlus',
  'Black Forest Labs',
  'Cerebras',
  'Chutes',
  'Cirrascale',
  'Clarifai',
  'Cloudflare',
  'Cohere',
  'Crucible',
  'Crusoe',
  'Darkbloom',
  'Decart',
  'DeepInfra',
  'DeepSeek',
  'DekaLLM',
  'DigitalOcean',
  'Featherless',
  'Fireworks',
  'Friendli',
  'GMICloud',
  'Google',
  'Google AI Studio',
  'Groq',
  'Inception',
  'Inceptron',
  'InferenceNet',
  'Ionstream',
  'Infermatic',
  'Io Net',
  'Inflection',
  'Liquid',
  'Mara',
  'Mancer 2',
  'Minimax',
  'ModelRun',
  'Mistral',
  'Modular',
  'Moonshot AI',
  'Morph',
  'NCompass',
  'Nebius',
  'Nex AGI',
  'NextBit',
  'Novita',
  'Nvidia',
  'OpenAI',
  'OpenInference',
  'Parasail',
  'Poolside',
  'Perceptron',
  'Perplexity',
  'Phala',
  'Recraft',
  'Reka',
  'Relace',
  'SambaNova',
  'Seed',
  'SiliconFlow',
  'Sourceful',
  'StepFun',
  'Stealth',
  'StreamLake',
  'Switchpoint',
  'Together',
  'Upstage',
  'Venice',
  'Wafer',
  'WandB',
  'Xiaomi',
  'xAI',
  'Z.AI',
  'FakeProvider',
])

/**
 * Error data for ProviderOverloadedResponse
 */
export const zProviderOverloadedResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Provider Overloaded - Provider is temporarily overloaded
 */
export const zProviderOverloadedResponse = z.object({
  error: zProviderOverloadedResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

/**
 * The provider sorting strategy (price, throughput, latency)
 */
export const zProviderSort = z.enum([
  'price',
  'throughput',
  'latency',
  'exacto',
])

/**
 * The provider sorting strategy (price, throughput, latency)
 */
export const zProviderSortConfig = z.object({
  by: z.enum(['price', 'throughput', 'latency', 'exacto']).nullish(),
  partition: z.enum(['model', 'none']).nullish(),
})

export const zQuantization = z.enum([
  'int4',
  'int8',
  'fp4',
  'fp6',
  'fp8',
  'fp16',
  'bf16',
  'fp32',
  'unknown',
])

/**
 * When multiple model providers are available, optionally indicate your routing preference.
 */
export const zProviderPreferences = z
  .object({
    allow_fallbacks: z.boolean().nullish(),
    data_collection: z.enum(['deny', 'allow']).nullish(),
    enforce_distillable_text: z.boolean().nullish(),
    ignore: z.array(z.union([zProviderName, z.string()])).nullish(),
    max_price: z
      .object({
        audio: zBigNumberUnion.and(z.unknown()).optional(),
        completion: zBigNumberUnion.and(z.unknown()).optional(),
        image: zBigNumberUnion.and(z.unknown()).optional(),
        prompt: zBigNumberUnion.optional(),
        request: zBigNumberUnion.and(z.unknown()).optional(),
      })
      .optional(),
    only: z.array(z.union([zProviderName, z.string()])).nullish(),
    order: z.array(z.union([zProviderName, z.string()])).nullish(),
    preferred_max_latency: zPreferredMaxLatency.optional(),
    preferred_min_throughput: zPreferredMinThroughput.optional(),
    quantizations: z.array(zQuantization).nullish(),
    require_parameters: z.boolean().nullish(),
    sort: z.union([zProviderSort, zProviderSortConfig, z.unknown()]).optional(),
    zdr: z.boolean().nullish(),
  })
  .nullable()

/**
 * Embeddings request input
 */
export const zEmbeddingsRequest = z.object({
  dimensions: z.int().gte(1).optional(),
  encoding_format: z.enum(['float', 'base64']).optional(),
  input: z.union([
    z.string(),
    z.array(z.string()),
    z.array(z.number()),
    z.array(z.array(z.number())),
    z.array(
      z.object({
        content: z.array(
          z.union([
            z.object({
              text: z.string(),
              type: z.enum(['text']),
            }),
            z.object({
              image_url: z.object({
                url: z.string(),
              }),
              type: z.enum(['image_url']),
            }),
            zContentPartInputAudio,
            zContentPartInputVideo,
            zContentPartInputFile,
          ]),
        ),
      }),
    ),
  ]),
  input_type: z.string().optional(),
  model: z.string(),
  provider: zProviderPreferences.and(z.unknown()).optional(),
  user: z.string().optional(),
})

/**
 * Error data for ServiceUnavailableResponse
 */
export const zServiceUnavailableResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Service Unavailable - Service temporarily unavailable
 */
export const zServiceUnavailableResponse = z.object({
  error: zServiceUnavailableResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

/**
 * Error data for TooManyRequestsResponse
 */
export const zTooManyRequestsResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Too Many Requests - Rate limit exceeded
 */
export const zTooManyRequestsResponse = z.object({
  error: zTooManyRequestsResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

/**
 * Error data for UnauthorizedResponse
 */
export const zUnauthorizedResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Unauthorized - Authentication required or invalid credentials
 */
export const zUnauthorizedResponse = z.object({
  error: zUnauthorizedResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

export const zCreateEmbeddingsBody = zEmbeddingsRequest

/**
 * Embedding response
 */
export const zCreateEmbeddingsResponse = zEmbeddingsResponse
