// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod'

/**
 * Image input for generation and editing requests.
 * Accepts a public URL, a base64-encoded data URL, or a file_id from the xAI Files API.
 */
export const zImageUrl = z.object({
  file_id: z.unknown().optional(),
  url: z.string().optional(),
})

/**
 * Configuration for creating a public URL alongside file storage.
 */
export const zPublicUrlOptions = z.object({
  expires_after: z.unknown().optional(),
})

/**
 * Accepts either `true` (create public URL with defaults) or a configuration
 * object with explicit options.
 *
 * **Variant order matters for `#[serde(untagged)]`:** `Flag` must come before
 * `Options` so that JSON `true`/`false` match `Flag` rather than falling
 * through to the object variant.
 *
 * **Serialization note:** Proto→REST readback always constructs
 * `Options(...)`, never `Flag`, so responses always emit the object form.
 * `Flag` only appears on the deserialization (request) path.
 */
export const zPublicUrlInput = z.union([z.boolean(), zPublicUrlOptions])

/**
 * Response for starting a deferred operation.
 */
export const zStartDeferredResponse = z.object({
  request_id: z.string(),
})

/**
 * Configuration for storing generation output in the Files API.
 * When provided in a generation request, the output is stored as a
 * permanent file and a `file_output` reference is included in the response.
 */
export const zStorageOptions = z.object({
  expires_after: z.unknown().optional(),
  filename: z.string(),
  public_url: z.union([z.unknown(), zPublicUrlInput]).optional(),
})

/**
 * Aspect ratio for video generation.
 */
export const zVideoAspectRatio = z.enum([
  '1:1',
  '16:9',
  '9:16',
  '4:3',
  '3:4',
  '3:2',
  '2:3',
])

/**
 * Output destination for generated video.
 */
export const zVideoOutput = z.object({
  upload_url: z.string(),
})

/**
 * Resolution for video generation.
 */
export const zVideoResolution = z.enum(['480p', '720p', '1080p'])

/**
 * Request to generate video for `/v1/videos/generations` endpoint
 */
export const zGenerateVideoRequest = z.object({
  aspect_ratio: z.union([z.unknown(), zVideoAspectRatio]).optional(),
  duration: z.unknown().optional().default(8),
  image: z.union([z.unknown(), zImageUrl]).optional(),
  model: z.unknown().optional(),
  output: z.union([z.unknown(), zVideoOutput]).optional(),
  prompt: z.string().optional(),
  reference_images: z.array(zImageUrl).optional(),
  resolution: z.union([z.unknown(), zVideoResolution]).optional(),
  storage_options: z.union([z.unknown(), zStorageOptions]).optional(),
  user: z.unknown().optional(),
})

/**
 * Video input for editing and extension requests.
 * Accepts a public URL, a base64-encoded data URL, or a file_id from the xAI Files API.
 */
export const zVideoUrl = z.object({
  file_id: z.unknown().optional(),
  url: z.string().optional(),
})

/**
 * Request for editing video for `/v1/videos/edits` endpoint
 */
export const zEditVideoRequest = z.object({
  model: z.unknown().optional(),
  output: z.union([z.unknown(), zVideoOutput]).optional(),
  prompt: z.string(),
  storage_options: z.union([z.unknown(), zStorageOptions]).optional(),
  user: z.unknown().optional(),
  video: zVideoUrl,
})

/**
 * Request for extending a video for `/v1/videos/extensions` endpoint
 */
export const zExtendVideoRequest = z.object({
  duration: z.unknown().optional(),
  model: z.unknown().optional(),
  output: z.union([z.unknown(), zVideoOutput]).optional(),
  prompt: z.string(),
  storage_options: z.union([z.unknown(), zStorageOptions]).optional(),
  video: zVideoUrl,
})

export const zHandleEditVideoRequestBody = zEditVideoRequest

/**
 * Video editing started successfully
 */
export const zHandleEditVideoRequestResponse = zStartDeferredResponse

export const zHandleExtendVideoRequestBody = zExtendVideoRequest

/**
 * Video extension started successfully
 */
export const zHandleExtendVideoRequestResponse = zStartDeferredResponse

export const zHandleGenerateVideoRequestBody = zGenerateVideoRequest

/**
 * Video generation started successfully
 */
export const zHandleGenerateVideoRequestResponse = zStartDeferredResponse
