// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod'

export const zAnnotation = z.object({
  end_index: z.unknown().optional(),
  start_index: z.unknown().optional(),
  title: z.unknown().optional(),
  type: z.string(),
  url: z.string(),
})

export const zChoiceMessage = z.object({
  content: z.unknown().optional(),
  reasoning_content: z.unknown().optional(),
  refusal: z.unknown().optional(),
  role: z.string(),
  tool_calls: z.unknown().optional(),
})

export const zCodeInterpreterOutput = z.union([
  z.object({
    logs: z.string(),
    type: z.enum(['logs']),
  }),
  z.object({
    type: z.enum(['image']),
    url: z.string(),
  }),
])

/**
 * The output of a code interpreter tool call.
 */
export const zCodeInterpreterCall = z.object({
  code: z.string().optional(),
  id: z.string().optional(),
  outputs: z.array(zCodeInterpreterOutput),
  status: z.string().optional(),
  type: z.string(),
})

/**
 * A compaction item from a previous `/v1/responses/compact` call.
 *
 * Accepted as input in `/v1/responses` calls. Clients must treat
 * `encrypted_content` as opaque — do not parse or depend on its
 * internal structure.
 */
export const zCompactionOutputItem = z.object({
  encrypted_content: z.string(),
  id: z.unknown().optional(),
  type: z.string(),
})

/**
 * (Legacy) Anthropic compatible complete response on `/v1/complete` endpoint.
 */
export const zCompleteResponse = z.object({
  completion: z.string(),
  id: z.string(),
  model: z.string(),
  stop_reason: z.unknown().optional(),
  type: z.string(),
})

/**
 * Details of completion usage.
 */
export const zCompletionUsageDetail = z.object({
  accepted_prediction_tokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  audio_tokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  reasoning_tokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  rejected_prediction_tokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
})

/**
 * Token counts for the latest context window seen by the model.
 *
 * In the non-agentic path these mirror `input_tokens` / `output_tokens`.
 * In the agentic path (multi-agents) these are reset on every step and
 * reflect the most recent step's prompt and output sizes — useful for
 * understanding how the live context window evolves across tool calls.
 * Informational only; not used for billing.
 */
export const zContextDetails = z.object({
  input_tokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  output_tokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
})

/**
 * The output of a custom tool call.
 */
export const zCustomToolCall = z.object({
  call_id: z.string(),
  id: z.string(),
  input: z.string().optional(),
  name: z.string(),
  status: z.string().optional(),
  type: z.string(),
})

export const zFileRef = z.object({
  file_id: z.unknown().optional(),
  url: z.unknown().optional(),
})

export const zFileSearchResult = z.object({
  file_id: z.string(),
  filename: z.string(),
  score: z.number().optional(),
  text: z.string(),
})

/**
 * The output of a web search tool call.
 */
export const zFileSearchCall = z.object({
  id: z.string().optional(),
  queries: z.array(z.string()),
  results: z.array(zFileSearchResult),
  status: z.string().optional(),
  type: z.string(),
})

export const zFunction = z.object({
  arguments: z.string(),
  name: z.string(),
})

/**
 * Function name.
 */
export const zFunctionChoice = z.object({
  name: z.string(),
})

/**
 * Definition of the tool call made available to the model.
 */
export const zFunctionDefinition = z.object({
  description: z.unknown().optional(),
  name: z.string(),
  parameters: z.unknown(),
  strict: z.unknown().optional(),
})

/**
 * A tool call to run a function.
 */
export const zFunctionToolCall = z.object({
  arguments: z.string(),
  call_id: z.string(),
  id: z.string().optional(),
  name: z.string(),
  status: z.string().optional(),
  type: z.string(),
})

/**
 * Image input for generation and editing requests.
 * Accepts a public URL, a base64-encoded data URL, or a file_id from the xAI Files API.
 */
export const zImageUrl = z.object({
  file_id: z.unknown().optional(),
  url: z.string().optional(),
})

export const zContentPart = z.object({
  file: z.union([z.unknown(), zFileRef]).optional(),
  image_url: z.union([z.unknown(), zImageUrl]).optional(),
  text: z.unknown().optional(),
  type: z.string(),
})

/**
 * Content of each chat message.
 */
export const zContent = z.union([z.string(), z.array(zContentPart)])

/**
 * Details about why a response is incomplete.
 */
export const zIncompleteDetails = z.union([
  z.object({
    reason: z.enum(['max_output_tokens']),
  }),
  z.object({
    reason: z.enum(['max_prompt_tokens']),
  }),
  z.object({
    reason: z.enum(['max_time_limit']),
  }),
])

export const zInputTokensDetails = z.object({
  cached_tokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
})

/**
 * A skill available in the local shell environment.
 */
export const zLocalShellSkill = z.object({
  description: z.string(),
  name: z.string(),
  path: z.string(),
})

export const zLogProbs = z.object({
  content: z.unknown().optional(),
})

export const zChoice = z.object({
  finish_reason: z.unknown().optional(),
  index: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  logprobs: z.union([z.unknown(), zLogProbs]).optional(),
  message: zChoiceMessage,
})

/**
 * The output of a MCP tool call.
 */
export const zMcpCall = z.object({
  arguments: z.string(),
  error: z.string().optional(),
  id: z.string().optional(),
  name: z.string(),
  output: z.string(),
  server_label: z.string(),
  status: z.string().optional(),
  type: z.string(),
})

/**
 * Chat message objects.
 */
export const zMessage = z.union([
  z.object({
    content: zContent,
    name: z.unknown().optional(),
    role: z.enum(['system']),
  }),
  z.object({
    content: zContent,
    name: z.unknown().optional(),
    role: z.enum(['user']),
  }),
  z.object({
    content: z.union([z.unknown(), zContent]).optional(),
    name: z.unknown().optional(),
    reasoning_content: z.unknown().optional(),
    role: z.enum(['assistant']),
    tool_calls: z.unknown().optional(),
  }),
  z.object({
    content: zContent,
    role: z.enum(['tool']),
    tool_call_id: z.unknown().optional(),
  }),
  z.object({
    content: zContent,
    name: z.unknown().optional(),
    role: z.enum(['function']),
  }),
])

export const zMessageImageContent = z.union([
  z.object({
    data: z.string(),
    media_type: z.string(),
    type: z.enum(['base64']),
  }),
  z.object({
    type: z.enum(['url']),
    url: z.string(),
  }),
])

export const zMessageMetadata = z.object({
  user_id: z.unknown().optional(),
})

/**
 * (Legacy) Anthropic compatible complete request on `/v1/complete` endpoint.
 */
export const zCompleteRequest = z.object({
  max_tokens_to_sample: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  metadata: z.union([z.unknown(), zMessageMetadata]).optional(),
  model: z.string().optional(),
  prompt: z.string().optional(),
  stop_sequences: z.unknown().optional(),
  stream: z.unknown().optional(),
  temperature: z.unknown().optional().default(1),
  top_k: z.unknown().optional(),
  top_p: z.unknown().optional().default(1),
})

export const zMessageResponseContent = z.union([
  z.object({
    text: z.string(),
    type: z.enum(['text']),
  }),
  z.object({
    signature: z.string(),
    thinking: z.string(),
    type: z.enum(['thinking']),
  }),
  z.object({
    data: z.string(),
    type: z.enum(['redacted_thinking']),
  }),
  z.object({
    id: z.string(),
    input: z.unknown(),
    name: z.string(),
    type: z.enum(['tool_use']),
  }),
])

/**
 * Tool choice option.
 */
export const zMessageToolChoice = z.union([
  z.object({
    type: z.enum(['auto']),
  }),
  z.object({
    type: z.enum(['any']),
  }),
  z.object({
    name: z.string(),
    type: z.enum(['tool']),
  }),
])

export const zMessageToolInputSchema = z.object({
  properties: z.unknown(),
  required: z.unknown().optional(),
  type: z.string(),
})

export const zMessageTools = z.object({
  cache_control: z.unknown().optional(),
  description: z.string(),
  input_schema: zMessageToolInputSchema,
  name: z.string(),
})

export const zMessageUsage = z.object({
  cache_creation_input_tokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  cache_read_input_tokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  input_tokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  output_tokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
})

/**
 * Response message for `/v1/messages`
 */
export const zMessageResponse = z.object({
  content: z.array(zMessageResponseContent),
  id: z.string(),
  model: z.string(),
  role: z.string(),
  stop_reason: z.unknown().optional(),
  stop_sequence: z.unknown().optional(),
  type: z.string(),
  usage: zMessageUsage,
})

export const zModelInputContentItem = z.union([
  z.object({
    text: z.string(),
    type: z.enum(['input_text']),
  }),
  z.object({
    text: z.string(),
    type: z.enum(['output_text']),
  }),
  z.object({
    file_id: z.unknown().optional(),
    image_url: z.string(),
    type: z.enum(['input_image']),
  }),
  z.object({
    file_data: z.unknown().optional(),
    file_id: z.unknown().optional(),
    file_url: z.unknown().optional(),
    filename: z.unknown().optional(),
    mime_type: z.unknown().optional(),
    type: z.enum(['input_file']),
  }),
])

export const zModelInputContent = z.union([
  z.string(),
  z.array(zModelInputContentItem),
])

/**
 * The output of a function tool call.
 */
export const zFunctionToolCallOutput = z.object({
  call_id: z.string(),
  output: zModelInputContent,
  type: z.string(),
})

/**
 * Response format parameter for structured outputs.
 */
export const zModelResponseFormat = z.union([
  z.object({
    type: z.enum(['text']),
  }),
  z.object({
    type: z.enum(['json_object']),
  }),
  z.object({
    description: z.unknown().optional(),
    name: z.unknown().optional(),
    schema: z.unknown(),
    strict: z.unknown().optional(),
    type: z.enum(['json_schema']),
  }),
])

export const zModelResponseConfiguration = z.object({
  format: z.union([z.unknown(), zModelResponseFormat]).optional(),
})

/**
 * Parameter to control how model chooses the tools.
 */
export const zModelToolChoice = z.union([
  z.string(),
  z.object({
    name: z.string(),
    type: z.string(),
  }),
])

/**
 * A file generated during the model's response (e.g., by the code execution tool).
 */
export const zOutputFile = z.object({
  file_id: z.string(),
  name: z.string(),
})

export const zOutputTokensDetails = z.object({
  reasoning_tokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
})

/**
 * Details of prompt usage.
 */
export const zPromptUsageDetail = z.object({
  audio_tokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  cached_tokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  image_tokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  text_tokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
})

export const zReasoningConfiguration = z.object({
  effort: z.unknown().optional().default('low'),
  generate_summary: z.unknown().optional(),
  summary: z.unknown().optional(),
})

export const zReasoningText = z.object({
  text: z.string(),
  type: z.string(),
})

/**
 * Response format parameter for structured outputs.
 */
export const zResponseFormat = z.union([
  z.object({
    type: z.enum(['text']),
  }),
  z.object({
    type: z.enum(['json_object']),
  }),
  z.object({
    json_schema: z.unknown(),
    type: z.enum(['json_schema']),
  }),
])

export const zSampleChoice = z.object({
  finish_reason: z.string(),
  index: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  text: z.string(),
})

export const zSampleContent = z.union([z.string(), z.array(z.string())])

/**
 * Parameters to control realtime data.
 */
export const zSearchParameters = z.object({
  from_date: z.unknown().optional(),
  max_search_results: z.unknown().optional().default(15),
  mode: z.unknown().optional().default('auto'),
  return_citations: z.unknown().optional().default(true),
  sources: z.unknown().optional(),
  to_date: z.unknown().optional(),
})

export const zSearchSource = z.union([
  z.object({
    excluded_x_handles: z.unknown().optional(),
    included_x_handles: z.unknown().optional(),
    post_favorite_count: z.unknown().optional(),
    post_view_count: z.unknown().optional(),
    type: z.enum(['x']),
    x_handles: z.unknown().optional(),
  }),
  z.object({
    allowed_websites: z.unknown().optional(),
    country: z.unknown().optional(),
    excluded_websites: z.unknown().optional(),
    safe_search: z.unknown().optional(),
    type: z.enum(['web']),
  }),
  z.object({
    country: z.unknown().optional(),
    excluded_websites: z.unknown().optional(),
    safe_search: z.unknown().optional(),
    type: z.enum(['news']),
  }),
  z.object({
    links: z.tuple([z.string()]),
    type: z.enum(['rss']),
  }),
])

export const zServerSideToolUsageDetails = z.object({
  code_interpreter_calls: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  document_search_calls: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  file_search_calls: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  mcp_calls: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  web_search_calls: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  x_search_calls: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
})

export const zModelUsage = z.object({
  context_details: z.union([z.unknown(), zContextDetails]).optional(),
  cost_in_nano_usd: z.unknown().optional(),
  cost_in_usd_ticks: z.unknown().optional(),
  input_tokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  input_tokens_details: zInputTokensDetails,
  num_server_side_tools_used: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  num_sources_used: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  output_tokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  output_tokens_details: zOutputTokensDetails,
  server_side_tool_usage_details: z
    .union([z.unknown(), zServerSideToolUsageDetails])
    .optional(),
  total_tokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
})

/**
 * Processing tier for a request. Determines scheduling priority and billing.
 */
export const zServiceTier = z.enum(['default', 'priority'])

/**
 * The shell commands and limits that describe how to run the tool call.
 */
export const zShellCallAction = z.object({
  commands: z.array(z.string()),
  max_output_length: z.unknown().optional(),
  timeout_ms: z.unknown().optional(),
  type: z.unknown().optional(),
})

/**
 * The outcome of a shell command execution.
 */
export const zShellCallOutcome = z.union([
  z.object({
    exit_code: z
      .int()
      .min(-2147483648, {
        error: 'Invalid value: Expected int32 to be >= -2147483648',
      })
      .max(2147483647, {
        error: 'Invalid value: Expected int32 to be <= 2147483647',
      }),
    type: z.enum(['exit']),
  }),
  z.object({
    type: z.enum(['timeout']),
  }),
])

/**
 * The content of a shell tool call output that was emitted.
 */
export const zShellCallOutputResult = z.object({
  outcome: zShellCallOutcome,
  stderr: z.string().optional(),
  stdout: z.string().optional(),
})

/**
 * The output of a shell tool call, sent by the client after local execution.
 */
export const zShellCallOutput = z.object({
  call_id: z.string(),
  max_output_length: z.unknown().optional(),
  output: z.array(zShellCallOutputResult),
  type: z.string(),
})

/**
 * The environment configuration for a shell tool.
 */
export const zShellEnvironment = z.object({
  skills: z.array(zLocalShellSkill).optional(),
  type: z.string(),
})

/**
 * A shell command call emitted by the model for local execution.
 */
export const zShellCall = z.object({
  action: zShellCallAction,
  call_id: z.string(),
  environment: z.union([z.unknown(), zShellEnvironment]).optional(),
  id: z.string().optional(),
  status: z.string().optional(),
  type: z.string(),
})

/**
 * Options available when using streaming response.
 */
export const zStreamOptions = z.object({
  include_usage: z.boolean(),
})

/**
 * (Legacy) Request for `/v1/completions` endpoint
 */
export const zSampleRequest = z.object({
  best_of: z.unknown().optional(),
  echo: z.unknown().optional(),
  frequency_penalty: z.unknown().optional(),
  logit_bias: z.unknown().optional(),
  logprobs: z.unknown().optional(),
  max_tokens: z.unknown().optional(),
  model: z.string().optional(),
  n: z.unknown().optional(),
  presence_penalty: z.unknown().optional(),
  prompt: zSampleContent.optional(),
  seed: z.unknown().optional(),
  stop: z.unknown().optional(),
  stream: z.unknown().optional(),
  stream_options: z.union([z.unknown(), zStreamOptions]).optional(),
  suffix: z.unknown().optional(),
  temperature: z.unknown().optional().default(1),
  top_p: z.unknown().optional(),
  user: z.unknown().optional(),
})

export const zSummaryText = z.object({
  text: z.string(),
  type: z.string(),
})

/**
 * The reasoning done by the model.
 */
export const zReasoning = z.object({
  content: z.array(zReasoningText).optional(),
  encrypted_content: z.unknown().optional(),
  id: z.string().optional(),
  status: z.string().optional(),
  summary: z.array(zSummaryText),
  type: z.string(),
})

export const zSystemMessagePart = z.object({
  cache_control: z.unknown().optional(),
  text: z.string(),
  type: z.string(),
})

export const zSystemMessageContent = z.union([
  z.string(),
  z.array(zSystemMessagePart),
])

export const zTokenizeRequest = z.object({
  model: z.string().optional(),
  text: z.string().optional(),
  user: z.unknown().optional(),
})

export const zTokenizeResponseToken = z.object({
  string_token: z.string(),
  token_bytes: z.array(
    z.int().gte(0).max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  ),
  token_id: z.int().gte(0).max(2147483647, {
    error: 'Invalid value: Expected int32 to be <= 2147483647',
  }),
})

export const zTokenizeResponse = z.object({
  token_ids: z.array(zTokenizeResponseToken),
})

/**
 * Definition of one tool that the model can call.
 */
export const zTool = z.union([
  z.object({
    function: zFunctionDefinition,
    type: z.enum(['function']),
  }),
  z.object({
    sources: z.array(zSearchSource),
    type: z.enum(['live_search']),
  }),
])

export const zToolCall = z.object({
  function: zFunction,
  id: z.string(),
  index: z.unknown().optional(),
  type: z.unknown().optional(),
})

/**
 * Parameter to control how model chooses the tools.
 */
export const zToolChoice = z.union([
  z.string(),
  z.object({
    function: z.union([z.unknown(), zFunctionChoice]).optional(),
    type: z.string(),
  }),
])

/**
 * A single content block within a tool_result's array content.
 */
export const zToolResultContentBlock = z.union([
  z.object({
    text: z.string(),
    type: z.enum(['text']),
  }),
  z.object({
    source: zMessageImageContent,
    type: z.enum(['image']),
  }),
])

/**
 * Content of a tool_result block. The Anthropic SDK may send this as either a plain
 * string or an array of typed content blocks (e.g. `[{"type": "text", "text": "..."}]`).
 */
export const zToolResultContent = z.union([
  z.string(),
  z.array(zToolResultContentBlock),
])

export const zMessageContentPart = z.union([
  z.object({
    cache_control: z.unknown().optional(),
    text: z.string(),
    type: z.enum(['text']),
  }),
  z.object({
    cache_control: z.unknown().optional(),
    source: zMessageImageContent,
    type: z.enum(['image']),
  }),
  z.object({
    cache_control: z.unknown().optional(),
    id: z.string(),
    input: z.unknown(),
    name: z.string(),
    type: z.enum(['tool_use']),
  }),
  z.object({
    cache_control: z.unknown().optional(),
    content: zToolResultContent,
    is_error: z.unknown().optional(),
    tool_use_id: z.string(),
    type: z.enum(['tool_result']),
  }),
  z.object({
    data: z.string(),
    type: z.enum(['redacted_thinking']),
  }),
  z.object({
    signature: z.unknown().optional(),
    thinking: z.string(),
    type: z.enum(['thinking']),
  }),
])

export const zMessageContent = z.union([
  z.string(),
  z.array(zMessageContentPart),
])

/**
 * Anthropic compatible message body
 */
export const zMessageBody = z.object({
  content: zMessageContent,
  role: z.string(),
})

/**
 * Request message for `/v1/messages`
 */
export const zMessageRequest = z.object({
  max_tokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  messages: z.array(zMessageBody).optional(),
  metadata: z.union([z.unknown(), zMessageMetadata]).optional(),
  model: z.string().optional(),
  stop_sequences: z.unknown().optional(),
  stream: z.unknown().optional(),
  system: z.union([z.unknown(), zSystemMessageContent]).optional(),
  temperature: z.unknown().optional().default(1),
  tool_choice: z.union([z.unknown(), zMessageToolChoice]).optional(),
  tools: z.unknown().optional(),
  top_k: z.unknown().optional(),
  top_p: z.unknown().optional().default(1),
})

export const zTopLogProb = z.object({
  bytes: z.unknown().optional(),
  logprob: z.number(),
  token: z.string(),
})

export const zTokenLogProb = z.object({
  bytes: z.unknown().optional(),
  logprob: z.number(),
  token: z.string(),
  top_logprobs: z.array(zTopLogProb),
})

export const zOutputMessageContent = z.union([
  z.object({
    annotations: z.array(zAnnotation).optional(),
    logprobs: z.array(zTokenLogProb).optional(),
    text: z.string(),
    type: z.enum(['output_text']),
  }),
  z.object({
    refusal: z.string(),
    type: z.enum(['refusal']),
  }),
])

/**
 * An output message from the model.
 */
export const zOutputMessage = z.object({
  content: z.array(zOutputMessageContent),
  id: z.string().optional(),
  role: z.string(),
  status: z.string().optional(),
  type: z.string(),
})

export const zUsage = z.object({
  completion_tokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  completion_tokens_details: zCompletionUsageDetail,
  cost_in_usd_ticks: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  num_sources_used: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  prompt_tokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  prompt_tokens_details: zPromptUsageDetail,
  total_tokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
})

/**
 * The chat response body for `/v1/chat/completions` endpoint.
 */
export const zChatResponse = z.object({
  choices: z.array(zChoice),
  citations: z.unknown().optional(),
  created: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  id: z.string(),
  model: z.string(),
  object: z.string(),
  output_files: z.unknown().optional(),
  service_tier: zServiceTier,
  system_fingerprint: z.unknown().optional(),
  usage: z.union([z.unknown(), zUsage]).optional(),
})

/**
 * (Legacy) Response for `/v1/completions` endpoint
 */
export const zSampleResponse = z.object({
  choices: z.array(zSampleChoice),
  created: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  id: z.string(),
  model: z.string(),
  object: z.string(),
  system_fingerprint: z.unknown().optional(),
  usage: z.union([z.unknown(), zUsage]).optional(),
})

export const zWebSearchFilters = z.object({
  allowed_domains: z.unknown().optional(),
  excluded_domains: z.unknown().optional(),
})

export const zWebSearchOptions = z.object({
  filters: z.unknown().optional(),
  search_context_size: z.unknown().optional().default('medium'),
  user_location: z.unknown().optional(),
})

/**
 * The chat request body for `/v1/chat/completions` endpoint.
 */
export const zChatRequest = z.object({
  deferred: z.unknown().optional().default(false),
  frequency_penalty: z.unknown().optional().default(0),
  logit_bias: z.unknown().optional(),
  logprobs: z.unknown().optional().default(false),
  max_completion_tokens: z.unknown().optional(),
  max_tokens: z.unknown().optional(),
  messages: z.array(zMessage).optional(),
  model: z.string().optional(),
  n: z.unknown().optional().default(1),
  parallel_tool_calls: z.unknown().optional().default(true),
  presence_penalty: z.unknown().optional().default(0),
  prompt_cache_key: z.unknown().optional(),
  reasoning_effort: z.unknown().optional(),
  response_format: z.union([z.unknown(), zResponseFormat]).optional(),
  search_parameters: z.union([z.unknown(), zSearchParameters]).optional(),
  seed: z.unknown().optional(),
  service_tier: z.union([z.unknown(), zServiceTier]).optional(),
  stop: z.unknown().optional(),
  stream: z.unknown().optional().default(false),
  stream_options: z.union([z.unknown(), zStreamOptions]).optional(),
  temperature: z.unknown().optional().default(1),
  tool_choice: z.union([z.unknown(), zToolChoice]).optional(),
  tools: z.unknown().optional(),
  top_logprobs: z.unknown().optional(),
  top_p: z.unknown().optional().default(1),
  user: z.unknown().optional(),
  web_search_options: z.union([z.unknown(), zWebSearchOptions]).optional(),
})

export const zWebSearchSource = z.object({
  type: z.string(),
  url: z.string().optional(),
})

export const zWebSearchAction = z.union([
  z.object({
    query: z.string(),
    sources: z.array(zWebSearchSource).optional(),
    type: z.enum(['search']),
  }),
  z.object({
    type: z.enum(['open_page']),
    url: z.string(),
  }),
  z.object({
    pattern: z.string(),
    type: z.enum(['find_in_page']),
    url: z.string(),
  }),
])

/**
 * The output of a web search tool call.
 */
export const zWebSearchCall = z.object({
  action: zWebSearchAction,
  id: z.string().optional(),
  status: z.string().optional(),
  type: z.string(),
})

export const zModelOutput = z.union([
  zOutputMessage,
  zFunctionToolCall,
  zReasoning,
  zWebSearchCall,
  zFileSearchCall,
  zCodeInterpreterCall,
  zMcpCall,
  zCustomToolCall,
  zShellCall,
])

export const zModelInputPart = z.union([
  z.object({
    content: zModelInputContent,
    name: z.unknown().optional(),
    role: z.string(),
    type: z.unknown().optional(),
  }),
  zModelOutput,
  zFunctionToolCallOutput,
  zShellCallOutput,
  zCompactionOutputItem,
])

/**
 * Content of the input passed to a `/v1/response` request.
 */
export const zModelInput = z.union([z.string(), z.array(zModelInputPart)])

/**
 * The request body for `/v1/responses` endpoint.
 */
export const zModelRequest = z.object({
  background: z.unknown().optional().default(false),
  context_management: z.unknown().optional(),
  include: z.unknown().optional(),
  input: zModelInput,
  instructions: z.unknown().optional(),
  logprobs: z.unknown().optional().default(false),
  max_output_tokens: z.unknown().optional(),
  max_turns: z.unknown().optional(),
  metadata: z.unknown().optional(),
  model: z.string().optional(),
  parallel_tool_calls: z.unknown().optional().default(true),
  previous_response_id: z.unknown().optional(),
  prompt_cache_key: z.unknown().optional(),
  reasoning: z.union([z.unknown(), zReasoningConfiguration]).optional(),
  search_parameters: z.union([z.unknown(), zSearchParameters]).optional(),
  service_tier: z.union([z.unknown(), zServiceTier]).optional(),
  store: z.unknown().optional().default(true),
  stream: z.unknown().optional().default(false),
  temperature: z.unknown().optional().default(1),
  text: z.union([z.unknown(), zModelResponseConfiguration]).optional(),
  tool_choice: z.union([z.unknown(), zModelToolChoice]).optional(),
  tools: z.unknown().optional(),
  top_logprobs: z.unknown().optional(),
  top_p: z.unknown().optional().default(1),
  truncation: z.unknown().optional(),
  user: z.unknown().optional(),
})

export const zWebSearchUserLocation = z.object({
  city: z.unknown().optional(),
  country: z.unknown().optional(),
  region: z.unknown().optional(),
  timezone: z.unknown().optional(),
  type: z.string(),
})

/**
 * Definition of one tool that the model can call.
 */
export const zModelTool = z.union([
  zFunctionDefinition.and(
    z.object({
      type: z.enum(['function']),
    }),
  ),
  zWebSearchOptions
    .and(
      z.object({
        allowed_domains: z.unknown().optional(),
        enable_image_search: z.unknown().optional(),
        enable_image_understanding: z.unknown().optional(),
        excluded_domains: z.unknown().optional(),
        external_web_access: z.unknown().optional(),
        filters: z.union([z.unknown(), zWebSearchFilters]).optional(),
        search_context_size: z.unknown().optional(),
        user_location: z
          .union([z.unknown(), zWebSearchUserLocation])
          .optional(),
      }),
    )
    .and(
      z.object({
        type: z.enum(['web_search']),
      }),
    ),
  z.object({
    allowed_x_handles: z.unknown().optional(),
    enable_image_understanding: z.unknown().optional(),
    enable_video_understanding: z.unknown().optional(),
    excluded_x_handles: z.unknown().optional(),
    from_date: z.unknown().optional(),
    to_date: z.unknown().optional(),
    type: z.enum(['x_search']),
  }),
  z.object({
    filters: z.unknown().optional(),
    max_num_results: z.unknown().optional(),
    ranking_options: z.unknown().optional(),
    type: z.enum(['file_search']),
    vector_store_ids: z.array(z.string()).max(10),
  }),
  z.object({
    container: z.unknown().optional(),
    type: z.enum(['code_interpreter']),
  }),
  z.object({
    allowed_tools: z.unknown().optional(),
    authorization: z.unknown().optional(),
    connector_id: z.unknown().optional(),
    headers: z.unknown().optional(),
    require_approval: z.unknown().optional(),
    server_description: z.unknown().optional(),
    server_label: z.string(),
    server_url: z.string(),
    type: z.enum(['mcp']),
  }),
  z.object({
    environment: zShellEnvironment,
    type: z.enum(['shell']),
  }),
])

/**
 * The response body for `/v1/responses` endpoint.
 */
export const zModelResponse = z.object({
  background: z.boolean().default(false),
  completed_at: z.unknown().optional(),
  created_at: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  error: z.unknown().optional(),
  frequency_penalty: z.number(),
  id: z.string(),
  incomplete_details: z.union([z.unknown(), zIncompleteDetails]).optional(),
  instructions: z.unknown().optional(),
  max_output_tokens: z.unknown().optional(),
  max_tool_calls: z.unknown().optional(),
  metadata: z.unknown(),
  model: z.string(),
  object: z.string(),
  output: z.array(zModelOutput),
  parallel_tool_calls: z.boolean(),
  presence_penalty: z.number(),
  previous_response_id: z.unknown().optional(),
  prompt_cache_key: z.unknown().optional(),
  reasoning: z.union([z.unknown(), zReasoningConfiguration]).optional(),
  safety_identifier: z.unknown().optional(),
  service_tier: zServiceTier,
  status: z.string(),
  store: z.boolean().default(true),
  temperature: z.unknown().optional().default(1),
  text: zModelResponseConfiguration,
  tool_choice: zModelToolChoice,
  tools: z.array(zModelTool).max(128),
  top_logprobs: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  top_p: z.unknown().optional().default(1),
  truncation: z.string().default('disabled'),
  usage: z.union([z.unknown(), zModelUsage]).optional(),
  user: z.unknown().optional(),
})

export const zHandleGenericCompletionRequestBody = zChatRequest

/**
 * Success
 */
export const zHandleGenericCompletionRequestResponse = zChatResponse

export const zHandleGenericCompleteRequestBody = zCompleteRequest

/**
 * Success
 */
export const zHandleGenericCompleteRequestResponse = zCompleteResponse

export const zHandleSampleRequestBody = zSampleRequest

/**
 * Success
 */
export const zHandleSampleRequestResponse = zSampleResponse

export const zHandleGenericMessagesRequestBody = zMessageRequest

/**
 * Success
 */
export const zHandleGenericMessagesRequestResponse = zMessageResponse

export const zHandleGenericModelRequestBody = zModelRequest

/**
 * Success
 */
export const zHandleGenericModelRequestResponse = zModelResponse

export const zHandleTokenizeTextRequestBody = zTokenizeRequest

/**
 * Success
 */
export const zHandleTokenizeTextRequestResponse = zTokenizeResponse
