// AUTO-GENERATED - Do not edit manually
// Generated by @hey-api/openapi-ts and post-processed by
// scripts/generate-endpoint-maps.ts to embed each schema's $defs closure.

export const BatchEmbedContentsRequestSchema = {
  type: 'object',
  description:
    'Batch request to get embeddings from the model for a list of prompts.',
  properties: {
    requests: {
      type: 'array',
      description:
        'Required. Embed requests for the batch. The model in each of these requests must match the model specified `BatchEmbedContentsRequest.model`.',
      items: { $ref: '#/$defs/EmbedContentRequest' },
    },
  },
  $defs: {
    Blob: {
      type: 'object',
      description:
        "Raw media bytes. Text should not be sent as raw bytes, use the 'text' field.",
      properties: {
        mimeType: {
          type: 'string',
          description:
            'The IANA standard MIME type of the source data. Examples of supported types: - Images: image/png, image/jpeg, image/jpg, image/webp, image/heic, image/heif, image/gif, image/avif - Audio: audio/*, video/audio/s16le, video/audio/wav - Video: video/* - Text: text/plain, text/html, text/css, text/javascript, text/x-typescript, text/csv, text/markdown, text/x-python, text/xml, text/rtf, video/text/timestamp - Applications: application/x-javascript, application/x-typescript, application/x-python-code, application/json, application/x-ipynb+json, application/rtf, application/pdf For additional context, see [Supported file formats](https://ai.google.dev/gemini-api/docs/file-input-methods#supported-content-types). //',
        },
        data: {
          type: 'string',
          format: 'byte',
          description: 'Raw bytes for media formats.',
        },
      },
    },
    CodeExecutionResult: {
      type: 'object',
      description:
        'Result of executing the `ExecutableCode`. Generated only when the `CodeExecution` tool is used.',
      properties: {
        output: {
          type: 'string',
          description:
            'Optional. Contains stdout when code execution is successful, stderr or other description otherwise.',
        },
        outcome: {
          type: 'string',
          description: 'Required. Outcome of the code execution.',
          enum: [
            'OUTCOME_UNSPECIFIED',
            'OUTCOME_OK',
            'OUTCOME_FAILED',
            'OUTCOME_DEADLINE_EXCEEDED',
          ],
        },
        id: {
          type: 'string',
          description:
            'Optional. The identifier of the `ExecutableCode` part this result is for. Only populated if the corresponding `ExecutableCode` has an id.',
        },
      },
    },
    Content: {
      type: 'object',
      description:
        'The base structured datatype containing multi-part content of a message. A `Content` includes a `role` field designating the producer of the `Content` and a `parts` field containing multi-part data that contains the content of the message turn.',
      properties: {
        role: {
          type: 'string',
          description:
            "Optional. The producer of the content. Must be either 'user' or 'model'. Useful to set for multi-turn conversations, otherwise can be left blank or unset.",
        },
        parts: {
          type: 'array',
          description:
            'Ordered `Parts` that constitute a single message. Parts may have different MIME types.',
          items: { $ref: '#/$defs/Part' },
        },
      },
    },
    EmbedContentConfig: {
      type: 'object',
      description: 'Configurations for the EmbedContent request.',
      properties: {
        documentOcr: {
          type: 'boolean',
          description: 'Optional. Whether to enable OCR for document content.',
        },
        audioTrackExtraction: {
          type: 'boolean',
          description: 'Optional. Whether to extract audio from video content.',
        },
        taskType: {
          type: 'string',
          description: 'Optional. The task type of the embedding.',
          enum: [
            'TASK_TYPE_UNSPECIFIED',
            'RETRIEVAL_QUERY',
            'RETRIEVAL_DOCUMENT',
            'SEMANTIC_SIMILARITY',
            'CLASSIFICATION',
            'CLUSTERING',
            'QUESTION_ANSWERING',
            'FACT_VERIFICATION',
            'CODE_RETRIEVAL_QUERY',
          ],
        },
        outputDimensionality: {
          type: 'integer',
          format: 'int32',
          description:
            'Optional. Reduced dimension for the output embedding. If set, excessive values in the output embedding are truncated from the end.',
        },
        title: {
          type: 'string',
          description: 'Optional. The title for the text.',
        },
        autoTruncate: {
          type: 'boolean',
          description:
            "Optional. Whether to silently truncate the input content if it's longer than the maximum sequence length.",
        },
      },
    },
    EmbedContentRequest: {
      type: 'object',
      description: 'Request containing the `Content` for the model to embed.',
      properties: {
        title: {
          type: 'string',
          description:
            'Optional. Deprecated: Please use EmbedContentConfig.title instead. An optional title for the text. Only applicable when TaskType is `RETRIEVAL_DOCUMENT`. Note: Specifying a `title` for `RETRIEVAL_DOCUMENT` provides better quality embeddings for retrieval.',
        },
        content: { $ref: '#/$defs/Content' },
        taskType: {
          type: 'string',
          description:
            'Optional. Deprecated: Please use EmbedContentConfig.task_type instead. Optional task type for which the embeddings will be used. Not supported on earlier models (`models/embedding-001`).',
          enum: [
            'TASK_TYPE_UNSPECIFIED',
            'RETRIEVAL_QUERY',
            'RETRIEVAL_DOCUMENT',
            'SEMANTIC_SIMILARITY',
            'CLASSIFICATION',
            'CLUSTERING',
            'QUESTION_ANSWERING',
            'FACT_VERIFICATION',
            'CODE_RETRIEVAL_QUERY',
          ],
        },
        outputDimensionality: {
          type: 'integer',
          format: 'int32',
          description:
            'Optional. Deprecated: Please use EmbedContentConfig.output_dimensionality instead. Optional reduced dimension for the output embedding. If set, excessive values in the output embedding are truncated from the end. Supported by newer models since 2024 only. You cannot set this value if using the earlier model (`models/embedding-001`).',
        },
        model: {
          type: 'string',
          description:
            "Required. The model's resource name. This serves as an ID for the Model to use. This name should match a model name returned by the `ListModels` method. Format: `models/{model}`",
        },
        embedContentConfig: { $ref: '#/$defs/EmbedContentConfig' },
      },
    },
    ExecutableCode: {
      type: 'object',
      description:
        'Code generated by the model that is meant to be executed, and the result returned to the model. Only generated when using the `CodeExecution` tool, in which the code will be automatically executed, and a corresponding `CodeExecutionResult` will also be generated.',
      properties: {
        language: {
          type: 'string',
          description: 'Required. Programming language of the `code`.',
          enum: ['LANGUAGE_UNSPECIFIED', 'PYTHON'],
        },
        code: {
          type: 'string',
          description: 'Required. The code to be executed.',
        },
        id: {
          type: 'string',
          description:
            'Optional. Unique identifier of the `ExecutableCode` part. The server returns the `CodeExecutionResult` with the matching `id`.',
        },
      },
    },
    FileData: {
      type: 'object',
      description: 'URI based data.',
      properties: {
        mimeType: {
          type: 'string',
          description:
            'Optional. The IANA standard MIME type of the source data.',
        },
        fileUri: { type: 'string', description: 'Required. URI.' },
      },
    },
    FunctionCall: {
      type: 'object',
      description:
        'A predicted `FunctionCall` returned from the model that contains a string representing the `FunctionDeclaration.name` with the arguments and their values.',
      properties: {
        id: {
          type: 'string',
          description:
            'Optional. Unique identifier of the function call. If populated, the client to execute the `function_call` and return the response with the matching `id`.',
        },
        name: {
          type: 'string',
          description:
            'Required. The name of the function to call. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 128.',
        },
        args: {
          type: 'object',
          description:
            'Optional. The function parameters and values in JSON object format.',
          additionalProperties: {
            type: 'any',
            description: 'Properties of the object.',
          },
        },
      },
    },
    FunctionResponse: {
      type: 'object',
      description:
        'The result output from a `FunctionCall` that contains a string representing the `FunctionDeclaration.name` and a structured JSON object containing any output from the function is used as context to the model. This should contain the result of a`FunctionCall` made based on model prediction.',
      properties: {
        id: {
          type: 'string',
          description:
            'Optional. The identifier of the function call this response is for. Populated by the client to match the corresponding function call `id`.',
        },
        scheduling: {
          type: 'string',
          description:
            'Optional. Specifies how the response should be scheduled in the conversation. Only applicable to NON_BLOCKING function calls, is ignored otherwise. Defaults to WHEN_IDLE.',
          enum: ['SCHEDULING_UNSPECIFIED', 'SILENT', 'WHEN_IDLE', 'INTERRUPT'],
        },
        willContinue: {
          type: 'boolean',
          description:
            'Optional. Signals that function call continues, and more responses will be returned, turning the function call into a generator. Is only applicable to NON_BLOCKING function calls, is ignored otherwise. If set to false, future responses will not be considered. It is allowed to return empty `response` with `will_continue=False` to signal that the function call is finished. This may still trigger the model generation. To avoid triggering the generation and finish the function call, additionally set `scheduling` to `SILENT`.',
        },
        name: {
          type: 'string',
          description:
            'Required. The name of the function to call. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 128.',
        },
        response: {
          type: 'object',
          description:
            'Required. The function response in JSON object format. Callers can use any keys of their choice that fit the function\'s syntax to return the function output, e.g. "output", "result", etc. In particular, if the function call failed to execute, the response can have an "error" key to return error details to the model. Multimedia can be included by using a subobject containing a single "$ref" key whose value is the `inline_data.display_name` of a `FunctionResponsePart` holding the multimedia. See https://ai.google.dev/gemini-api/docs/function-calling#multimodal.',
          additionalProperties: {
            type: 'any',
            description: 'Properties of the object.',
          },
        },
        parts: {
          type: 'array',
          description:
            'Optional. Ordered `Parts` that constitute a function response. Parts may have different IANA MIME types.',
          items: { $ref: '#/$defs/FunctionResponsePart' },
        },
      },
    },
    FunctionResponseBlob: {
      type: 'object',
      description:
        "Raw media bytes for function response. Text should not be sent as raw bytes, use the 'FunctionResponse.response' field.",
      properties: {
        mimeType: {
          type: 'string',
          description:
            'The IANA standard MIME type of the source data. Examples: - image/png - image/jpeg If an unsupported MIME type is provided, an error will be returned. For a complete list of supported types, see [Supported file formats](https://ai.google.dev/gemini-api/docs/prompting_with_media#supported_file_formats).',
        },
        data: {
          type: 'string',
          format: 'byte',
          description: 'Raw bytes for media formats.',
        },
      },
    },
    FunctionResponsePart: {
      type: 'object',
      description:
        'A datatype containing media that is part of a `FunctionResponse` message. A `FunctionResponsePart` consists of data which has an associated datatype. A `FunctionResponsePart` can only contain one of the accepted types in `FunctionResponsePart.data`. A `FunctionResponsePart` must have a fixed IANA MIME type identifying the type and subtype of the media if the `inline_data` field is filled with raw bytes.',
      properties: { inlineData: { $ref: '#/$defs/FunctionResponseBlob' } },
    },
    MediaResolution: {
      type: 'object',
      description:
        'Schema referenced but not defined upstream (missing from source OpenAPI spec)',
      additionalProperties: true,
    },
    Part: {
      type: 'object',
      description:
        'A datatype containing media that is part of a multi-part `Content` message. A `Part` consists of data which has an associated datatype. A `Part` can only contain one of the accepted types in `Part.data`. A `Part` must have a fixed IANA MIME type identifying the type and subtype of the media if the `inline_data` field is filled with raw bytes.',
      properties: {
        videoMetadata: { $ref: '#/$defs/VideoMetadata' },
        text: { type: 'string', description: 'Inline text.' },
        executableCode: { $ref: '#/$defs/ExecutableCode' },
        functionResponse: { $ref: '#/$defs/FunctionResponse' },
        thought: {
          type: 'boolean',
          description:
            'Optional. Indicates if the part is thought from the model.',
        },
        mediaResolution: { $ref: '#/$defs/MediaResolution' },
        fileData: { $ref: '#/$defs/FileData' },
        partMetadata: {
          type: 'object',
          description:
            'Custom metadata associated with the Part. Agents using genai.Part as content representation may need to keep track of the additional information. For example it can be name of a file/source from which the Part originates or a way to multiplex multiple Part streams.',
          additionalProperties: {
            type: 'any',
            description: 'Properties of the object.',
          },
        },
        functionCall: { $ref: '#/$defs/FunctionCall' },
        toolResponse: { $ref: '#/$defs/ToolResponse' },
        inlineData: { $ref: '#/$defs/Blob' },
        codeExecutionResult: { $ref: '#/$defs/CodeExecutionResult' },
        toolCall: { $ref: '#/$defs/ToolCall' },
        thoughtSignature: {
          type: 'string',
          format: 'byte',
          description:
            'Optional. An opaque signature for the thought so it can be reused in subsequent requests.',
        },
      },
    },
    ToolCall: {
      type: 'object',
      description:
        'A predicted server-side `ToolCall` returned from the model. This message contains information about a tool that the model wants to invoke. The client is NOT expected to execute this `ToolCall`. Instead, the client should pass this `ToolCall` back to the API in a subsequent turn within a `Content` message, along with the corresponding `ToolResponse`.',
      properties: {
        id: {
          type: 'string',
          description:
            'Optional. Unique identifier of the tool call. The server returns the tool response with the matching `id`.',
        },
        toolType: {
          type: 'string',
          description: 'Required. The type of tool that was called.',
          enum: [
            'TOOL_TYPE_UNSPECIFIED',
            'GOOGLE_SEARCH_WEB',
            'GOOGLE_SEARCH_IMAGE',
            'URL_CONTEXT',
            'GOOGLE_MAPS',
            'FILE_SEARCH',
          ],
        },
        args: {
          type: 'object',
          description:
            'Optional. The tool call arguments. Example: {"arg1" : "value1", "arg2" : "value2" , ...}',
          additionalProperties: {
            type: 'any',
            description: 'Properties of the object.',
          },
        },
      },
    },
    ToolResponse: {
      type: 'object',
      description:
        'The output from a server-side `ToolCall` execution. This message contains the results of a tool invocation that was initiated by a `ToolCall` from the model. The client should pass this `ToolResponse` back to the API in a subsequent turn within a `Content` message, along with the corresponding `ToolCall`.',
      properties: {
        id: {
          type: 'string',
          description:
            'Optional. The identifier of the tool call this response is for.',
        },
        toolType: {
          type: 'string',
          description:
            'Required. The type of tool that was called, matching the `tool_type` in the corresponding `ToolCall`.',
          enum: [
            'TOOL_TYPE_UNSPECIFIED',
            'GOOGLE_SEARCH_WEB',
            'GOOGLE_SEARCH_IMAGE',
            'URL_CONTEXT',
            'GOOGLE_MAPS',
            'FILE_SEARCH',
          ],
        },
        response: {
          type: 'object',
          description: 'Optional. The tool response.',
          additionalProperties: {
            type: 'any',
            description: 'Properties of the object.',
          },
        },
      },
    },
    VideoMetadata: {
      type: 'object',
      description:
        'Deprecated: Use `GenerateContentRequest.processing_options` instead. Metadata describes the input video content.',
      properties: {
        startOffset: {
          type: 'string',
          format: 'google-duration',
          description: 'Optional. The start offset of the video.',
        },
        endOffset: {
          type: 'string',
          format: 'google-duration',
          description: 'Optional. The end offset of the video.',
        },
        fps: {
          type: 'number',
          format: 'double',
          description:
            'Optional. The frame rate of the video sent to the model. If not specified, the default value will be 1.0. The fps range is (0.0, 24.0].',
        },
      },
    },
  },
} as const

export const BatchEmbedContentsResponseSchema = {
  type: 'object',
  description: 'The response to a `BatchEmbedContentsRequest`.',
  properties: {
    usageMetadata: { $ref: '#/$defs/EmbeddingUsageMetadata' },
    embeddings: {
      type: 'array',
      description:
        'Output only. The embeddings for each request, in the same order as provided in the batch request.',
      items: { $ref: '#/$defs/ContentEmbedding' },
    },
  },
  $defs: {
    ContentEmbedding: {
      type: 'object',
      description: 'A list of floats representing an embedding.',
      properties: {
        values: {
          type: 'array',
          description:
            'The embedding values. This is for 3P users only and will not be populated for 1P calls.',
          items: { type: 'number', format: 'float' },
        },
        shape: {
          type: 'array',
          description:
            'This field stores the soft tokens tensor frame shape (e.g. [1, 1, 256, 2048]).',
          items: { type: 'integer', format: 'int32' },
        },
      },
    },
    EmbeddingUsageMetadata: {
      type: 'object',
      description: 'Metadata on the usage of the embedding request.',
      properties: {
        promptTokenDetails: {
          type: 'array',
          description:
            'Output only. List of modalities that were processed in the request input.',
          items: { $ref: '#/$defs/ModalityTokenCount' },
        },
        promptTokenCount: {
          type: 'integer',
          format: 'int32',
          description: 'Output only. Number of tokens in the prompt.',
        },
      },
    },
    ModalityTokenCount: {
      type: 'object',
      description: 'Represents token counting info for a single modality.',
      properties: {
        modality: {
          type: 'string',
          description: 'The modality associated with this token count.',
          enum: [
            'MODALITY_UNSPECIFIED',
            'TEXT',
            'IMAGE',
            'VIDEO',
            'AUDIO',
            'DOCUMENT',
          ],
        },
        tokenCount: {
          type: 'integer',
          format: 'int32',
          description: 'Number of tokens.',
        },
      },
    },
  },
} as const

export const BatchEmbedTextRequestSchema = {
  type: 'object',
  description: 'Batch request to get a text embedding from the model.',
  properties: {
    texts: {
      type: 'array',
      description:
        'Optional. The free-form input texts that the model will turn into an embedding. The current limit is 100 texts, over which an error will be thrown.',
      items: { type: 'string' },
    },
    requests: {
      type: 'array',
      description:
        'Optional. Embed requests for the batch. Only one of `texts` or `requests` can be set.',
      items: { $ref: '#/$defs/EmbedTextRequest' },
    },
  },
  $defs: {
    EmbedTextRequest: {
      type: 'object',
      description: 'Request to get a text embedding from the model.',
      properties: {
        model: {
          type: 'string',
          description:
            'Required. The model name to use with the format model=models/{model}.',
        },
        text: {
          type: 'string',
          description:
            'Optional. The free-form input text that the model will turn into an embedding.',
        },
      },
    },
  },
} as const

export const BatchEmbedTextResponseSchema = {
  type: 'object',
  description: 'The response to a EmbedTextRequest.',
  properties: {
    embeddings: {
      type: 'array',
      description: 'Output only. The embeddings generated from the input text.',
      items: { $ref: '#/$defs/Embedding' },
    },
  },
  $defs: {
    Embedding: {
      type: 'object',
      description: 'A list of floats representing the embedding.',
      properties: {
        value: {
          type: 'array',
          description: 'The embedding values.',
          items: { type: 'number', format: 'float' },
        },
      },
    },
  },
} as const

export const BlobSchema = {
  type: 'object',
  description:
    "Raw media bytes. Text should not be sent as raw bytes, use the 'text' field.",
  properties: {
    mimeType: {
      type: 'string',
      description:
        'The IANA standard MIME type of the source data. Examples of supported types: - Images: image/png, image/jpeg, image/jpg, image/webp, image/heic, image/heif, image/gif, image/avif - Audio: audio/*, video/audio/s16le, video/audio/wav - Video: video/* - Text: text/plain, text/html, text/css, text/javascript, text/x-typescript, text/csv, text/markdown, text/x-python, text/xml, text/rtf, video/text/timestamp - Applications: application/x-javascript, application/x-typescript, application/x-python-code, application/json, application/x-ipynb+json, application/rtf, application/pdf For additional context, see [Supported file formats](https://ai.google.dev/gemini-api/docs/file-input-methods#supported-content-types). //',
    },
    data: {
      type: 'string',
      format: 'byte',
      description: 'Raw bytes for media formats.',
    },
  },
} as const

export const CodeExecutionResultSchema = {
  type: 'object',
  description:
    'Result of executing the `ExecutableCode`. Generated only when the `CodeExecution` tool is used.',
  properties: {
    output: {
      type: 'string',
      description:
        'Optional. Contains stdout when code execution is successful, stderr or other description otherwise.',
    },
    outcome: {
      type: 'string',
      description: 'Required. Outcome of the code execution.',
      enum: [
        'OUTCOME_UNSPECIFIED',
        'OUTCOME_OK',
        'OUTCOME_FAILED',
        'OUTCOME_DEADLINE_EXCEEDED',
      ],
    },
    id: {
      type: 'string',
      description:
        'Optional. The identifier of the `ExecutableCode` part this result is for. Only populated if the corresponding `ExecutableCode` has an id.',
    },
  },
} as const

export const ContentSchema = {
  type: 'object',
  description:
    'The base structured datatype containing multi-part content of a message. A `Content` includes a `role` field designating the producer of the `Content` and a `parts` field containing multi-part data that contains the content of the message turn.',
  properties: {
    role: {
      type: 'string',
      description:
        "Optional. The producer of the content. Must be either 'user' or 'model'. Useful to set for multi-turn conversations, otherwise can be left blank or unset.",
    },
    parts: {
      type: 'array',
      description:
        'Ordered `Parts` that constitute a single message. Parts may have different MIME types.',
      items: { $ref: '#/$defs/Part' },
    },
  },
  $defs: {
    Blob: {
      type: 'object',
      description:
        "Raw media bytes. Text should not be sent as raw bytes, use the 'text' field.",
      properties: {
        mimeType: {
          type: 'string',
          description:
            'The IANA standard MIME type of the source data. Examples of supported types: - Images: image/png, image/jpeg, image/jpg, image/webp, image/heic, image/heif, image/gif, image/avif - Audio: audio/*, video/audio/s16le, video/audio/wav - Video: video/* - Text: text/plain, text/html, text/css, text/javascript, text/x-typescript, text/csv, text/markdown, text/x-python, text/xml, text/rtf, video/text/timestamp - Applications: application/x-javascript, application/x-typescript, application/x-python-code, application/json, application/x-ipynb+json, application/rtf, application/pdf For additional context, see [Supported file formats](https://ai.google.dev/gemini-api/docs/file-input-methods#supported-content-types). //',
        },
        data: {
          type: 'string',
          format: 'byte',
          description: 'Raw bytes for media formats.',
        },
      },
    },
    CodeExecutionResult: {
      type: 'object',
      description:
        'Result of executing the `ExecutableCode`. Generated only when the `CodeExecution` tool is used.',
      properties: {
        output: {
          type: 'string',
          description:
            'Optional. Contains stdout when code execution is successful, stderr or other description otherwise.',
        },
        outcome: {
          type: 'string',
          description: 'Required. Outcome of the code execution.',
          enum: [
            'OUTCOME_UNSPECIFIED',
            'OUTCOME_OK',
            'OUTCOME_FAILED',
            'OUTCOME_DEADLINE_EXCEEDED',
          ],
        },
        id: {
          type: 'string',
          description:
            'Optional. The identifier of the `ExecutableCode` part this result is for. Only populated if the corresponding `ExecutableCode` has an id.',
        },
      },
    },
    ExecutableCode: {
      type: 'object',
      description:
        'Code generated by the model that is meant to be executed, and the result returned to the model. Only generated when using the `CodeExecution` tool, in which the code will be automatically executed, and a corresponding `CodeExecutionResult` will also be generated.',
      properties: {
        language: {
          type: 'string',
          description: 'Required. Programming language of the `code`.',
          enum: ['LANGUAGE_UNSPECIFIED', 'PYTHON'],
        },
        code: {
          type: 'string',
          description: 'Required. The code to be executed.',
        },
        id: {
          type: 'string',
          description:
            'Optional. Unique identifier of the `ExecutableCode` part. The server returns the `CodeExecutionResult` with the matching `id`.',
        },
      },
    },
    FileData: {
      type: 'object',
      description: 'URI based data.',
      properties: {
        mimeType: {
          type: 'string',
          description:
            'Optional. The IANA standard MIME type of the source data.',
        },
        fileUri: { type: 'string', description: 'Required. URI.' },
      },
    },
    FunctionCall: {
      type: 'object',
      description:
        'A predicted `FunctionCall` returned from the model that contains a string representing the `FunctionDeclaration.name` with the arguments and their values.',
      properties: {
        id: {
          type: 'string',
          description:
            'Optional. Unique identifier of the function call. If populated, the client to execute the `function_call` and return the response with the matching `id`.',
        },
        name: {
          type: 'string',
          description:
            'Required. The name of the function to call. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 128.',
        },
        args: {
          type: 'object',
          description:
            'Optional. The function parameters and values in JSON object format.',
          additionalProperties: {
            type: 'any',
            description: 'Properties of the object.',
          },
        },
      },
    },
    FunctionResponse: {
      type: 'object',
      description:
        'The result output from a `FunctionCall` that contains a string representing the `FunctionDeclaration.name` and a structured JSON object containing any output from the function is used as context to the model. This should contain the result of a`FunctionCall` made based on model prediction.',
      properties: {
        id: {
          type: 'string',
          description:
            'Optional. The identifier of the function call this response is for. Populated by the client to match the corresponding function call `id`.',
        },
        scheduling: {
          type: 'string',
          description:
            'Optional. Specifies how the response should be scheduled in the conversation. Only applicable to NON_BLOCKING function calls, is ignored otherwise. Defaults to WHEN_IDLE.',
          enum: ['SCHEDULING_UNSPECIFIED', 'SILENT', 'WHEN_IDLE', 'INTERRUPT'],
        },
        willContinue: {
          type: 'boolean',
          description:
            'Optional. Signals that function call continues, and more responses will be returned, turning the function call into a generator. Is only applicable to NON_BLOCKING function calls, is ignored otherwise. If set to false, future responses will not be considered. It is allowed to return empty `response` with `will_continue=False` to signal that the function call is finished. This may still trigger the model generation. To avoid triggering the generation and finish the function call, additionally set `scheduling` to `SILENT`.',
        },
        name: {
          type: 'string',
          description:
            'Required. The name of the function to call. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 128.',
        },
        response: {
          type: 'object',
          description:
            'Required. The function response in JSON object format. Callers can use any keys of their choice that fit the function\'s syntax to return the function output, e.g. "output", "result", etc. In particular, if the function call failed to execute, the response can have an "error" key to return error details to the model. Multimedia can be included by using a subobject containing a single "$ref" key whose value is the `inline_data.display_name` of a `FunctionResponsePart` holding the multimedia. See https://ai.google.dev/gemini-api/docs/function-calling#multimodal.',
          additionalProperties: {
            type: 'any',
            description: 'Properties of the object.',
          },
        },
        parts: {
          type: 'array',
          description:
            'Optional. Ordered `Parts` that constitute a function response. Parts may have different IANA MIME types.',
          items: { $ref: '#/$defs/FunctionResponsePart' },
        },
      },
    },
    FunctionResponseBlob: {
      type: 'object',
      description:
        "Raw media bytes for function response. Text should not be sent as raw bytes, use the 'FunctionResponse.response' field.",
      properties: {
        mimeType: {
          type: 'string',
          description:
            'The IANA standard MIME type of the source data. Examples: - image/png - image/jpeg If an unsupported MIME type is provided, an error will be returned. For a complete list of supported types, see [Supported file formats](https://ai.google.dev/gemini-api/docs/prompting_with_media#supported_file_formats).',
        },
        data: {
          type: 'string',
          format: 'byte',
          description: 'Raw bytes for media formats.',
        },
      },
    },
    FunctionResponsePart: {
      type: 'object',
      description:
        'A datatype containing media that is part of a `FunctionResponse` message. A `FunctionResponsePart` consists of data which has an associated datatype. A `FunctionResponsePart` can only contain one of the accepted types in `FunctionResponsePart.data`. A `FunctionResponsePart` must have a fixed IANA MIME type identifying the type and subtype of the media if the `inline_data` field is filled with raw bytes.',
      properties: { inlineData: { $ref: '#/$defs/FunctionResponseBlob' } },
    },
    MediaResolution: {
      type: 'object',
      description:
        'Schema referenced but not defined upstream (missing from source OpenAPI spec)',
      additionalProperties: true,
    },
    Part: {
      type: 'object',
      description:
        'A datatype containing media that is part of a multi-part `Content` message. A `Part` consists of data which has an associated datatype. A `Part` can only contain one of the accepted types in `Part.data`. A `Part` must have a fixed IANA MIME type identifying the type and subtype of the media if the `inline_data` field is filled with raw bytes.',
      properties: {
        videoMetadata: { $ref: '#/$defs/VideoMetadata' },
        text: { type: 'string', description: 'Inline text.' },
        executableCode: { $ref: '#/$defs/ExecutableCode' },
        functionResponse: { $ref: '#/$defs/FunctionResponse' },
        thought: {
          type: 'boolean',
          description:
            'Optional. Indicates if the part is thought from the model.',
        },
        mediaResolution: { $ref: '#/$defs/MediaResolution' },
        fileData: { $ref: '#/$defs/FileData' },
        partMetadata: {
          type: 'object',
          description:
            'Custom metadata associated with the Part. Agents using genai.Part as content representation may need to keep track of the additional information. For example it can be name of a file/source from which the Part originates or a way to multiplex multiple Part streams.',
          additionalProperties: {
            type: 'any',
            description: 'Properties of the object.',
          },
        },
        functionCall: { $ref: '#/$defs/FunctionCall' },
        toolResponse: { $ref: '#/$defs/ToolResponse' },
        inlineData: { $ref: '#/$defs/Blob' },
        codeExecutionResult: { $ref: '#/$defs/CodeExecutionResult' },
        toolCall: { $ref: '#/$defs/ToolCall' },
        thoughtSignature: {
          type: 'string',
          format: 'byte',
          description:
            'Optional. An opaque signature for the thought so it can be reused in subsequent requests.',
        },
      },
    },
    ToolCall: {
      type: 'object',
      description:
        'A predicted server-side `ToolCall` returned from the model. This message contains information about a tool that the model wants to invoke. The client is NOT expected to execute this `ToolCall`. Instead, the client should pass this `ToolCall` back to the API in a subsequent turn within a `Content` message, along with the corresponding `ToolResponse`.',
      properties: {
        id: {
          type: 'string',
          description:
            'Optional. Unique identifier of the tool call. The server returns the tool response with the matching `id`.',
        },
        toolType: {
          type: 'string',
          description: 'Required. The type of tool that was called.',
          enum: [
            'TOOL_TYPE_UNSPECIFIED',
            'GOOGLE_SEARCH_WEB',
            'GOOGLE_SEARCH_IMAGE',
            'URL_CONTEXT',
            'GOOGLE_MAPS',
            'FILE_SEARCH',
          ],
        },
        args: {
          type: 'object',
          description:
            'Optional. The tool call arguments. Example: {"arg1" : "value1", "arg2" : "value2" , ...}',
          additionalProperties: {
            type: 'any',
            description: 'Properties of the object.',
          },
        },
      },
    },
    ToolResponse: {
      type: 'object',
      description:
        'The output from a server-side `ToolCall` execution. This message contains the results of a tool invocation that was initiated by a `ToolCall` from the model. The client should pass this `ToolResponse` back to the API in a subsequent turn within a `Content` message, along with the corresponding `ToolCall`.',
      properties: {
        id: {
          type: 'string',
          description:
            'Optional. The identifier of the tool call this response is for.',
        },
        toolType: {
          type: 'string',
          description:
            'Required. The type of tool that was called, matching the `tool_type` in the corresponding `ToolCall`.',
          enum: [
            'TOOL_TYPE_UNSPECIFIED',
            'GOOGLE_SEARCH_WEB',
            'GOOGLE_SEARCH_IMAGE',
            'URL_CONTEXT',
            'GOOGLE_MAPS',
            'FILE_SEARCH',
          ],
        },
        response: {
          type: 'object',
          description: 'Optional. The tool response.',
          additionalProperties: {
            type: 'any',
            description: 'Properties of the object.',
          },
        },
      },
    },
    VideoMetadata: {
      type: 'object',
      description:
        'Deprecated: Use `GenerateContentRequest.processing_options` instead. Metadata describes the input video content.',
      properties: {
        startOffset: {
          type: 'string',
          format: 'google-duration',
          description: 'Optional. The start offset of the video.',
        },
        endOffset: {
          type: 'string',
          format: 'google-duration',
          description: 'Optional. The end offset of the video.',
        },
        fps: {
          type: 'number',
          format: 'double',
          description:
            'Optional. The frame rate of the video sent to the model. If not specified, the default value will be 1.0. The fps range is (0.0, 24.0].',
        },
      },
    },
  },
} as const

export const ContentEmbeddingSchema = {
  type: 'object',
  description: 'A list of floats representing an embedding.',
  properties: {
    values: {
      type: 'array',
      description:
        'The embedding values. This is for 3P users only and will not be populated for 1P calls.',
      items: { type: 'number', format: 'float' },
    },
    shape: {
      type: 'array',
      description:
        'This field stores the soft tokens tensor frame shape (e.g. [1, 1, 256, 2048]).',
      items: { type: 'integer', format: 'int32' },
    },
  },
} as const

export const EmbedContentConfigSchema = {
  type: 'object',
  description: 'Configurations for the EmbedContent request.',
  properties: {
    documentOcr: {
      type: 'boolean',
      description: 'Optional. Whether to enable OCR for document content.',
    },
    audioTrackExtraction: {
      type: 'boolean',
      description: 'Optional. Whether to extract audio from video content.',
    },
    taskType: {
      type: 'string',
      description: 'Optional. The task type of the embedding.',
      enum: [
        'TASK_TYPE_UNSPECIFIED',
        'RETRIEVAL_QUERY',
        'RETRIEVAL_DOCUMENT',
        'SEMANTIC_SIMILARITY',
        'CLASSIFICATION',
        'CLUSTERING',
        'QUESTION_ANSWERING',
        'FACT_VERIFICATION',
        'CODE_RETRIEVAL_QUERY',
      ],
    },
    outputDimensionality: {
      type: 'integer',
      format: 'int32',
      description:
        'Optional. Reduced dimension for the output embedding. If set, excessive values in the output embedding are truncated from the end.',
    },
    title: { type: 'string', description: 'Optional. The title for the text.' },
    autoTruncate: {
      type: 'boolean',
      description:
        "Optional. Whether to silently truncate the input content if it's longer than the maximum sequence length.",
    },
  },
} as const

export const EmbedContentRequestSchema = {
  type: 'object',
  description: 'Request containing the `Content` for the model to embed.',
  properties: {
    title: {
      type: 'string',
      description:
        'Optional. Deprecated: Please use EmbedContentConfig.title instead. An optional title for the text. Only applicable when TaskType is `RETRIEVAL_DOCUMENT`. Note: Specifying a `title` for `RETRIEVAL_DOCUMENT` provides better quality embeddings for retrieval.',
    },
    content: { $ref: '#/$defs/Content' },
    taskType: {
      type: 'string',
      description:
        'Optional. Deprecated: Please use EmbedContentConfig.task_type instead. Optional task type for which the embeddings will be used. Not supported on earlier models (`models/embedding-001`).',
      enum: [
        'TASK_TYPE_UNSPECIFIED',
        'RETRIEVAL_QUERY',
        'RETRIEVAL_DOCUMENT',
        'SEMANTIC_SIMILARITY',
        'CLASSIFICATION',
        'CLUSTERING',
        'QUESTION_ANSWERING',
        'FACT_VERIFICATION',
        'CODE_RETRIEVAL_QUERY',
      ],
    },
    outputDimensionality: {
      type: 'integer',
      format: 'int32',
      description:
        'Optional. Deprecated: Please use EmbedContentConfig.output_dimensionality instead. Optional reduced dimension for the output embedding. If set, excessive values in the output embedding are truncated from the end. Supported by newer models since 2024 only. You cannot set this value if using the earlier model (`models/embedding-001`).',
    },
    model: {
      type: 'string',
      description:
        "Required. The model's resource name. This serves as an ID for the Model to use. This name should match a model name returned by the `ListModels` method. Format: `models/{model}`",
    },
    embedContentConfig: { $ref: '#/$defs/EmbedContentConfig' },
  },
  $defs: {
    Blob: {
      type: 'object',
      description:
        "Raw media bytes. Text should not be sent as raw bytes, use the 'text' field.",
      properties: {
        mimeType: {
          type: 'string',
          description:
            'The IANA standard MIME type of the source data. Examples of supported types: - Images: image/png, image/jpeg, image/jpg, image/webp, image/heic, image/heif, image/gif, image/avif - Audio: audio/*, video/audio/s16le, video/audio/wav - Video: video/* - Text: text/plain, text/html, text/css, text/javascript, text/x-typescript, text/csv, text/markdown, text/x-python, text/xml, text/rtf, video/text/timestamp - Applications: application/x-javascript, application/x-typescript, application/x-python-code, application/json, application/x-ipynb+json, application/rtf, application/pdf For additional context, see [Supported file formats](https://ai.google.dev/gemini-api/docs/file-input-methods#supported-content-types). //',
        },
        data: {
          type: 'string',
          format: 'byte',
          description: 'Raw bytes for media formats.',
        },
      },
    },
    CodeExecutionResult: {
      type: 'object',
      description:
        'Result of executing the `ExecutableCode`. Generated only when the `CodeExecution` tool is used.',
      properties: {
        output: {
          type: 'string',
          description:
            'Optional. Contains stdout when code execution is successful, stderr or other description otherwise.',
        },
        outcome: {
          type: 'string',
          description: 'Required. Outcome of the code execution.',
          enum: [
            'OUTCOME_UNSPECIFIED',
            'OUTCOME_OK',
            'OUTCOME_FAILED',
            'OUTCOME_DEADLINE_EXCEEDED',
          ],
        },
        id: {
          type: 'string',
          description:
            'Optional. The identifier of the `ExecutableCode` part this result is for. Only populated if the corresponding `ExecutableCode` has an id.',
        },
      },
    },
    Content: {
      type: 'object',
      description:
        'The base structured datatype containing multi-part content of a message. A `Content` includes a `role` field designating the producer of the `Content` and a `parts` field containing multi-part data that contains the content of the message turn.',
      properties: {
        role: {
          type: 'string',
          description:
            "Optional. The producer of the content. Must be either 'user' or 'model'. Useful to set for multi-turn conversations, otherwise can be left blank or unset.",
        },
        parts: {
          type: 'array',
          description:
            'Ordered `Parts` that constitute a single message. Parts may have different MIME types.',
          items: { $ref: '#/$defs/Part' },
        },
      },
    },
    EmbedContentConfig: {
      type: 'object',
      description: 'Configurations for the EmbedContent request.',
      properties: {
        documentOcr: {
          type: 'boolean',
          description: 'Optional. Whether to enable OCR for document content.',
        },
        audioTrackExtraction: {
          type: 'boolean',
          description: 'Optional. Whether to extract audio from video content.',
        },
        taskType: {
          type: 'string',
          description: 'Optional. The task type of the embedding.',
          enum: [
            'TASK_TYPE_UNSPECIFIED',
            'RETRIEVAL_QUERY',
            'RETRIEVAL_DOCUMENT',
            'SEMANTIC_SIMILARITY',
            'CLASSIFICATION',
            'CLUSTERING',
            'QUESTION_ANSWERING',
            'FACT_VERIFICATION',
            'CODE_RETRIEVAL_QUERY',
          ],
        },
        outputDimensionality: {
          type: 'integer',
          format: 'int32',
          description:
            'Optional. Reduced dimension for the output embedding. If set, excessive values in the output embedding are truncated from the end.',
        },
        title: {
          type: 'string',
          description: 'Optional. The title for the text.',
        },
        autoTruncate: {
          type: 'boolean',
          description:
            "Optional. Whether to silently truncate the input content if it's longer than the maximum sequence length.",
        },
      },
    },
    ExecutableCode: {
      type: 'object',
      description:
        'Code generated by the model that is meant to be executed, and the result returned to the model. Only generated when using the `CodeExecution` tool, in which the code will be automatically executed, and a corresponding `CodeExecutionResult` will also be generated.',
      properties: {
        language: {
          type: 'string',
          description: 'Required. Programming language of the `code`.',
          enum: ['LANGUAGE_UNSPECIFIED', 'PYTHON'],
        },
        code: {
          type: 'string',
          description: 'Required. The code to be executed.',
        },
        id: {
          type: 'string',
          description:
            'Optional. Unique identifier of the `ExecutableCode` part. The server returns the `CodeExecutionResult` with the matching `id`.',
        },
      },
    },
    FileData: {
      type: 'object',
      description: 'URI based data.',
      properties: {
        mimeType: {
          type: 'string',
          description:
            'Optional. The IANA standard MIME type of the source data.',
        },
        fileUri: { type: 'string', description: 'Required. URI.' },
      },
    },
    FunctionCall: {
      type: 'object',
      description:
        'A predicted `FunctionCall` returned from the model that contains a string representing the `FunctionDeclaration.name` with the arguments and their values.',
      properties: {
        id: {
          type: 'string',
          description:
            'Optional. Unique identifier of the function call. If populated, the client to execute the `function_call` and return the response with the matching `id`.',
        },
        name: {
          type: 'string',
          description:
            'Required. The name of the function to call. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 128.',
        },
        args: {
          type: 'object',
          description:
            'Optional. The function parameters and values in JSON object format.',
          additionalProperties: {
            type: 'any',
            description: 'Properties of the object.',
          },
        },
      },
    },
    FunctionResponse: {
      type: 'object',
      description:
        'The result output from a `FunctionCall` that contains a string representing the `FunctionDeclaration.name` and a structured JSON object containing any output from the function is used as context to the model. This should contain the result of a`FunctionCall` made based on model prediction.',
      properties: {
        id: {
          type: 'string',
          description:
            'Optional. The identifier of the function call this response is for. Populated by the client to match the corresponding function call `id`.',
        },
        scheduling: {
          type: 'string',
          description:
            'Optional. Specifies how the response should be scheduled in the conversation. Only applicable to NON_BLOCKING function calls, is ignored otherwise. Defaults to WHEN_IDLE.',
          enum: ['SCHEDULING_UNSPECIFIED', 'SILENT', 'WHEN_IDLE', 'INTERRUPT'],
        },
        willContinue: {
          type: 'boolean',
          description:
            'Optional. Signals that function call continues, and more responses will be returned, turning the function call into a generator. Is only applicable to NON_BLOCKING function calls, is ignored otherwise. If set to false, future responses will not be considered. It is allowed to return empty `response` with `will_continue=False` to signal that the function call is finished. This may still trigger the model generation. To avoid triggering the generation and finish the function call, additionally set `scheduling` to `SILENT`.',
        },
        name: {
          type: 'string',
          description:
            'Required. The name of the function to call. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 128.',
        },
        response: {
          type: 'object',
          description:
            'Required. The function response in JSON object format. Callers can use any keys of their choice that fit the function\'s syntax to return the function output, e.g. "output", "result", etc. In particular, if the function call failed to execute, the response can have an "error" key to return error details to the model. Multimedia can be included by using a subobject containing a single "$ref" key whose value is the `inline_data.display_name` of a `FunctionResponsePart` holding the multimedia. See https://ai.google.dev/gemini-api/docs/function-calling#multimodal.',
          additionalProperties: {
            type: 'any',
            description: 'Properties of the object.',
          },
        },
        parts: {
          type: 'array',
          description:
            'Optional. Ordered `Parts` that constitute a function response. Parts may have different IANA MIME types.',
          items: { $ref: '#/$defs/FunctionResponsePart' },
        },
      },
    },
    FunctionResponseBlob: {
      type: 'object',
      description:
        "Raw media bytes for function response. Text should not be sent as raw bytes, use the 'FunctionResponse.response' field.",
      properties: {
        mimeType: {
          type: 'string',
          description:
            'The IANA standard MIME type of the source data. Examples: - image/png - image/jpeg If an unsupported MIME type is provided, an error will be returned. For a complete list of supported types, see [Supported file formats](https://ai.google.dev/gemini-api/docs/prompting_with_media#supported_file_formats).',
        },
        data: {
          type: 'string',
          format: 'byte',
          description: 'Raw bytes for media formats.',
        },
      },
    },
    FunctionResponsePart: {
      type: 'object',
      description:
        'A datatype containing media that is part of a `FunctionResponse` message. A `FunctionResponsePart` consists of data which has an associated datatype. A `FunctionResponsePart` can only contain one of the accepted types in `FunctionResponsePart.data`. A `FunctionResponsePart` must have a fixed IANA MIME type identifying the type and subtype of the media if the `inline_data` field is filled with raw bytes.',
      properties: { inlineData: { $ref: '#/$defs/FunctionResponseBlob' } },
    },
    MediaResolution: {
      type: 'object',
      description:
        'Schema referenced but not defined upstream (missing from source OpenAPI spec)',
      additionalProperties: true,
    },
    Part: {
      type: 'object',
      description:
        'A datatype containing media that is part of a multi-part `Content` message. A `Part` consists of data which has an associated datatype. A `Part` can only contain one of the accepted types in `Part.data`. A `Part` must have a fixed IANA MIME type identifying the type and subtype of the media if the `inline_data` field is filled with raw bytes.',
      properties: {
        videoMetadata: { $ref: '#/$defs/VideoMetadata' },
        text: { type: 'string', description: 'Inline text.' },
        executableCode: { $ref: '#/$defs/ExecutableCode' },
        functionResponse: { $ref: '#/$defs/FunctionResponse' },
        thought: {
          type: 'boolean',
          description:
            'Optional. Indicates if the part is thought from the model.',
        },
        mediaResolution: { $ref: '#/$defs/MediaResolution' },
        fileData: { $ref: '#/$defs/FileData' },
        partMetadata: {
          type: 'object',
          description:
            'Custom metadata associated with the Part. Agents using genai.Part as content representation may need to keep track of the additional information. For example it can be name of a file/source from which the Part originates or a way to multiplex multiple Part streams.',
          additionalProperties: {
            type: 'any',
            description: 'Properties of the object.',
          },
        },
        functionCall: { $ref: '#/$defs/FunctionCall' },
        toolResponse: { $ref: '#/$defs/ToolResponse' },
        inlineData: { $ref: '#/$defs/Blob' },
        codeExecutionResult: { $ref: '#/$defs/CodeExecutionResult' },
        toolCall: { $ref: '#/$defs/ToolCall' },
        thoughtSignature: {
          type: 'string',
          format: 'byte',
          description:
            'Optional. An opaque signature for the thought so it can be reused in subsequent requests.',
        },
      },
    },
    ToolCall: {
      type: 'object',
      description:
        'A predicted server-side `ToolCall` returned from the model. This message contains information about a tool that the model wants to invoke. The client is NOT expected to execute this `ToolCall`. Instead, the client should pass this `ToolCall` back to the API in a subsequent turn within a `Content` message, along with the corresponding `ToolResponse`.',
      properties: {
        id: {
          type: 'string',
          description:
            'Optional. Unique identifier of the tool call. The server returns the tool response with the matching `id`.',
        },
        toolType: {
          type: 'string',
          description: 'Required. The type of tool that was called.',
          enum: [
            'TOOL_TYPE_UNSPECIFIED',
            'GOOGLE_SEARCH_WEB',
            'GOOGLE_SEARCH_IMAGE',
            'URL_CONTEXT',
            'GOOGLE_MAPS',
            'FILE_SEARCH',
          ],
        },
        args: {
          type: 'object',
          description:
            'Optional. The tool call arguments. Example: {"arg1" : "value1", "arg2" : "value2" , ...}',
          additionalProperties: {
            type: 'any',
            description: 'Properties of the object.',
          },
        },
      },
    },
    ToolResponse: {
      type: 'object',
      description:
        'The output from a server-side `ToolCall` execution. This message contains the results of a tool invocation that was initiated by a `ToolCall` from the model. The client should pass this `ToolResponse` back to the API in a subsequent turn within a `Content` message, along with the corresponding `ToolCall`.',
      properties: {
        id: {
          type: 'string',
          description:
            'Optional. The identifier of the tool call this response is for.',
        },
        toolType: {
          type: 'string',
          description:
            'Required. The type of tool that was called, matching the `tool_type` in the corresponding `ToolCall`.',
          enum: [
            'TOOL_TYPE_UNSPECIFIED',
            'GOOGLE_SEARCH_WEB',
            'GOOGLE_SEARCH_IMAGE',
            'URL_CONTEXT',
            'GOOGLE_MAPS',
            'FILE_SEARCH',
          ],
        },
        response: {
          type: 'object',
          description: 'Optional. The tool response.',
          additionalProperties: {
            type: 'any',
            description: 'Properties of the object.',
          },
        },
      },
    },
    VideoMetadata: {
      type: 'object',
      description:
        'Deprecated: Use `GenerateContentRequest.processing_options` instead. Metadata describes the input video content.',
      properties: {
        startOffset: {
          type: 'string',
          format: 'google-duration',
          description: 'Optional. The start offset of the video.',
        },
        endOffset: {
          type: 'string',
          format: 'google-duration',
          description: 'Optional. The end offset of the video.',
        },
        fps: {
          type: 'number',
          format: 'double',
          description:
            'Optional. The frame rate of the video sent to the model. If not specified, the default value will be 1.0. The fps range is (0.0, 24.0].',
        },
      },
    },
  },
} as const

export const EmbedContentResponseSchema = {
  type: 'object',
  description: 'The response to an `EmbedContentRequest`.',
  properties: {
    usageMetadata: { $ref: '#/$defs/EmbeddingUsageMetadata' },
    embedding: { $ref: '#/$defs/ContentEmbedding' },
  },
  $defs: {
    ContentEmbedding: {
      type: 'object',
      description: 'A list of floats representing an embedding.',
      properties: {
        values: {
          type: 'array',
          description:
            'The embedding values. This is for 3P users only and will not be populated for 1P calls.',
          items: { type: 'number', format: 'float' },
        },
        shape: {
          type: 'array',
          description:
            'This field stores the soft tokens tensor frame shape (e.g. [1, 1, 256, 2048]).',
          items: { type: 'integer', format: 'int32' },
        },
      },
    },
    EmbeddingUsageMetadata: {
      type: 'object',
      description: 'Metadata on the usage of the embedding request.',
      properties: {
        promptTokenDetails: {
          type: 'array',
          description:
            'Output only. List of modalities that were processed in the request input.',
          items: { $ref: '#/$defs/ModalityTokenCount' },
        },
        promptTokenCount: {
          type: 'integer',
          format: 'int32',
          description: 'Output only. Number of tokens in the prompt.',
        },
      },
    },
    ModalityTokenCount: {
      type: 'object',
      description: 'Represents token counting info for a single modality.',
      properties: {
        modality: {
          type: 'string',
          description: 'The modality associated with this token count.',
          enum: [
            'MODALITY_UNSPECIFIED',
            'TEXT',
            'IMAGE',
            'VIDEO',
            'AUDIO',
            'DOCUMENT',
          ],
        },
        tokenCount: {
          type: 'integer',
          format: 'int32',
          description: 'Number of tokens.',
        },
      },
    },
  },
} as const

export const EmbedTextRequestSchema = {
  type: 'object',
  description: 'Request to get a text embedding from the model.',
  properties: {
    model: {
      type: 'string',
      description:
        'Required. The model name to use with the format model=models/{model}.',
    },
    text: {
      type: 'string',
      description:
        'Optional. The free-form input text that the model will turn into an embedding.',
    },
  },
} as const

export const EmbedTextResponseSchema = {
  type: 'object',
  description: 'The response to a EmbedTextRequest.',
  properties: { embedding: { $ref: '#/$defs/Embedding' } },
  $defs: {
    Embedding: {
      type: 'object',
      description: 'A list of floats representing the embedding.',
      properties: {
        value: {
          type: 'array',
          description: 'The embedding values.',
          items: { type: 'number', format: 'float' },
        },
      },
    },
  },
} as const

export const EmbeddingSchema = {
  type: 'object',
  description: 'A list of floats representing the embedding.',
  properties: {
    value: {
      type: 'array',
      description: 'The embedding values.',
      items: { type: 'number', format: 'float' },
    },
  },
} as const

export const EmbeddingUsageMetadataSchema = {
  type: 'object',
  description: 'Metadata on the usage of the embedding request.',
  properties: {
    promptTokenDetails: {
      type: 'array',
      description:
        'Output only. List of modalities that were processed in the request input.',
      items: { $ref: '#/$defs/ModalityTokenCount' },
    },
    promptTokenCount: {
      type: 'integer',
      format: 'int32',
      description: 'Output only. Number of tokens in the prompt.',
    },
  },
  $defs: {
    ModalityTokenCount: {
      type: 'object',
      description: 'Represents token counting info for a single modality.',
      properties: {
        modality: {
          type: 'string',
          description: 'The modality associated with this token count.',
          enum: [
            'MODALITY_UNSPECIFIED',
            'TEXT',
            'IMAGE',
            'VIDEO',
            'AUDIO',
            'DOCUMENT',
          ],
        },
        tokenCount: {
          type: 'integer',
          format: 'int32',
          description: 'Number of tokens.',
        },
      },
    },
  },
} as const

export const ExecutableCodeSchema = {
  type: 'object',
  description:
    'Code generated by the model that is meant to be executed, and the result returned to the model. Only generated when using the `CodeExecution` tool, in which the code will be automatically executed, and a corresponding `CodeExecutionResult` will also be generated.',
  properties: {
    language: {
      type: 'string',
      description: 'Required. Programming language of the `code`.',
      enum: ['LANGUAGE_UNSPECIFIED', 'PYTHON'],
    },
    code: { type: 'string', description: 'Required. The code to be executed.' },
    id: {
      type: 'string',
      description:
        'Optional. Unique identifier of the `ExecutableCode` part. The server returns the `CodeExecutionResult` with the matching `id`.',
    },
  },
} as const

export const FileDataSchema = {
  type: 'object',
  description: 'URI based data.',
  properties: {
    mimeType: {
      type: 'string',
      description: 'Optional. The IANA standard MIME type of the source data.',
    },
    fileUri: { type: 'string', description: 'Required. URI.' },
  },
} as const

export const FunctionCallSchema = {
  type: 'object',
  description:
    'A predicted `FunctionCall` returned from the model that contains a string representing the `FunctionDeclaration.name` with the arguments and their values.',
  properties: {
    id: {
      type: 'string',
      description:
        'Optional. Unique identifier of the function call. If populated, the client to execute the `function_call` and return the response with the matching `id`.',
    },
    name: {
      type: 'string',
      description:
        'Required. The name of the function to call. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 128.',
    },
    args: {
      type: 'object',
      description:
        'Optional. The function parameters and values in JSON object format.',
      additionalProperties: {
        type: 'any',
        description: 'Properties of the object.',
      },
    },
  },
} as const

export const FunctionResponseSchema = {
  type: 'object',
  description:
    'The result output from a `FunctionCall` that contains a string representing the `FunctionDeclaration.name` and a structured JSON object containing any output from the function is used as context to the model. This should contain the result of a`FunctionCall` made based on model prediction.',
  properties: {
    id: {
      type: 'string',
      description:
        'Optional. The identifier of the function call this response is for. Populated by the client to match the corresponding function call `id`.',
    },
    scheduling: {
      type: 'string',
      description:
        'Optional. Specifies how the response should be scheduled in the conversation. Only applicable to NON_BLOCKING function calls, is ignored otherwise. Defaults to WHEN_IDLE.',
      enum: ['SCHEDULING_UNSPECIFIED', 'SILENT', 'WHEN_IDLE', 'INTERRUPT'],
    },
    willContinue: {
      type: 'boolean',
      description:
        'Optional. Signals that function call continues, and more responses will be returned, turning the function call into a generator. Is only applicable to NON_BLOCKING function calls, is ignored otherwise. If set to false, future responses will not be considered. It is allowed to return empty `response` with `will_continue=False` to signal that the function call is finished. This may still trigger the model generation. To avoid triggering the generation and finish the function call, additionally set `scheduling` to `SILENT`.',
    },
    name: {
      type: 'string',
      description:
        'Required. The name of the function to call. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 128.',
    },
    response: {
      type: 'object',
      description:
        'Required. The function response in JSON object format. Callers can use any keys of their choice that fit the function\'s syntax to return the function output, e.g. "output", "result", etc. In particular, if the function call failed to execute, the response can have an "error" key to return error details to the model. Multimedia can be included by using a subobject containing a single "$ref" key whose value is the `inline_data.display_name` of a `FunctionResponsePart` holding the multimedia. See https://ai.google.dev/gemini-api/docs/function-calling#multimodal.',
      additionalProperties: {
        type: 'any',
        description: 'Properties of the object.',
      },
    },
    parts: {
      type: 'array',
      description:
        'Optional. Ordered `Parts` that constitute a function response. Parts may have different IANA MIME types.',
      items: { $ref: '#/$defs/FunctionResponsePart' },
    },
  },
  $defs: {
    FunctionResponseBlob: {
      type: 'object',
      description:
        "Raw media bytes for function response. Text should not be sent as raw bytes, use the 'FunctionResponse.response' field.",
      properties: {
        mimeType: {
          type: 'string',
          description:
            'The IANA standard MIME type of the source data. Examples: - image/png - image/jpeg If an unsupported MIME type is provided, an error will be returned. For a complete list of supported types, see [Supported file formats](https://ai.google.dev/gemini-api/docs/prompting_with_media#supported_file_formats).',
        },
        data: {
          type: 'string',
          format: 'byte',
          description: 'Raw bytes for media formats.',
        },
      },
    },
    FunctionResponsePart: {
      type: 'object',
      description:
        'A datatype containing media that is part of a `FunctionResponse` message. A `FunctionResponsePart` consists of data which has an associated datatype. A `FunctionResponsePart` can only contain one of the accepted types in `FunctionResponsePart.data`. A `FunctionResponsePart` must have a fixed IANA MIME type identifying the type and subtype of the media if the `inline_data` field is filled with raw bytes.',
      properties: { inlineData: { $ref: '#/$defs/FunctionResponseBlob' } },
    },
  },
} as const

export const FunctionResponseBlobSchema = {
  type: 'object',
  description:
    "Raw media bytes for function response. Text should not be sent as raw bytes, use the 'FunctionResponse.response' field.",
  properties: {
    mimeType: {
      type: 'string',
      description:
        'The IANA standard MIME type of the source data. Examples: - image/png - image/jpeg If an unsupported MIME type is provided, an error will be returned. For a complete list of supported types, see [Supported file formats](https://ai.google.dev/gemini-api/docs/prompting_with_media#supported_file_formats).',
    },
    data: {
      type: 'string',
      format: 'byte',
      description: 'Raw bytes for media formats.',
    },
  },
} as const

export const FunctionResponsePartSchema = {
  type: 'object',
  description:
    'A datatype containing media that is part of a `FunctionResponse` message. A `FunctionResponsePart` consists of data which has an associated datatype. A `FunctionResponsePart` can only contain one of the accepted types in `FunctionResponsePart.data`. A `FunctionResponsePart` must have a fixed IANA MIME type identifying the type and subtype of the media if the `inline_data` field is filled with raw bytes.',
  properties: { inlineData: { $ref: '#/$defs/FunctionResponseBlob' } },
  $defs: {
    FunctionResponseBlob: {
      type: 'object',
      description:
        "Raw media bytes for function response. Text should not be sent as raw bytes, use the 'FunctionResponse.response' field.",
      properties: {
        mimeType: {
          type: 'string',
          description:
            'The IANA standard MIME type of the source data. Examples: - image/png - image/jpeg If an unsupported MIME type is provided, an error will be returned. For a complete list of supported types, see [Supported file formats](https://ai.google.dev/gemini-api/docs/prompting_with_media#supported_file_formats).',
        },
        data: {
          type: 'string',
          format: 'byte',
          description: 'Raw bytes for media formats.',
        },
      },
    },
  },
} as const

export const MediaResolutionSchema = {
  type: 'object',
  description:
    'Schema referenced but not defined upstream (missing from source OpenAPI spec)',
  additionalProperties: true,
} as const

export const ModalityTokenCountSchema = {
  type: 'object',
  description: 'Represents token counting info for a single modality.',
  properties: {
    modality: {
      type: 'string',
      description: 'The modality associated with this token count.',
      enum: [
        'MODALITY_UNSPECIFIED',
        'TEXT',
        'IMAGE',
        'VIDEO',
        'AUDIO',
        'DOCUMENT',
      ],
    },
    tokenCount: {
      type: 'integer',
      format: 'int32',
      description: 'Number of tokens.',
    },
  },
} as const

export const PartSchema = {
  type: 'object',
  description:
    'A datatype containing media that is part of a multi-part `Content` message. A `Part` consists of data which has an associated datatype. A `Part` can only contain one of the accepted types in `Part.data`. A `Part` must have a fixed IANA MIME type identifying the type and subtype of the media if the `inline_data` field is filled with raw bytes.',
  properties: {
    videoMetadata: { $ref: '#/$defs/VideoMetadata' },
    text: { type: 'string', description: 'Inline text.' },
    executableCode: { $ref: '#/$defs/ExecutableCode' },
    functionResponse: { $ref: '#/$defs/FunctionResponse' },
    thought: {
      type: 'boolean',
      description: 'Optional. Indicates if the part is thought from the model.',
    },
    mediaResolution: { $ref: '#/$defs/MediaResolution' },
    fileData: { $ref: '#/$defs/FileData' },
    partMetadata: {
      type: 'object',
      description:
        'Custom metadata associated with the Part. Agents using genai.Part as content representation may need to keep track of the additional information. For example it can be name of a file/source from which the Part originates or a way to multiplex multiple Part streams.',
      additionalProperties: {
        type: 'any',
        description: 'Properties of the object.',
      },
    },
    functionCall: { $ref: '#/$defs/FunctionCall' },
    toolResponse: { $ref: '#/$defs/ToolResponse' },
    inlineData: { $ref: '#/$defs/Blob' },
    codeExecutionResult: { $ref: '#/$defs/CodeExecutionResult' },
    toolCall: { $ref: '#/$defs/ToolCall' },
    thoughtSignature: {
      type: 'string',
      format: 'byte',
      description:
        'Optional. An opaque signature for the thought so it can be reused in subsequent requests.',
    },
  },
  $defs: {
    Blob: {
      type: 'object',
      description:
        "Raw media bytes. Text should not be sent as raw bytes, use the 'text' field.",
      properties: {
        mimeType: {
          type: 'string',
          description:
            'The IANA standard MIME type of the source data. Examples of supported types: - Images: image/png, image/jpeg, image/jpg, image/webp, image/heic, image/heif, image/gif, image/avif - Audio: audio/*, video/audio/s16le, video/audio/wav - Video: video/* - Text: text/plain, text/html, text/css, text/javascript, text/x-typescript, text/csv, text/markdown, text/x-python, text/xml, text/rtf, video/text/timestamp - Applications: application/x-javascript, application/x-typescript, application/x-python-code, application/json, application/x-ipynb+json, application/rtf, application/pdf For additional context, see [Supported file formats](https://ai.google.dev/gemini-api/docs/file-input-methods#supported-content-types). //',
        },
        data: {
          type: 'string',
          format: 'byte',
          description: 'Raw bytes for media formats.',
        },
      },
    },
    CodeExecutionResult: {
      type: 'object',
      description:
        'Result of executing the `ExecutableCode`. Generated only when the `CodeExecution` tool is used.',
      properties: {
        output: {
          type: 'string',
          description:
            'Optional. Contains stdout when code execution is successful, stderr or other description otherwise.',
        },
        outcome: {
          type: 'string',
          description: 'Required. Outcome of the code execution.',
          enum: [
            'OUTCOME_UNSPECIFIED',
            'OUTCOME_OK',
            'OUTCOME_FAILED',
            'OUTCOME_DEADLINE_EXCEEDED',
          ],
        },
        id: {
          type: 'string',
          description:
            'Optional. The identifier of the `ExecutableCode` part this result is for. Only populated if the corresponding `ExecutableCode` has an id.',
        },
      },
    },
    ExecutableCode: {
      type: 'object',
      description:
        'Code generated by the model that is meant to be executed, and the result returned to the model. Only generated when using the `CodeExecution` tool, in which the code will be automatically executed, and a corresponding `CodeExecutionResult` will also be generated.',
      properties: {
        language: {
          type: 'string',
          description: 'Required. Programming language of the `code`.',
          enum: ['LANGUAGE_UNSPECIFIED', 'PYTHON'],
        },
        code: {
          type: 'string',
          description: 'Required. The code to be executed.',
        },
        id: {
          type: 'string',
          description:
            'Optional. Unique identifier of the `ExecutableCode` part. The server returns the `CodeExecutionResult` with the matching `id`.',
        },
      },
    },
    FileData: {
      type: 'object',
      description: 'URI based data.',
      properties: {
        mimeType: {
          type: 'string',
          description:
            'Optional. The IANA standard MIME type of the source data.',
        },
        fileUri: { type: 'string', description: 'Required. URI.' },
      },
    },
    FunctionCall: {
      type: 'object',
      description:
        'A predicted `FunctionCall` returned from the model that contains a string representing the `FunctionDeclaration.name` with the arguments and their values.',
      properties: {
        id: {
          type: 'string',
          description:
            'Optional. Unique identifier of the function call. If populated, the client to execute the `function_call` and return the response with the matching `id`.',
        },
        name: {
          type: 'string',
          description:
            'Required. The name of the function to call. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 128.',
        },
        args: {
          type: 'object',
          description:
            'Optional. The function parameters and values in JSON object format.',
          additionalProperties: {
            type: 'any',
            description: 'Properties of the object.',
          },
        },
      },
    },
    FunctionResponse: {
      type: 'object',
      description:
        'The result output from a `FunctionCall` that contains a string representing the `FunctionDeclaration.name` and a structured JSON object containing any output from the function is used as context to the model. This should contain the result of a`FunctionCall` made based on model prediction.',
      properties: {
        id: {
          type: 'string',
          description:
            'Optional. The identifier of the function call this response is for. Populated by the client to match the corresponding function call `id`.',
        },
        scheduling: {
          type: 'string',
          description:
            'Optional. Specifies how the response should be scheduled in the conversation. Only applicable to NON_BLOCKING function calls, is ignored otherwise. Defaults to WHEN_IDLE.',
          enum: ['SCHEDULING_UNSPECIFIED', 'SILENT', 'WHEN_IDLE', 'INTERRUPT'],
        },
        willContinue: {
          type: 'boolean',
          description:
            'Optional. Signals that function call continues, and more responses will be returned, turning the function call into a generator. Is only applicable to NON_BLOCKING function calls, is ignored otherwise. If set to false, future responses will not be considered. It is allowed to return empty `response` with `will_continue=False` to signal that the function call is finished. This may still trigger the model generation. To avoid triggering the generation and finish the function call, additionally set `scheduling` to `SILENT`.',
        },
        name: {
          type: 'string',
          description:
            'Required. The name of the function to call. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 128.',
        },
        response: {
          type: 'object',
          description:
            'Required. The function response in JSON object format. Callers can use any keys of their choice that fit the function\'s syntax to return the function output, e.g. "output", "result", etc. In particular, if the function call failed to execute, the response can have an "error" key to return error details to the model. Multimedia can be included by using a subobject containing a single "$ref" key whose value is the `inline_data.display_name` of a `FunctionResponsePart` holding the multimedia. See https://ai.google.dev/gemini-api/docs/function-calling#multimodal.',
          additionalProperties: {
            type: 'any',
            description: 'Properties of the object.',
          },
        },
        parts: {
          type: 'array',
          description:
            'Optional. Ordered `Parts` that constitute a function response. Parts may have different IANA MIME types.',
          items: { $ref: '#/$defs/FunctionResponsePart' },
        },
      },
    },
    FunctionResponseBlob: {
      type: 'object',
      description:
        "Raw media bytes for function response. Text should not be sent as raw bytes, use the 'FunctionResponse.response' field.",
      properties: {
        mimeType: {
          type: 'string',
          description:
            'The IANA standard MIME type of the source data. Examples: - image/png - image/jpeg If an unsupported MIME type is provided, an error will be returned. For a complete list of supported types, see [Supported file formats](https://ai.google.dev/gemini-api/docs/prompting_with_media#supported_file_formats).',
        },
        data: {
          type: 'string',
          format: 'byte',
          description: 'Raw bytes for media formats.',
        },
      },
    },
    FunctionResponsePart: {
      type: 'object',
      description:
        'A datatype containing media that is part of a `FunctionResponse` message. A `FunctionResponsePart` consists of data which has an associated datatype. A `FunctionResponsePart` can only contain one of the accepted types in `FunctionResponsePart.data`. A `FunctionResponsePart` must have a fixed IANA MIME type identifying the type and subtype of the media if the `inline_data` field is filled with raw bytes.',
      properties: { inlineData: { $ref: '#/$defs/FunctionResponseBlob' } },
    },
    MediaResolution: {
      type: 'object',
      description:
        'Schema referenced but not defined upstream (missing from source OpenAPI spec)',
      additionalProperties: true,
    },
    ToolCall: {
      type: 'object',
      description:
        'A predicted server-side `ToolCall` returned from the model. This message contains information about a tool that the model wants to invoke. The client is NOT expected to execute this `ToolCall`. Instead, the client should pass this `ToolCall` back to the API in a subsequent turn within a `Content` message, along with the corresponding `ToolResponse`.',
      properties: {
        id: {
          type: 'string',
          description:
            'Optional. Unique identifier of the tool call. The server returns the tool response with the matching `id`.',
        },
        toolType: {
          type: 'string',
          description: 'Required. The type of tool that was called.',
          enum: [
            'TOOL_TYPE_UNSPECIFIED',
            'GOOGLE_SEARCH_WEB',
            'GOOGLE_SEARCH_IMAGE',
            'URL_CONTEXT',
            'GOOGLE_MAPS',
            'FILE_SEARCH',
          ],
        },
        args: {
          type: 'object',
          description:
            'Optional. The tool call arguments. Example: {"arg1" : "value1", "arg2" : "value2" , ...}',
          additionalProperties: {
            type: 'any',
            description: 'Properties of the object.',
          },
        },
      },
    },
    ToolResponse: {
      type: 'object',
      description:
        'The output from a server-side `ToolCall` execution. This message contains the results of a tool invocation that was initiated by a `ToolCall` from the model. The client should pass this `ToolResponse` back to the API in a subsequent turn within a `Content` message, along with the corresponding `ToolCall`.',
      properties: {
        id: {
          type: 'string',
          description:
            'Optional. The identifier of the tool call this response is for.',
        },
        toolType: {
          type: 'string',
          description:
            'Required. The type of tool that was called, matching the `tool_type` in the corresponding `ToolCall`.',
          enum: [
            'TOOL_TYPE_UNSPECIFIED',
            'GOOGLE_SEARCH_WEB',
            'GOOGLE_SEARCH_IMAGE',
            'URL_CONTEXT',
            'GOOGLE_MAPS',
            'FILE_SEARCH',
          ],
        },
        response: {
          type: 'object',
          description: 'Optional. The tool response.',
          additionalProperties: {
            type: 'any',
            description: 'Properties of the object.',
          },
        },
      },
    },
    VideoMetadata: {
      type: 'object',
      description:
        'Deprecated: Use `GenerateContentRequest.processing_options` instead. Metadata describes the input video content.',
      properties: {
        startOffset: {
          type: 'string',
          format: 'google-duration',
          description: 'Optional. The start offset of the video.',
        },
        endOffset: {
          type: 'string',
          format: 'google-duration',
          description: 'Optional. The end offset of the video.',
        },
        fps: {
          type: 'number',
          format: 'double',
          description:
            'Optional. The frame rate of the video sent to the model. If not specified, the default value will be 1.0. The fps range is (0.0, 24.0].',
        },
      },
    },
  },
} as const

export const ToolCallSchema = {
  type: 'object',
  description:
    'A predicted server-side `ToolCall` returned from the model. This message contains information about a tool that the model wants to invoke. The client is NOT expected to execute this `ToolCall`. Instead, the client should pass this `ToolCall` back to the API in a subsequent turn within a `Content` message, along with the corresponding `ToolResponse`.',
  properties: {
    id: {
      type: 'string',
      description:
        'Optional. Unique identifier of the tool call. The server returns the tool response with the matching `id`.',
    },
    toolType: {
      type: 'string',
      description: 'Required. The type of tool that was called.',
      enum: [
        'TOOL_TYPE_UNSPECIFIED',
        'GOOGLE_SEARCH_WEB',
        'GOOGLE_SEARCH_IMAGE',
        'URL_CONTEXT',
        'GOOGLE_MAPS',
        'FILE_SEARCH',
      ],
    },
    args: {
      type: 'object',
      description:
        'Optional. The tool call arguments. Example: {"arg1" : "value1", "arg2" : "value2" , ...}',
      additionalProperties: {
        type: 'any',
        description: 'Properties of the object.',
      },
    },
  },
} as const

export const ToolResponseSchema = {
  type: 'object',
  description:
    'The output from a server-side `ToolCall` execution. This message contains the results of a tool invocation that was initiated by a `ToolCall` from the model. The client should pass this `ToolResponse` back to the API in a subsequent turn within a `Content` message, along with the corresponding `ToolCall`.',
  properties: {
    id: {
      type: 'string',
      description:
        'Optional. The identifier of the tool call this response is for.',
    },
    toolType: {
      type: 'string',
      description:
        'Required. The type of tool that was called, matching the `tool_type` in the corresponding `ToolCall`.',
      enum: [
        'TOOL_TYPE_UNSPECIFIED',
        'GOOGLE_SEARCH_WEB',
        'GOOGLE_SEARCH_IMAGE',
        'URL_CONTEXT',
        'GOOGLE_MAPS',
        'FILE_SEARCH',
      ],
    },
    response: {
      type: 'object',
      description: 'Optional. The tool response.',
      additionalProperties: {
        type: 'any',
        description: 'Properties of the object.',
      },
    },
  },
} as const

export const VideoMetadataSchema = {
  type: 'object',
  description:
    'Deprecated: Use `GenerateContentRequest.processing_options` instead. Metadata describes the input video content.',
  properties: {
    startOffset: {
      type: 'string',
      format: 'google-duration',
      description: 'Optional. The start offset of the video.',
    },
    endOffset: {
      type: 'string',
      format: 'google-duration',
      description: 'Optional. The end offset of the video.',
    },
    fps: {
      type: 'number',
      format: 'double',
      description:
        'Optional. The frame rate of the video sent to the model. If not specified, the default value will be 1.0. The fps range is (0.0, 24.0].',
    },
  },
} as const
