// AUTO-GENERATED - Do not edit manually
// Generated by @hey-api/openapi-ts and post-processed by
// scripts/generate-endpoint-maps.ts to embed each schema's $defs closure.

export const BadRequestResponseSchema = {
  description: 'Bad Request - Invalid request parameters or malformed input',
  example: { error: { code: 400, message: 'Invalid request parameters' } },
  properties: {
    error: { $ref: '#/$defs/BadRequestResponseErrorData' },
    openrouter_metadata: {
      additionalProperties: { nullable: true },
      nullable: true,
      type: 'object',
    },
    user_id: { nullable: true, type: 'string' },
  },
  required: ['error'],
  type: 'object',
  $defs: {
    BadRequestResponseErrorData: {
      description: 'Error data for BadRequestResponse',
      example: { code: 400, message: 'Invalid request parameters' },
      properties: {
        code: { type: 'integer' },
        message: { type: 'string' },
        metadata: {
          additionalProperties: { nullable: true },
          nullable: true,
          type: 'object',
        },
      },
      required: ['code', 'message'],
      type: 'object',
    },
  },
} as const

export const BadRequestResponseErrorDataSchema = {
  description: 'Error data for BadRequestResponse',
  example: { code: 400, message: 'Invalid request parameters' },
  properties: {
    code: { type: 'integer' },
    message: { type: 'string' },
    metadata: {
      additionalProperties: { nullable: true },
      nullable: true,
      type: 'object',
    },
  },
  required: ['code', 'message'],
  type: 'object',
} as const

export const ContentPartImageSchema = {
  example: {
    image_url: { url: 'https://example.com/image.png' },
    type: 'image_url',
  },
  properties: {
    image_url: {
      properties: { url: { type: 'string' } },
      required: ['url'],
      type: 'object',
    },
    type: { enum: ['image_url'], type: 'string' },
  },
  required: ['type', 'image_url'],
  type: 'object',
} as const

export const FrameImageSchema = {
  allOf: [
    { $ref: '#/$defs/ContentPartImage' },
    {
      properties: {
        frame_type: {
          description:
            'Whether this image represents the first or last frame of the video',
          enum: ['first_frame', 'last_frame'],
          example: 'first_frame',
          type: 'string',
          'x-speakeasy-unknown-values': 'allow',
        },
      },
      required: ['frame_type'],
      type: 'object',
    },
  ],
  example: {
    image_url: { url: 'https://example.com/image.png' },
    type: 'image_url',
  },
  $defs: {
    ContentPartImage: {
      example: {
        image_url: { url: 'https://example.com/image.png' },
        type: 'image_url',
      },
      properties: {
        image_url: {
          properties: { url: { type: 'string' } },
          required: ['url'],
          type: 'object',
        },
        type: { enum: ['image_url'], type: 'string' },
      },
      required: ['type', 'image_url'],
      type: 'object',
    },
  },
} as const

export const InternalServerResponseSchema = {
  description: 'Internal Server Error - Unexpected server error',
  example: { error: { code: 500, message: 'Internal Server Error' } },
  properties: {
    error: { $ref: '#/$defs/InternalServerResponseErrorData' },
    openrouter_metadata: {
      additionalProperties: { nullable: true },
      nullable: true,
      type: 'object',
    },
    user_id: { nullable: true, type: 'string' },
  },
  required: ['error'],
  type: 'object',
  $defs: {
    InternalServerResponseErrorData: {
      description: 'Error data for InternalServerResponse',
      example: { code: 500, message: 'Internal Server Error' },
      properties: {
        code: { type: 'integer' },
        message: { type: 'string' },
        metadata: {
          additionalProperties: { nullable: true },
          nullable: true,
          type: 'object',
        },
      },
      required: ['code', 'message'],
      type: 'object',
    },
  },
} as const

export const InternalServerResponseErrorDataSchema = {
  description: 'Error data for InternalServerResponse',
  example: { code: 500, message: 'Internal Server Error' },
  properties: {
    code: { type: 'integer' },
    message: { type: 'string' },
    metadata: {
      additionalProperties: { nullable: true },
      nullable: true,
      type: 'object',
    },
  },
  required: ['code', 'message'],
  type: 'object',
} as const

export const NotFoundResponseSchema = {
  description: 'Not Found - Resource does not exist',
  example: { error: { code: 404, message: 'Resource not found' } },
  properties: {
    error: { $ref: '#/$defs/NotFoundResponseErrorData' },
    openrouter_metadata: {
      additionalProperties: { nullable: true },
      nullable: true,
      type: 'object',
    },
    user_id: { nullable: true, type: 'string' },
  },
  required: ['error'],
  type: 'object',
  $defs: {
    NotFoundResponseErrorData: {
      description: 'Error data for NotFoundResponse',
      example: { code: 404, message: 'Resource not found' },
      properties: {
        code: { type: 'integer' },
        message: { type: 'string' },
        metadata: {
          additionalProperties: { nullable: true },
          nullable: true,
          type: 'object',
        },
      },
      required: ['code', 'message'],
      type: 'object',
    },
  },
} as const

export const NotFoundResponseErrorDataSchema = {
  description: 'Error data for NotFoundResponse',
  example: { code: 404, message: 'Resource not found' },
  properties: {
    code: { type: 'integer' },
    message: { type: 'string' },
    metadata: {
      additionalProperties: { nullable: true },
      nullable: true,
      type: 'object',
    },
  },
  required: ['code', 'message'],
  type: 'object',
} as const

export const PaymentRequiredResponseSchema = {
  description:
    'Payment Required - Insufficient credits or quota to complete request',
  example: {
    error: {
      code: 402,
      message:
        'Insufficient credits. Add more using https://openrouter.ai/credits',
    },
  },
  properties: {
    error: { $ref: '#/$defs/PaymentRequiredResponseErrorData' },
    openrouter_metadata: {
      additionalProperties: { nullable: true },
      nullable: true,
      type: 'object',
    },
    user_id: { nullable: true, type: 'string' },
  },
  required: ['error'],
  type: 'object',
  $defs: {
    PaymentRequiredResponseErrorData: {
      description: 'Error data for PaymentRequiredResponse',
      example: {
        code: 402,
        message:
          'Insufficient credits. Add more using https://openrouter.ai/credits',
      },
      properties: {
        code: { type: 'integer' },
        message: { type: 'string' },
        metadata: {
          additionalProperties: { nullable: true },
          nullable: true,
          type: 'object',
        },
      },
      required: ['code', 'message'],
      type: 'object',
    },
  },
} as const

export const PaymentRequiredResponseErrorDataSchema = {
  description: 'Error data for PaymentRequiredResponse',
  example: {
    code: 402,
    message:
      'Insufficient credits. Add more using https://openrouter.ai/credits',
  },
  properties: {
    code: { type: 'integer' },
    message: { type: 'string' },
    metadata: {
      additionalProperties: { nullable: true },
      nullable: true,
      type: 'object',
    },
  },
  required: ['code', 'message'],
  type: 'object',
} as const

export const ProviderOptionsSchema = {
  description:
    'Provider-specific options keyed by provider slug. The options for the matched provider are spread into the upstream request body.',
  example: { openai: { max_tokens: 1000 } },
  properties: {
    '01ai': { additionalProperties: { nullable: true }, type: 'object' },
    ai21: { additionalProperties: { nullable: true }, type: 'object' },
    'aion-labs': { additionalProperties: { nullable: true }, type: 'object' },
    akashml: { additionalProperties: { nullable: true }, type: 'object' },
    alibaba: { additionalProperties: { nullable: true }, type: 'object' },
    'amazon-bedrock': {
      additionalProperties: { nullable: true },
      type: 'object',
    },
    'amazon-nova': { additionalProperties: { nullable: true }, type: 'object' },
    ambient: { additionalProperties: { nullable: true }, type: 'object' },
    anthropic: { additionalProperties: { nullable: true }, type: 'object' },
    anyscale: { additionalProperties: { nullable: true }, type: 'object' },
    'arcee-ai': { additionalProperties: { nullable: true }, type: 'object' },
    'atlas-cloud': { additionalProperties: { nullable: true }, type: 'object' },
    atoma: { additionalProperties: { nullable: true }, type: 'object' },
    avian: { additionalProperties: { nullable: true }, type: 'object' },
    azure: { additionalProperties: { nullable: true }, type: 'object' },
    baidu: { additionalProperties: { nullable: true }, type: 'object' },
    baseten: { additionalProperties: { nullable: true }, type: 'object' },
    'black-forest-labs': {
      additionalProperties: { nullable: true },
      type: 'object',
    },
    byteplus: { additionalProperties: { nullable: true }, type: 'object' },
    centml: { additionalProperties: { nullable: true }, type: 'object' },
    cerebras: { additionalProperties: { nullable: true }, type: 'object' },
    chutes: { additionalProperties: { nullable: true }, type: 'object' },
    cirrascale: { additionalProperties: { nullable: true }, type: 'object' },
    clarifai: { additionalProperties: { nullable: true }, type: 'object' },
    cloudflare: { additionalProperties: { nullable: true }, type: 'object' },
    cohere: { additionalProperties: { nullable: true }, type: 'object' },
    crofai: { additionalProperties: { nullable: true }, type: 'object' },
    crucible: { additionalProperties: { nullable: true }, type: 'object' },
    crusoe: { additionalProperties: { nullable: true }, type: 'object' },
    darkbloom: { additionalProperties: { nullable: true }, type: 'object' },
    deepinfra: { additionalProperties: { nullable: true }, type: 'object' },
    deepseek: { additionalProperties: { nullable: true }, type: 'object' },
    dekallm: { additionalProperties: { nullable: true }, type: 'object' },
    digitalocean: { additionalProperties: { nullable: true }, type: 'object' },
    enfer: { additionalProperties: { nullable: true }, type: 'object' },
    'fake-provider': {
      additionalProperties: { nullable: true },
      type: 'object',
    },
    featherless: { additionalProperties: { nullable: true }, type: 'object' },
    fireworks: { additionalProperties: { nullable: true }, type: 'object' },
    friendli: { additionalProperties: { nullable: true }, type: 'object' },
    gmicloud: { additionalProperties: { nullable: true }, type: 'object' },
    'google-ai-studio': {
      additionalProperties: { nullable: true },
      type: 'object',
    },
    'google-vertex': {
      additionalProperties: { nullable: true },
      type: 'object',
    },
    gopomelo: { additionalProperties: { nullable: true }, type: 'object' },
    groq: { additionalProperties: { nullable: true }, type: 'object' },
    huggingface: { additionalProperties: { nullable: true }, type: 'object' },
    hyperbolic: { additionalProperties: { nullable: true }, type: 'object' },
    'hyperbolic-quantized': {
      additionalProperties: { nullable: true },
      type: 'object',
    },
    inception: { additionalProperties: { nullable: true }, type: 'object' },
    inceptron: { additionalProperties: { nullable: true }, type: 'object' },
    'inference-net': {
      additionalProperties: { nullable: true },
      type: 'object',
    },
    infermatic: { additionalProperties: { nullable: true }, type: 'object' },
    inflection: { additionalProperties: { nullable: true }, type: 'object' },
    inocloud: { additionalProperties: { nullable: true }, type: 'object' },
    'io-net': { additionalProperties: { nullable: true }, type: 'object' },
    ionstream: { additionalProperties: { nullable: true }, type: 'object' },
    klusterai: { additionalProperties: { nullable: true }, type: 'object' },
    lambda: { additionalProperties: { nullable: true }, type: 'object' },
    lepton: { additionalProperties: { nullable: true }, type: 'object' },
    liquid: { additionalProperties: { nullable: true }, type: 'object' },
    lynn: { additionalProperties: { nullable: true }, type: 'object' },
    'lynn-private': {
      additionalProperties: { nullable: true },
      type: 'object',
    },
    mancer: { additionalProperties: { nullable: true }, type: 'object' },
    'mancer-old': { additionalProperties: { nullable: true }, type: 'object' },
    mara: { additionalProperties: { nullable: true }, type: 'object' },
    meta: { additionalProperties: { nullable: true }, type: 'object' },
    minimax: { additionalProperties: { nullable: true }, type: 'object' },
    mistral: { additionalProperties: { nullable: true }, type: 'object' },
    modal: { additionalProperties: { nullable: true }, type: 'object' },
    modelrun: { additionalProperties: { nullable: true }, type: 'object' },
    modular: { additionalProperties: { nullable: true }, type: 'object' },
    moonshotai: { additionalProperties: { nullable: true }, type: 'object' },
    morph: { additionalProperties: { nullable: true }, type: 'object' },
    ncompass: { additionalProperties: { nullable: true }, type: 'object' },
    nebius: { additionalProperties: { nullable: true }, type: 'object' },
    'nex-agi': { additionalProperties: { nullable: true }, type: 'object' },
    nextbit: { additionalProperties: { nullable: true }, type: 'object' },
    nineteen: { additionalProperties: { nullable: true }, type: 'object' },
    novita: { additionalProperties: { nullable: true }, type: 'object' },
    nvidia: { additionalProperties: { nullable: true }, type: 'object' },
    octoai: { additionalProperties: { nullable: true }, type: 'object' },
    'open-inference': {
      additionalProperties: { nullable: true },
      type: 'object',
    },
    openai: { additionalProperties: { nullable: true }, type: 'object' },
    parasail: { additionalProperties: { nullable: true }, type: 'object' },
    perceptron: { additionalProperties: { nullable: true }, type: 'object' },
    perplexity: { additionalProperties: { nullable: true }, type: 'object' },
    phala: { additionalProperties: { nullable: true }, type: 'object' },
    poolside: { additionalProperties: { nullable: true }, type: 'object' },
    recraft: { additionalProperties: { nullable: true }, type: 'object' },
    recursal: { additionalProperties: { nullable: true }, type: 'object' },
    reflection: { additionalProperties: { nullable: true }, type: 'object' },
    reka: { additionalProperties: { nullable: true }, type: 'object' },
    relace: { additionalProperties: { nullable: true }, type: 'object' },
    replicate: { additionalProperties: { nullable: true }, type: 'object' },
    sambanova: { additionalProperties: { nullable: true }, type: 'object' },
    'sambanova-cloaked': {
      additionalProperties: { nullable: true },
      type: 'object',
    },
    seed: { additionalProperties: { nullable: true }, type: 'object' },
    'sf-compute': { additionalProperties: { nullable: true }, type: 'object' },
    siliconflow: { additionalProperties: { nullable: true }, type: 'object' },
    sourceful: { additionalProperties: { nullable: true }, type: 'object' },
    stealth: { additionalProperties: { nullable: true }, type: 'object' },
    stepfun: { additionalProperties: { nullable: true }, type: 'object' },
    streamlake: { additionalProperties: { nullable: true }, type: 'object' },
    switchpoint: { additionalProperties: { nullable: true }, type: 'object' },
    targon: { additionalProperties: { nullable: true }, type: 'object' },
    together: { additionalProperties: { nullable: true }, type: 'object' },
    'together-lite': {
      additionalProperties: { nullable: true },
      type: 'object',
    },
    ubicloud: { additionalProperties: { nullable: true }, type: 'object' },
    upstage: { additionalProperties: { nullable: true }, type: 'object' },
    venice: { additionalProperties: { nullable: true }, type: 'object' },
    wandb: { additionalProperties: { nullable: true }, type: 'object' },
    xai: { additionalProperties: { nullable: true }, type: 'object' },
    xiaomi: { additionalProperties: { nullable: true }, type: 'object' },
    'z-ai': { additionalProperties: { nullable: true }, type: 'object' },
  },
  type: 'object',
} as const

export const TooManyRequestsResponseSchema = {
  description: 'Too Many Requests - Rate limit exceeded',
  example: { error: { code: 429, message: 'Rate limit exceeded' } },
  properties: {
    error: { $ref: '#/$defs/TooManyRequestsResponseErrorData' },
    openrouter_metadata: {
      additionalProperties: { nullable: true },
      nullable: true,
      type: 'object',
    },
    user_id: { nullable: true, type: 'string' },
  },
  required: ['error'],
  type: 'object',
  $defs: {
    TooManyRequestsResponseErrorData: {
      description: 'Error data for TooManyRequestsResponse',
      example: { code: 429, message: 'Rate limit exceeded' },
      properties: {
        code: { type: 'integer' },
        message: { type: 'string' },
        metadata: {
          additionalProperties: { nullable: true },
          nullable: true,
          type: 'object',
        },
      },
      required: ['code', 'message'],
      type: 'object',
    },
  },
} as const

export const TooManyRequestsResponseErrorDataSchema = {
  description: 'Error data for TooManyRequestsResponse',
  example: { code: 429, message: 'Rate limit exceeded' },
  properties: {
    code: { type: 'integer' },
    message: { type: 'string' },
    metadata: {
      additionalProperties: { nullable: true },
      nullable: true,
      type: 'object',
    },
  },
  required: ['code', 'message'],
  type: 'object',
} as const

export const UnauthorizedResponseSchema = {
  description: 'Unauthorized - Authentication required or invalid credentials',
  example: { error: { code: 401, message: 'Missing Authentication header' } },
  properties: {
    error: { $ref: '#/$defs/UnauthorizedResponseErrorData' },
    openrouter_metadata: {
      additionalProperties: { nullable: true },
      nullable: true,
      type: 'object',
    },
    user_id: { nullable: true, type: 'string' },
  },
  required: ['error'],
  type: 'object',
  $defs: {
    UnauthorizedResponseErrorData: {
      description: 'Error data for UnauthorizedResponse',
      example: { code: 401, message: 'Missing Authentication header' },
      properties: {
        code: { type: 'integer' },
        message: { type: 'string' },
        metadata: {
          additionalProperties: { nullable: true },
          nullable: true,
          type: 'object',
        },
      },
      required: ['code', 'message'],
      type: 'object',
    },
  },
} as const

export const UnauthorizedResponseErrorDataSchema = {
  description: 'Error data for UnauthorizedResponse',
  example: { code: 401, message: 'Missing Authentication header' },
  properties: {
    code: { type: 'integer' },
    message: { type: 'string' },
    metadata: {
      additionalProperties: { nullable: true },
      nullable: true,
      type: 'object',
    },
  },
  required: ['code', 'message'],
  type: 'object',
} as const

export const VideoGenerationRequestSchema = {
  example: {
    aspect_ratio: '16:9',
    duration: 8,
    model: 'google/veo-3.1',
    prompt: 'A serene mountain landscape at sunset',
    resolution: '720p',
  },
  properties: {
    aspect_ratio: {
      description: 'Aspect ratio of the generated video',
      enum: ['16:9', '9:16', '1:1', '4:3', '3:4', '3:2', '2:3', '21:9', '9:21'],
      example: '16:9',
      type: 'string',
      'x-speakeasy-unknown-values': 'allow',
    },
    callback_url: {
      description:
        'URL to receive a webhook notification when the video generation job completes. Overrides the workspace-level default callback URL if set. Must be HTTPS.',
      example: 'https://example.com/webhook',
      format: 'uri',
      type: 'string',
    },
    duration: {
      description: 'Duration of the generated video in seconds',
      example: 8,
      minimum: 1,
      type: 'integer',
    },
    frame_images: {
      description:
        'Images to use as the first and/or last frame of the generated video. Each image must specify a frame_type of first_frame or last_frame.',
      items: { $ref: '#/$defs/FrameImage' },
      type: 'array',
    },
    generate_audio: {
      description:
        "Whether to generate audio alongside the video. Defaults to the endpoint's generate_audio capability flag, false if not set.",
      example: true,
      type: 'boolean',
    },
    input_references: {
      description: 'Reference images to guide video generation',
      items: { $ref: '#/$defs/ContentPartImage' },
      type: 'array',
    },
    model: { type: 'string' },
    prompt: { type: 'string' },
    provider: {
      description: 'Provider-specific passthrough configuration',
      properties: {
        options: {
          allOf: [
            { $ref: '#/$defs/ProviderOptions' },
            {
              example: {
                'google-vertex': { output_config: { effort: 'low' } },
              },
            },
          ],
        },
      },
      type: 'object',
    },
    resolution: {
      description: 'Resolution of the generated video',
      enum: ['480p', '720p', '1080p', '1K', '2K', '4K'],
      example: '720p',
      type: 'string',
      'x-speakeasy-unknown-values': 'allow',
    },
    seed: {
      description:
        'If specified, the generation will sample deterministically, such that repeated requests with the same seed and parameters should return the same result. Determinism is not guaranteed for all providers.',
      type: 'integer',
    },
    size: {
      description:
        'Exact pixel dimensions of the generated video in "WIDTHxHEIGHT" format (e.g. "1280x720"). Interchangeable with resolution + aspect_ratio.',
      example: '1280x720',
      type: 'string',
    },
  },
  required: ['prompt', 'model'],
  type: 'object',
  $defs: {
    ContentPartImage: {
      example: {
        image_url: { url: 'https://example.com/image.png' },
        type: 'image_url',
      },
      properties: {
        image_url: {
          properties: { url: { type: 'string' } },
          required: ['url'],
          type: 'object',
        },
        type: { enum: ['image_url'], type: 'string' },
      },
      required: ['type', 'image_url'],
      type: 'object',
    },
    FrameImage: {
      allOf: [
        { $ref: '#/$defs/ContentPartImage' },
        {
          properties: {
            frame_type: {
              description:
                'Whether this image represents the first or last frame of the video',
              enum: ['first_frame', 'last_frame'],
              example: 'first_frame',
              type: 'string',
              'x-speakeasy-unknown-values': 'allow',
            },
          },
          required: ['frame_type'],
          type: 'object',
        },
      ],
      example: {
        image_url: { url: 'https://example.com/image.png' },
        type: 'image_url',
      },
    },
    ProviderOptions: {
      description:
        'Provider-specific options keyed by provider slug. The options for the matched provider are spread into the upstream request body.',
      example: { openai: { max_tokens: 1000 } },
      properties: {
        '01ai': { additionalProperties: { nullable: true }, type: 'object' },
        ai21: { additionalProperties: { nullable: true }, type: 'object' },
        'aion-labs': {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        akashml: { additionalProperties: { nullable: true }, type: 'object' },
        alibaba: { additionalProperties: { nullable: true }, type: 'object' },
        'amazon-bedrock': {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        'amazon-nova': {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        ambient: { additionalProperties: { nullable: true }, type: 'object' },
        anthropic: { additionalProperties: { nullable: true }, type: 'object' },
        anyscale: { additionalProperties: { nullable: true }, type: 'object' },
        'arcee-ai': {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        'atlas-cloud': {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        atoma: { additionalProperties: { nullable: true }, type: 'object' },
        avian: { additionalProperties: { nullable: true }, type: 'object' },
        azure: { additionalProperties: { nullable: true }, type: 'object' },
        baidu: { additionalProperties: { nullable: true }, type: 'object' },
        baseten: { additionalProperties: { nullable: true }, type: 'object' },
        'black-forest-labs': {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        byteplus: { additionalProperties: { nullable: true }, type: 'object' },
        centml: { additionalProperties: { nullable: true }, type: 'object' },
        cerebras: { additionalProperties: { nullable: true }, type: 'object' },
        chutes: { additionalProperties: { nullable: true }, type: 'object' },
        cirrascale: {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        clarifai: { additionalProperties: { nullable: true }, type: 'object' },
        cloudflare: {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        cohere: { additionalProperties: { nullable: true }, type: 'object' },
        crofai: { additionalProperties: { nullable: true }, type: 'object' },
        crucible: { additionalProperties: { nullable: true }, type: 'object' },
        crusoe: { additionalProperties: { nullable: true }, type: 'object' },
        darkbloom: { additionalProperties: { nullable: true }, type: 'object' },
        deepinfra: { additionalProperties: { nullable: true }, type: 'object' },
        deepseek: { additionalProperties: { nullable: true }, type: 'object' },
        dekallm: { additionalProperties: { nullable: true }, type: 'object' },
        digitalocean: {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        enfer: { additionalProperties: { nullable: true }, type: 'object' },
        'fake-provider': {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        featherless: {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        fireworks: { additionalProperties: { nullable: true }, type: 'object' },
        friendli: { additionalProperties: { nullable: true }, type: 'object' },
        gmicloud: { additionalProperties: { nullable: true }, type: 'object' },
        'google-ai-studio': {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        'google-vertex': {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        gopomelo: { additionalProperties: { nullable: true }, type: 'object' },
        groq: { additionalProperties: { nullable: true }, type: 'object' },
        huggingface: {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        hyperbolic: {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        'hyperbolic-quantized': {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        inception: { additionalProperties: { nullable: true }, type: 'object' },
        inceptron: { additionalProperties: { nullable: true }, type: 'object' },
        'inference-net': {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        infermatic: {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        inflection: {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        inocloud: { additionalProperties: { nullable: true }, type: 'object' },
        'io-net': { additionalProperties: { nullable: true }, type: 'object' },
        ionstream: { additionalProperties: { nullable: true }, type: 'object' },
        klusterai: { additionalProperties: { nullable: true }, type: 'object' },
        lambda: { additionalProperties: { nullable: true }, type: 'object' },
        lepton: { additionalProperties: { nullable: true }, type: 'object' },
        liquid: { additionalProperties: { nullable: true }, type: 'object' },
        lynn: { additionalProperties: { nullable: true }, type: 'object' },
        'lynn-private': {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        mancer: { additionalProperties: { nullable: true }, type: 'object' },
        'mancer-old': {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        mara: { additionalProperties: { nullable: true }, type: 'object' },
        meta: { additionalProperties: { nullable: true }, type: 'object' },
        minimax: { additionalProperties: { nullable: true }, type: 'object' },
        mistral: { additionalProperties: { nullable: true }, type: 'object' },
        modal: { additionalProperties: { nullable: true }, type: 'object' },
        modelrun: { additionalProperties: { nullable: true }, type: 'object' },
        modular: { additionalProperties: { nullable: true }, type: 'object' },
        moonshotai: {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        morph: { additionalProperties: { nullable: true }, type: 'object' },
        ncompass: { additionalProperties: { nullable: true }, type: 'object' },
        nebius: { additionalProperties: { nullable: true }, type: 'object' },
        'nex-agi': { additionalProperties: { nullable: true }, type: 'object' },
        nextbit: { additionalProperties: { nullable: true }, type: 'object' },
        nineteen: { additionalProperties: { nullable: true }, type: 'object' },
        novita: { additionalProperties: { nullable: true }, type: 'object' },
        nvidia: { additionalProperties: { nullable: true }, type: 'object' },
        octoai: { additionalProperties: { nullable: true }, type: 'object' },
        'open-inference': {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        openai: { additionalProperties: { nullable: true }, type: 'object' },
        parasail: { additionalProperties: { nullable: true }, type: 'object' },
        perceptron: {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        perplexity: {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        phala: { additionalProperties: { nullable: true }, type: 'object' },
        poolside: { additionalProperties: { nullable: true }, type: 'object' },
        recraft: { additionalProperties: { nullable: true }, type: 'object' },
        recursal: { additionalProperties: { nullable: true }, type: 'object' },
        reflection: {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        reka: { additionalProperties: { nullable: true }, type: 'object' },
        relace: { additionalProperties: { nullable: true }, type: 'object' },
        replicate: { additionalProperties: { nullable: true }, type: 'object' },
        sambanova: { additionalProperties: { nullable: true }, type: 'object' },
        'sambanova-cloaked': {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        seed: { additionalProperties: { nullable: true }, type: 'object' },
        'sf-compute': {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        siliconflow: {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        sourceful: { additionalProperties: { nullable: true }, type: 'object' },
        stealth: { additionalProperties: { nullable: true }, type: 'object' },
        stepfun: { additionalProperties: { nullable: true }, type: 'object' },
        streamlake: {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        switchpoint: {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        targon: { additionalProperties: { nullable: true }, type: 'object' },
        together: { additionalProperties: { nullable: true }, type: 'object' },
        'together-lite': {
          additionalProperties: { nullable: true },
          type: 'object',
        },
        ubicloud: { additionalProperties: { nullable: true }, type: 'object' },
        upstage: { additionalProperties: { nullable: true }, type: 'object' },
        venice: { additionalProperties: { nullable: true }, type: 'object' },
        wandb: { additionalProperties: { nullable: true }, type: 'object' },
        xai: { additionalProperties: { nullable: true }, type: 'object' },
        xiaomi: { additionalProperties: { nullable: true }, type: 'object' },
        'z-ai': { additionalProperties: { nullable: true }, type: 'object' },
      },
      type: 'object',
    },
  },
} as const

export const VideoGenerationResponseSchema = {
  example: {
    generation_id: 'gen-xyz789',
    id: 'job-abc123',
    polling_url: '/api/v1/videos/job-abc123',
    status: 'pending',
  },
  properties: {
    error: { type: 'string' },
    generation_id: {
      description:
        'The generation ID associated with this video generation job. Available once the job has been processed.',
      type: 'string',
    },
    id: { type: 'string' },
    polling_url: { type: 'string' },
    status: {
      enum: [
        'pending',
        'in_progress',
        'completed',
        'failed',
        'cancelled',
        'expired',
      ],
      type: 'string',
      'x-speakeasy-unknown-values': 'allow',
    },
    unsigned_urls: { items: { type: 'string' }, type: 'array' },
    usage: { $ref: '#/$defs/VideoGenerationUsage' },
  },
  required: ['id', 'polling_url', 'status'],
  type: 'object',
  $defs: {
    VideoGenerationUsage: {
      description:
        'Usage and cost information for the video generation. Available once the job has completed.',
      example: { cost: 0.5, is_byok: false },
      properties: {
        cost: {
          description: 'The cost of the video generation in USD.',
          format: 'double',
          nullable: true,
          type: 'number',
        },
        is_byok: {
          description:
            'Whether the request was made using a Bring Your Own Key configuration.',
          type: 'boolean',
        },
      },
      type: 'object',
    },
  },
} as const

export const VideoGenerationUsageSchema = {
  description:
    'Usage and cost information for the video generation. Available once the job has completed.',
  example: { cost: 0.5, is_byok: false },
  properties: {
    cost: {
      description: 'The cost of the video generation in USD.',
      format: 'double',
      nullable: true,
      type: 'number',
    },
    is_byok: {
      description:
        'Whether the request was made using a Bring Your Own Key configuration.',
      type: 'boolean',
    },
  },
  type: 'object',
} as const
