// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod'

/**
 * Error data for BadRequestResponse
 */
export const zBadRequestResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Bad Request - Invalid request parameters or malformed input
 */
export const zBadRequestResponse = z.object({
  error: zBadRequestResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

export const zContentPartImage = z.object({
  image_url: z.object({
    url: z.string(),
  }),
  type: z.enum(['image_url']),
})

export const zFrameImage = zContentPartImage.and(
  z.object({
    frame_type: z.enum(['first_frame', 'last_frame']),
  }),
)

/**
 * Error data for InternalServerResponse
 */
export const zInternalServerResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Internal Server Error - Unexpected server error
 */
export const zInternalServerResponse = z.object({
  error: zInternalServerResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

/**
 * Error data for NotFoundResponse
 */
export const zNotFoundResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Not Found - Resource does not exist
 */
export const zNotFoundResponse = z.object({
  error: zNotFoundResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

/**
 * Error data for PaymentRequiredResponse
 */
export const zPaymentRequiredResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Payment Required - Insufficient credits or quota to complete request
 */
export const zPaymentRequiredResponse = z.object({
  error: zPaymentRequiredResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

/**
 * Provider-specific options keyed by provider slug. The options for the matched provider are spread into the upstream request body.
 */
export const zProviderOptions = z.object({
  '01ai': z.record(z.string(), z.unknown()).optional(),
  ai21: z.record(z.string(), z.unknown()).optional(),
  'aion-labs': z.record(z.string(), z.unknown()).optional(),
  akashml: z.record(z.string(), z.unknown()).optional(),
  alibaba: z.record(z.string(), z.unknown()).optional(),
  'amazon-bedrock': z.record(z.string(), z.unknown()).optional(),
  'amazon-nova': z.record(z.string(), z.unknown()).optional(),
  ambient: z.record(z.string(), z.unknown()).optional(),
  anthropic: z.record(z.string(), z.unknown()).optional(),
  anyscale: z.record(z.string(), z.unknown()).optional(),
  'arcee-ai': z.record(z.string(), z.unknown()).optional(),
  'atlas-cloud': z.record(z.string(), z.unknown()).optional(),
  atoma: z.record(z.string(), z.unknown()).optional(),
  avian: z.record(z.string(), z.unknown()).optional(),
  azure: z.record(z.string(), z.unknown()).optional(),
  baidu: z.record(z.string(), z.unknown()).optional(),
  baseten: z.record(z.string(), z.unknown()).optional(),
  'black-forest-labs': z.record(z.string(), z.unknown()).optional(),
  byteplus: z.record(z.string(), z.unknown()).optional(),
  centml: z.record(z.string(), z.unknown()).optional(),
  cerebras: z.record(z.string(), z.unknown()).optional(),
  chutes: z.record(z.string(), z.unknown()).optional(),
  cirrascale: z.record(z.string(), z.unknown()).optional(),
  clarifai: z.record(z.string(), z.unknown()).optional(),
  cloudflare: z.record(z.string(), z.unknown()).optional(),
  cohere: z.record(z.string(), z.unknown()).optional(),
  crofai: z.record(z.string(), z.unknown()).optional(),
  crucible: z.record(z.string(), z.unknown()).optional(),
  crusoe: z.record(z.string(), z.unknown()).optional(),
  darkbloom: z.record(z.string(), z.unknown()).optional(),
  deepinfra: z.record(z.string(), z.unknown()).optional(),
  deepseek: z.record(z.string(), z.unknown()).optional(),
  dekallm: z.record(z.string(), z.unknown()).optional(),
  digitalocean: z.record(z.string(), z.unknown()).optional(),
  enfer: z.record(z.string(), z.unknown()).optional(),
  'fake-provider': z.record(z.string(), z.unknown()).optional(),
  featherless: z.record(z.string(), z.unknown()).optional(),
  fireworks: z.record(z.string(), z.unknown()).optional(),
  friendli: z.record(z.string(), z.unknown()).optional(),
  gmicloud: z.record(z.string(), z.unknown()).optional(),
  'google-ai-studio': z.record(z.string(), z.unknown()).optional(),
  'google-vertex': z.record(z.string(), z.unknown()).optional(),
  gopomelo: z.record(z.string(), z.unknown()).optional(),
  groq: z.record(z.string(), z.unknown()).optional(),
  huggingface: z.record(z.string(), z.unknown()).optional(),
  hyperbolic: z.record(z.string(), z.unknown()).optional(),
  'hyperbolic-quantized': z.record(z.string(), z.unknown()).optional(),
  inception: z.record(z.string(), z.unknown()).optional(),
  inceptron: z.record(z.string(), z.unknown()).optional(),
  'inference-net': z.record(z.string(), z.unknown()).optional(),
  infermatic: z.record(z.string(), z.unknown()).optional(),
  inflection: z.record(z.string(), z.unknown()).optional(),
  inocloud: z.record(z.string(), z.unknown()).optional(),
  'io-net': z.record(z.string(), z.unknown()).optional(),
  ionstream: z.record(z.string(), z.unknown()).optional(),
  klusterai: z.record(z.string(), z.unknown()).optional(),
  lambda: z.record(z.string(), z.unknown()).optional(),
  lepton: z.record(z.string(), z.unknown()).optional(),
  liquid: z.record(z.string(), z.unknown()).optional(),
  lynn: z.record(z.string(), z.unknown()).optional(),
  'lynn-private': z.record(z.string(), z.unknown()).optional(),
  mancer: z.record(z.string(), z.unknown()).optional(),
  'mancer-old': z.record(z.string(), z.unknown()).optional(),
  mara: z.record(z.string(), z.unknown()).optional(),
  meta: z.record(z.string(), z.unknown()).optional(),
  minimax: z.record(z.string(), z.unknown()).optional(),
  mistral: z.record(z.string(), z.unknown()).optional(),
  modal: z.record(z.string(), z.unknown()).optional(),
  modelrun: z.record(z.string(), z.unknown()).optional(),
  modular: z.record(z.string(), z.unknown()).optional(),
  moonshotai: z.record(z.string(), z.unknown()).optional(),
  morph: z.record(z.string(), z.unknown()).optional(),
  ncompass: z.record(z.string(), z.unknown()).optional(),
  nebius: z.record(z.string(), z.unknown()).optional(),
  'nex-agi': z.record(z.string(), z.unknown()).optional(),
  nextbit: z.record(z.string(), z.unknown()).optional(),
  nineteen: z.record(z.string(), z.unknown()).optional(),
  novita: z.record(z.string(), z.unknown()).optional(),
  nvidia: z.record(z.string(), z.unknown()).optional(),
  octoai: z.record(z.string(), z.unknown()).optional(),
  'open-inference': z.record(z.string(), z.unknown()).optional(),
  openai: z.record(z.string(), z.unknown()).optional(),
  parasail: z.record(z.string(), z.unknown()).optional(),
  perceptron: z.record(z.string(), z.unknown()).optional(),
  perplexity: z.record(z.string(), z.unknown()).optional(),
  phala: z.record(z.string(), z.unknown()).optional(),
  poolside: z.record(z.string(), z.unknown()).optional(),
  recraft: z.record(z.string(), z.unknown()).optional(),
  recursal: z.record(z.string(), z.unknown()).optional(),
  reflection: z.record(z.string(), z.unknown()).optional(),
  reka: z.record(z.string(), z.unknown()).optional(),
  relace: z.record(z.string(), z.unknown()).optional(),
  replicate: z.record(z.string(), z.unknown()).optional(),
  sambanova: z.record(z.string(), z.unknown()).optional(),
  'sambanova-cloaked': z.record(z.string(), z.unknown()).optional(),
  seed: z.record(z.string(), z.unknown()).optional(),
  'sf-compute': z.record(z.string(), z.unknown()).optional(),
  siliconflow: z.record(z.string(), z.unknown()).optional(),
  sourceful: z.record(z.string(), z.unknown()).optional(),
  stealth: z.record(z.string(), z.unknown()).optional(),
  stepfun: z.record(z.string(), z.unknown()).optional(),
  streamlake: z.record(z.string(), z.unknown()).optional(),
  switchpoint: z.record(z.string(), z.unknown()).optional(),
  targon: z.record(z.string(), z.unknown()).optional(),
  together: z.record(z.string(), z.unknown()).optional(),
  'together-lite': z.record(z.string(), z.unknown()).optional(),
  ubicloud: z.record(z.string(), z.unknown()).optional(),
  upstage: z.record(z.string(), z.unknown()).optional(),
  venice: z.record(z.string(), z.unknown()).optional(),
  wandb: z.record(z.string(), z.unknown()).optional(),
  xai: z.record(z.string(), z.unknown()).optional(),
  xiaomi: z.record(z.string(), z.unknown()).optional(),
  'z-ai': z.record(z.string(), z.unknown()).optional(),
})

/**
 * Error data for TooManyRequestsResponse
 */
export const zTooManyRequestsResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Too Many Requests - Rate limit exceeded
 */
export const zTooManyRequestsResponse = z.object({
  error: zTooManyRequestsResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

/**
 * Error data for UnauthorizedResponse
 */
export const zUnauthorizedResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Unauthorized - Authentication required or invalid credentials
 */
export const zUnauthorizedResponse = z.object({
  error: zUnauthorizedResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

export const zVideoGenerationRequest = z.object({
  aspect_ratio: z
    .enum(['16:9', '9:16', '1:1', '4:3', '3:4', '3:2', '2:3', '21:9', '9:21'])
    .optional(),
  callback_url: z.url().optional(),
  duration: z.int().gte(1).optional(),
  frame_images: z.array(zFrameImage).optional(),
  generate_audio: z.boolean().optional(),
  input_references: z.array(zContentPartImage).optional(),
  model: z.string(),
  prompt: z.string(),
  provider: z
    .object({
      options: zProviderOptions.and(z.unknown()).optional(),
    })
    .optional(),
  resolution: z.enum(['480p', '720p', '1080p', '1K', '2K', '4K']).optional(),
  seed: z.int().optional(),
  size: z.string().optional(),
})

/**
 * Usage and cost information for the video generation. Available once the job has completed.
 */
export const zVideoGenerationUsage = z.object({
  cost: z.number().nullish(),
  is_byok: z.boolean().optional(),
})

export const zVideoGenerationResponse = z.object({
  error: z.string().optional(),
  generation_id: z.string().optional(),
  id: z.string(),
  polling_url: z.string(),
  status: z.enum([
    'pending',
    'in_progress',
    'completed',
    'failed',
    'cancelled',
    'expired',
  ]),
  unsigned_urls: z.array(z.string()).optional(),
  usage: zVideoGenerationUsage.optional(),
})

export const zCreateVideosBody = zVideoGenerationRequest

/**
 * Video generation request accepted
 */
export const zCreateVideosResponse = zVideoGenerationResponse
