// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod'

/**
 * Error data for BadRequestResponse
 */
export const zBadRequestResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Bad Request - Invalid request parameters or malformed input
 */
export const zBadRequestResponse = z.object({
  error: zBadRequestResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

export const zContentPartAudio = z.object({
  audio_url: z.object({
    url: z.string(),
  }),
  type: z.enum(['audio_url']),
})

export const zContentPartImage = z.object({
  image_url: z.object({
    url: z.string(),
  }),
  type: z.enum(['image_url']),
})

export const zContentPartVideo = z.object({
  type: z.enum(['video_url']),
  video_url: z.object({
    url: z.string(),
  }),
})

export const zFrameImage = zContentPartImage.and(
  z.object({
    frame_type: z.enum(['first_frame', 'last_frame']),
  }),
)

/**
 * A reference asset used to guide video generation. Image references are supported by all providers; audio and video references are only honored by providers that support them (currently BytePlus Seedance 2.0).
 */
export const zInputReference = z.discriminatedUnion('type', [
  zContentPartImage.extend({ type: z.literal('image_url') }),
  zContentPartAudio.extend({ type: z.literal('audio_url') }),
  zContentPartVideo.extend({ type: z.literal('video_url') }),
])

/**
 * Error data for InternalServerResponse
 */
export const zInternalServerResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Internal Server Error - Unexpected server error
 */
export const zInternalServerResponse = z.object({
  error: zInternalServerResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

/**
 * Error data for NotFoundResponse
 */
export const zNotFoundResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Not Found - Resource does not exist
 */
export const zNotFoundResponse = z.object({
  error: zNotFoundResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

/**
 * Error data for PaymentRequiredResponse
 */
export const zPaymentRequiredResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Payment Required - Insufficient credits or quota to complete request
 */
export const zPaymentRequiredResponse = z.object({
  error: zPaymentRequiredResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

/**
 * Provider-specific options keyed by provider slug. The options for the matched provider are spread into the upstream request body.
 */
export const zProviderOptions = z.object({
  '01ai': z.record(z.string(), z.unknown()).optional(),
  ai21: z.record(z.string(), z.unknown()).optional(),
  'aion-labs': z.record(z.string(), z.unknown()).optional(),
  akashml: z.record(z.string(), z.unknown()).optional(),
  alibaba: z.record(z.string(), z.unknown()).optional(),
  'amazon-bedrock': z.record(z.string(), z.unknown()).optional(),
  'amazon-nova': z.record(z.string(), z.unknown()).optional(),
  ambient: z.record(z.string(), z.unknown()).optional(),
  anthropic: z.record(z.string(), z.unknown()).optional(),
  anyscale: z.record(z.string(), z.unknown()).optional(),
  'arcee-ai': z.record(z.string(), z.unknown()).optional(),
  'atlas-cloud': z.record(z.string(), z.unknown()).optional(),
  atoma: z.record(z.string(), z.unknown()).optional(),
  avian: z.record(z.string(), z.unknown()).optional(),
  azure: z.record(z.string(), z.unknown()).optional(),
  baidu: z.record(z.string(), z.unknown()).optional(),
  baseten: z.record(z.string(), z.unknown()).optional(),
  'black-forest-labs': z.record(z.string(), z.unknown()).optional(),
  byteplus: z.record(z.string(), z.unknown()).optional(),
  centml: z.record(z.string(), z.unknown()).optional(),
  cerebras: z.record(z.string(), z.unknown()).optional(),
  chutes: z.record(z.string(), z.unknown()).optional(),
  cirrascale: z.record(z.string(), z.unknown()).optional(),
  clarifai: z.record(z.string(), z.unknown()).optional(),
  cloudflare: z.record(z.string(), z.unknown()).optional(),
  cohere: z.record(z.string(), z.unknown()).optional(),
  crofai: z.record(z.string(), z.unknown()).optional(),
  crucible: z.record(z.string(), z.unknown()).optional(),
  crusoe: z.record(z.string(), z.unknown()).optional(),
  darkbloom: z.record(z.string(), z.unknown()).optional(),
  decart: z.record(z.string(), z.unknown()).optional(),
  deepinfra: z.record(z.string(), z.unknown()).optional(),
  deepseek: z.record(z.string(), z.unknown()).optional(),
  dekallm: z.record(z.string(), z.unknown()).optional(),
  digitalocean: z.record(z.string(), z.unknown()).optional(),
  enfer: z.record(z.string(), z.unknown()).optional(),
  'fake-provider': z.record(z.string(), z.unknown()).optional(),
  featherless: z.record(z.string(), z.unknown()).optional(),
  fireworks: z.record(z.string(), z.unknown()).optional(),
  friendli: z.record(z.string(), z.unknown()).optional(),
  gmicloud: z.record(z.string(), z.unknown()).optional(),
  'google-ai-studio': z.record(z.string(), z.unknown()).optional(),
  'google-vertex': z.record(z.string(), z.unknown()).optional(),
  gopomelo: z.record(z.string(), z.unknown()).optional(),
  groq: z.record(z.string(), z.unknown()).optional(),
  huggingface: z.record(z.string(), z.unknown()).optional(),
  hyperbolic: z.record(z.string(), z.unknown()).optional(),
  'hyperbolic-quantized': z.record(z.string(), z.unknown()).optional(),
  inception: z.record(z.string(), z.unknown()).optional(),
  inceptron: z.record(z.string(), z.unknown()).optional(),
  'inference-net': z.record(z.string(), z.unknown()).optional(),
  infermatic: z.record(z.string(), z.unknown()).optional(),
  inflection: z.record(z.string(), z.unknown()).optional(),
  inocloud: z.record(z.string(), z.unknown()).optional(),
  'io-net': z.record(z.string(), z.unknown()).optional(),
  ionstream: z.record(z.string(), z.unknown()).optional(),
  klusterai: z.record(z.string(), z.unknown()).optional(),
  lambda: z.record(z.string(), z.unknown()).optional(),
  lepton: z.record(z.string(), z.unknown()).optional(),
  liquid: z.record(z.string(), z.unknown()).optional(),
  lynn: z.record(z.string(), z.unknown()).optional(),
  'lynn-private': z.record(z.string(), z.unknown()).optional(),
  mancer: z.record(z.string(), z.unknown()).optional(),
  'mancer-old': z.record(z.string(), z.unknown()).optional(),
  mara: z.record(z.string(), z.unknown()).optional(),
  meta: z.record(z.string(), z.unknown()).optional(),
  minimax: z.record(z.string(), z.unknown()).optional(),
  mistral: z.record(z.string(), z.unknown()).optional(),
  modal: z.record(z.string(), z.unknown()).optional(),
  modelrun: z.record(z.string(), z.unknown()).optional(),
  modular: z.record(z.string(), z.unknown()).optional(),
  moonshotai: z.record(z.string(), z.unknown()).optional(),
  morph: z.record(z.string(), z.unknown()).optional(),
  ncompass: z.record(z.string(), z.unknown()).optional(),
  nebius: z.record(z.string(), z.unknown()).optional(),
  'nex-agi': z.record(z.string(), z.unknown()).optional(),
  nextbit: z.record(z.string(), z.unknown()).optional(),
  nineteen: z.record(z.string(), z.unknown()).optional(),
  novita: z.record(z.string(), z.unknown()).optional(),
  nvidia: z.record(z.string(), z.unknown()).optional(),
  octoai: z.record(z.string(), z.unknown()).optional(),
  'open-inference': z.record(z.string(), z.unknown()).optional(),
  openai: z.record(z.string(), z.unknown()).optional(),
  parasail: z.record(z.string(), z.unknown()).optional(),
  perceptron: z.record(z.string(), z.unknown()).optional(),
  perplexity: z.record(z.string(), z.unknown()).optional(),
  phala: z.record(z.string(), z.unknown()).optional(),
  poolside: z.record(z.string(), z.unknown()).optional(),
  recraft: z.record(z.string(), z.unknown()).optional(),
  recursal: z.record(z.string(), z.unknown()).optional(),
  reflection: z.record(z.string(), z.unknown()).optional(),
  reka: z.record(z.string(), z.unknown()).optional(),
  relace: z.record(z.string(), z.unknown()).optional(),
  replicate: z.record(z.string(), z.unknown()).optional(),
  sambanova: z.record(z.string(), z.unknown()).optional(),
  'sambanova-cloaked': z.record(z.string(), z.unknown()).optional(),
  seed: z.record(z.string(), z.unknown()).optional(),
  'sf-compute': z.record(z.string(), z.unknown()).optional(),
  siliconflow: z.record(z.string(), z.unknown()).optional(),
  sourceful: z.record(z.string(), z.unknown()).optional(),
  stealth: z.record(z.string(), z.unknown()).optional(),
  stepfun: z.record(z.string(), z.unknown()).optional(),
  streamlake: z.record(z.string(), z.unknown()).optional(),
  switchpoint: z.record(z.string(), z.unknown()).optional(),
  targon: z.record(z.string(), z.unknown()).optional(),
  together: z.record(z.string(), z.unknown()).optional(),
  'together-lite': z.record(z.string(), z.unknown()).optional(),
  ubicloud: z.record(z.string(), z.unknown()).optional(),
  upstage: z.record(z.string(), z.unknown()).optional(),
  venice: z.record(z.string(), z.unknown()).optional(),
  wafer: z.record(z.string(), z.unknown()).optional(),
  wandb: z.record(z.string(), z.unknown()).optional(),
  xai: z.record(z.string(), z.unknown()).optional(),
  xiaomi: z.record(z.string(), z.unknown()).optional(),
  'z-ai': z.record(z.string(), z.unknown()).optional(),
})

/**
 * Error data for TooManyRequestsResponse
 */
export const zTooManyRequestsResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Too Many Requests - Rate limit exceeded
 */
export const zTooManyRequestsResponse = z.object({
  error: zTooManyRequestsResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

/**
 * Error data for UnauthorizedResponse
 */
export const zUnauthorizedResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Unauthorized - Authentication required or invalid credentials
 */
export const zUnauthorizedResponse = z.object({
  error: zUnauthorizedResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

export const zVideoGenerationRequest = z.object({
  aspect_ratio: z
    .enum(['16:9', '9:16', '1:1', '4:3', '3:4', '3:2', '2:3', '21:9', '9:21'])
    .optional(),
  callback_url: z.url().optional(),
  duration: z.int().gte(1).optional(),
  frame_images: z.array(zFrameImage).optional(),
  generate_audio: z.boolean().optional(),
  input_references: z.array(zInputReference).optional(),
  model: z.string(),
  prompt: z.string(),
  provider: z
    .object({
      options: zProviderOptions.and(z.unknown()).optional(),
    })
    .optional(),
  resolution: z.enum(['480p', '720p', '1080p', '1K', '2K', '4K']).optional(),
  seed: z.int().optional(),
  size: z.string().optional(),
})

/**
 * Alibaba: Wan 2.6 (alibaba/wan-2.6) — model-constrained video generation request. Alibaba's most advanced video generation model, supporting over 10 visual creation capabilities in a unified system. Wan 2.6 generates 1080p video at 24fps from text, images, reference videos, or audio,...
 */
export const zVideoGenerationRequestAlibabaWan26 = z.object({
  aspect_ratio: z.enum(['16:9', '9:16']).optional(),
  callback_url: z.url().optional(),
  duration: z.union([z.literal(5), z.literal(10)]).optional(),
  frame_images: z.array(zFrameImage).optional(),
  generate_audio: z.boolean().optional(),
  input_references: z.array(zInputReference).optional(),
  model: z.enum(['alibaba/wan-2.6']),
  prompt: z.string(),
  provider: z
    .object({
      options: zProviderOptions.and(z.unknown()).optional(),
    })
    .optional(),
  resolution: z.enum(['720p', '1080p']).optional(),
  seed: z.int().optional(),
  size: z.enum(['1280x720', '1080x1920', '720x1280', '1920x1080']).optional(),
})

/**
 * Alibaba: Wan 2.7 (alibaba/wan-2.7) — model-constrained video generation request. Wan 2.7 is a video generation model from Alibaba. It supports text-to-video, image-to-video with first and last frame control, and reference-to-video, where multiple reference images guide the style and content...
 */
export const zVideoGenerationRequestAlibabaWan27 = z.object({
  aspect_ratio: z.enum(['16:9', '9:16', '1:1', '4:3', '3:4']).optional(),
  callback_url: z.url().optional(),
  duration: z
    .union([
      z.literal(2),
      z.literal(3),
      z.literal(4),
      z.literal(5),
      z.literal(6),
      z.literal(7),
      z.literal(8),
      z.literal(9),
      z.literal(10),
    ])
    .optional(),
  frame_images: z.array(zFrameImage).optional(),
  generate_audio: z.boolean().optional(),
  input_references: z.array(zInputReference).optional(),
  model: z.enum(['alibaba/wan-2.7']),
  prompt: z.string(),
  provider: z
    .object({
      options: zProviderOptions.and(z.unknown()).optional(),
    })
    .optional(),
  resolution: z.enum(['720p', '1080p']).optional(),
  seed: z.int().optional(),
  size: z
    .enum([
      '1280x720',
      '720x1280',
      '1920x1080',
      '1080x1920',
      '720x720',
      '1080x1080',
      '960x720',
      '720x960',
      '1440x1080',
      '1080x1440',
    ])
    .optional(),
})

/**
 * ByteDance: Seedance 1.5 Pro (bytedance/seedance-1-5-pro) — model-constrained video generation request. ByteDance's next-generation audio-visual generation model with a 4.5B parameter Dual-Branch Diffusion Transformer architecture. Seedance 1.5 Pro generates video and audio simultaneously in a single unified pass — eliminating the timing...
 */
export const zVideoGenerationRequestBytedanceSeedance15Pro = z.object({
  aspect_ratio: z
    .enum(['1:1', '3:4', '9:16', '9:21', '4:3', '16:9', '21:9'])
    .optional(),
  callback_url: z.url().optional(),
  duration: z
    .union([
      z.literal(4),
      z.literal(5),
      z.literal(6),
      z.literal(7),
      z.literal(8),
      z.literal(9),
      z.literal(10),
      z.literal(11),
      z.literal(12),
    ])
    .optional(),
  frame_images: z.array(zFrameImage).optional(),
  generate_audio: z.boolean().optional(),
  input_references: z.array(zInputReference).optional(),
  model: z.enum(['bytedance/seedance-1-5-pro']),
  prompt: z.string(),
  provider: z
    .object({
      options: zProviderOptions.and(z.unknown()).optional(),
    })
    .optional(),
  resolution: z.enum(['480p', '720p', '1080p']).optional(),
  seed: z.int().optional(),
  size: z
    .enum([
      '480x480',
      '480x640',
      '480x854',
      '480x1120',
      '640x480',
      '720x720',
      '720x960',
      '720x1280',
      '720x1680',
      '854x480',
      '960x720',
      '1080x1080',
      '1080x1440',
      '1080x1920',
      '1080x2520',
      '1120x480',
      '1280x720',
      '1440x1080',
      '1680x720',
      '1920x1080',
      '2520x1080',
    ])
    .optional(),
})

/**
 * ByteDance: Seedance 2.0 (bytedance/seedance-2.0) — model-constrained video generation request. Seedance 2.0 is a video generation model from ByteDance. It supports text-to-video, image-to-video with first and last frame control, and multimodal reference-to-video. It is particularly strong at preserving character consistency,...
 */
export const zVideoGenerationRequestBytedanceSeedance20 = z.object({
  aspect_ratio: z
    .enum(['1:1', '3:4', '9:16', '4:3', '16:9', '21:9', '9:21'])
    .optional(),
  callback_url: z.url().optional(),
  duration: z
    .union([
      z.literal(4),
      z.literal(5),
      z.literal(6),
      z.literal(7),
      z.literal(8),
      z.literal(9),
      z.literal(10),
      z.literal(11),
      z.literal(12),
      z.literal(13),
      z.literal(14),
      z.literal(15),
    ])
    .optional(),
  frame_images: z.array(zFrameImage).optional(),
  generate_audio: z.boolean().optional(),
  input_references: z.array(zInputReference).optional(),
  model: z.enum(['bytedance/seedance-2.0']),
  prompt: z.string(),
  provider: z
    .object({
      options: zProviderOptions.and(z.unknown()).optional(),
    })
    .optional(),
  resolution: z.enum(['480p', '720p', '1080p']).optional(),
  seed: z.int().optional(),
  size: z
    .enum([
      '480x480',
      '480x640',
      '480x854',
      '640x480',
      '854x480',
      '1120x480',
      '720x720',
      '720x960',
      '720x1280',
      '720x1680',
      '960x720',
      '1280x720',
      '1680x720',
      '1080x1080',
      '1080x1440',
      '1080x1920',
      '1440x1080',
      '1920x1080',
      '2520x1080',
    ])
    .optional(),
})

/**
 * ByteDance: Seedance 2.0 Fast (bytedance/seedance-2.0-fast) — model-constrained video generation request. Seedance 2.0 Fast is a video generation model from ByteDance. It supports text-to-video, image-to-video with first and last frame control, and multimodal reference-to-video. It prioritizes generation speed and lower cost...
 */
export const zVideoGenerationRequestBytedanceSeedance20Fast = z.object({
  aspect_ratio: z
    .enum(['1:1', '3:4', '9:16', '4:3', '16:9', '21:9', '9:21'])
    .optional(),
  callback_url: z.url().optional(),
  duration: z
    .union([
      z.literal(4),
      z.literal(5),
      z.literal(6),
      z.literal(7),
      z.literal(8),
      z.literal(9),
      z.literal(10),
      z.literal(11),
      z.literal(12),
      z.literal(13),
      z.literal(14),
      z.literal(15),
    ])
    .optional(),
  frame_images: z.array(zFrameImage).optional(),
  generate_audio: z.boolean().optional(),
  input_references: z.array(zInputReference).optional(),
  model: z.enum(['bytedance/seedance-2.0-fast']),
  prompt: z.string(),
  provider: z
    .object({
      options: zProviderOptions.and(z.unknown()).optional(),
    })
    .optional(),
  resolution: z.enum(['480p', '720p']).optional(),
  seed: z.int().optional(),
  size: z
    .enum([
      '480x480',
      '480x640',
      '480x854',
      '640x480',
      '854x480',
      '1120x480',
      '720x720',
      '720x960',
      '720x1280',
      '720x1680',
      '960x720',
      '1280x720',
      '1680x720',
    ])
    .optional(),
})

/**
 * Google: Veo 3.1 (google/veo-3.1) — model-constrained video generation request. Google's state-of-the-art video generation model, built for maximum visual fidelity in final production cuts. Veo 3.1 generates high-quality 1080p video from text or image prompts with native synchronized audio —...
 */
export const zVideoGenerationRequestGoogleVeo31 = z.object({
  aspect_ratio: z.enum(['16:9', '9:16']).optional(),
  callback_url: z.url().optional(),
  duration: z.union([z.literal(4), z.literal(6), z.literal(8)]).optional(),
  frame_images: z.array(zFrameImage).optional(),
  generate_audio: z.boolean().optional(),
  input_references: z.array(zInputReference).optional(),
  model: z.enum(['google/veo-3.1']),
  prompt: z.string(),
  provider: z
    .object({
      options: zProviderOptions.and(z.unknown()).optional(),
    })
    .optional(),
  resolution: z.enum(['720p', '1080p', '4K']).optional(),
  seed: z.int().optional(),
  size: z
    .enum([
      '1280x720',
      '1080x1920',
      '1920x1080',
      '720x1280',
      '3840x2160',
      '2160x3840',
    ])
    .optional(),
})

/**
 * Google: Veo 3.1 Fast (google/veo-3.1-fast) — model-constrained video generation request. Google's mid-tier video generation model balancing speed and quality. Veo 3.1 Fast generates high-quality video from text or image prompts with native synchronized audio, offering faster turnaround than Veo 3.1...
 */
export const zVideoGenerationRequestGoogleVeo31Fast = z.object({
  aspect_ratio: z.enum(['16:9', '9:16']).optional(),
  callback_url: z.url().optional(),
  duration: z.union([z.literal(4), z.literal(6), z.literal(8)]).optional(),
  frame_images: z.array(zFrameImage).optional(),
  generate_audio: z.boolean().optional(),
  input_references: z.array(zInputReference).optional(),
  model: z.enum(['google/veo-3.1-fast']),
  prompt: z.string(),
  provider: z
    .object({
      options: zProviderOptions.and(z.unknown()).optional(),
    })
    .optional(),
  resolution: z.enum(['720p', '1080p', '4K']).optional(),
  seed: z.int().optional(),
  size: z
    .enum([
      '1280x720',
      '1080x1920',
      '1920x1080',
      '720x1280',
      '3840x2160',
      '2160x3840',
    ])
    .optional(),
})

/**
 * Google: Veo 3.1 Lite (google/veo-3.1-lite) — model-constrained video generation request. Google's most cost-effective video generation model, designed for high-volume applications and rapid iteration. Veo 3.1 Lite generates 720p and 1080p video from text or image prompts with native synchronized audio...
 */
export const zVideoGenerationRequestGoogleVeo31Lite = z.object({
  aspect_ratio: z.enum(['16:9', '9:16']).optional(),
  callback_url: z.url().optional(),
  duration: z.union([z.literal(8), z.literal(4), z.literal(6)]).optional(),
  frame_images: z.array(zFrameImage).optional(),
  generate_audio: z.boolean().optional(),
  input_references: z.array(zInputReference).optional(),
  model: z.enum(['google/veo-3.1-lite']),
  prompt: z.string(),
  provider: z
    .object({
      options: zProviderOptions.and(z.unknown()).optional(),
    })
    .optional(),
  resolution: z.enum(['720p', '1080p']).optional(),
  seed: z.int().optional(),
  size: z.enum(['1280x720', '720x1280', '1920x1080', '1080x1920']).optional(),
})

/**
 * Kling: Video v3.0 Pro (kwaivgi/kling-v3.0-pro) — model-constrained video generation request. Kling v3.0 Pro is Kuaishou's premium video generation model, offering higher visual quality than the Standard tier. It supports text-to-video and image-to-video workflows, with first-frame and last-frame control for precise...
 */
export const zVideoGenerationRequestKwaivgiKlingV30Pro = z.object({
  aspect_ratio: z.enum(['16:9', '9:16', '1:1']).optional(),
  callback_url: z.url().optional(),
  duration: z
    .union([
      z.literal(3),
      z.literal(4),
      z.literal(5),
      z.literal(6),
      z.literal(7),
      z.literal(8),
      z.literal(9),
      z.literal(10),
      z.literal(11),
      z.literal(12),
      z.literal(13),
      z.literal(14),
      z.literal(15),
    ])
    .optional(),
  frame_images: z.array(zFrameImage).optional(),
  generate_audio: z.boolean().optional(),
  input_references: z.array(zInputReference).optional(),
  model: z.enum(['kwaivgi/kling-v3.0-pro']),
  prompt: z.string(),
  provider: z
    .object({
      options: zProviderOptions.and(z.unknown()).optional(),
    })
    .optional(),
  resolution: z.enum(['720p']).optional(),
  size: z.enum(['1280x720', '720x1280', '720x720']).optional(),
})

/**
 * Kling: Video v3.0 Standard (kwaivgi/kling-v3.0-std) — model-constrained video generation request. Kling v3.0 Standard is a video generation model from Kuaishou. It supports text-to-video and image-to-video workflows, with first-frame and last-frame control for guided scene composition. Clips range from 3 to...
 */
export const zVideoGenerationRequestKwaivgiKlingV30Std = z.object({
  aspect_ratio: z.enum(['16:9', '9:16', '1:1']).optional(),
  callback_url: z.url().optional(),
  duration: z
    .union([
      z.literal(3),
      z.literal(4),
      z.literal(5),
      z.literal(6),
      z.literal(7),
      z.literal(8),
      z.literal(9),
      z.literal(10),
      z.literal(11),
      z.literal(12),
      z.literal(13),
      z.literal(14),
      z.literal(15),
    ])
    .optional(),
  frame_images: z.array(zFrameImage).optional(),
  generate_audio: z.boolean().optional(),
  input_references: z.array(zInputReference).optional(),
  model: z.enum(['kwaivgi/kling-v3.0-std']),
  prompt: z.string(),
  provider: z
    .object({
      options: zProviderOptions.and(z.unknown()).optional(),
    })
    .optional(),
  resolution: z.enum(['720p']).optional(),
  size: z.enum(['1280x720', '720x1280', '720x720']).optional(),
})

/**
 * Kling: Video O1 (kwaivgi/kling-video-o1) — model-constrained video generation request. Kling Video O1 is a video generation model from Kuaishou. It supports text and image inputs with video output, enabling text-to-video and image-to-video workflows. It is suited for cinematic content...
 */
export const zVideoGenerationRequestKwaivgiKlingVideoO1 = z.object({
  aspect_ratio: z.enum(['16:9', '9:16', '1:1']).optional(),
  callback_url: z.url().optional(),
  duration: z.union([z.literal(5), z.literal(10)]).optional(),
  frame_images: z.array(zFrameImage).optional(),
  generate_audio: z.boolean().optional(),
  input_references: z.array(zInputReference).optional(),
  model: z.enum(['kwaivgi/kling-video-o1']),
  prompt: z.string(),
  provider: z
    .object({
      options: zProviderOptions.and(z.unknown()).optional(),
    })
    .optional(),
  resolution: z.enum(['720p']).optional(),
  size: z.enum(['1280x720', '720x1280', '720x720']).optional(),
})

/**
 * MiniMax: Hailuo 2.3 (minimax/hailuo-2.3) — model-constrained video generation request. Hailuo 2.3 is a video generation model from MiniMax. It accepts text prompts and reference images as input and generates video output, supporting both text-to-video and image-to-video workflows. It is...
 */
export const zVideoGenerationRequestMinimaxHailuo23 = z.object({
  aspect_ratio: z.enum(['16:9']).optional(),
  callback_url: z.url().optional(),
  duration: z.union([z.literal(6), z.literal(10)]).optional(),
  frame_images: z.array(zFrameImage).optional(),
  input_references: z.array(zInputReference).optional(),
  model: z.enum(['minimax/hailuo-2.3']),
  prompt: z.string(),
  provider: z
    .object({
      options: zProviderOptions.and(z.unknown()).optional(),
    })
    .optional(),
  resolution: z.enum(['1080p']).optional(),
  size: z.enum(['1920x1080']).optional(),
})

/**
 * OpenAI: Sora 2 Pro (openai/sora-2-pro) — model-constrained video generation request. OpenAI's flagship video generation model, delivering production-quality video with physics-accurate motion, synchronized audio, and world-state persistence across shots. Sora 2 Pro follows intricate multi-shot instructions while maintaining consistent spatial relationships...
 */
export const zVideoGenerationRequestOpenaiSora2Pro = z.object({
  aspect_ratio: z.enum(['16:9', '9:16']).optional(),
  callback_url: z.url().optional(),
  duration: z
    .union([
      z.literal(4),
      z.literal(8),
      z.literal(12),
      z.literal(16),
      z.literal(20),
    ])
    .optional(),
  generate_audio: z.boolean().optional(),
  input_references: z.array(zInputReference).optional(),
  model: z.enum(['openai/sora-2-pro']),
  prompt: z.string(),
  provider: z
    .object({
      options: zProviderOptions.and(z.unknown()).optional(),
    })
    .optional(),
  resolution: z.enum(['720p', '1080p']).optional(),
  size: z.enum(['1280x720', '1080x1920', '1920x1080', '720x1280']).optional(),
})

/**
 * xAI: Grok Imagine Video (x-ai/grok-imagine-video) — model-constrained video generation request. Grok Imagine Video is xAI's fast, text-, image-, and reference-conditioned video generation model. It produces short videos (1–15 seconds, 24 fps) at 480p or 720p across seven aspect ratios -...
 */
export const zVideoGenerationRequestXAiGrokImagineVideo = z.object({
  aspect_ratio: z
    .enum(['16:9', '9:16', '1:1', '4:3', '3:4', '3:2', '2:3'])
    .optional(),
  callback_url: z.url().optional(),
  duration: z
    .union([
      z.literal(1),
      z.literal(2),
      z.literal(3),
      z.literal(4),
      z.literal(5),
      z.literal(6),
      z.literal(7),
      z.literal(8),
      z.literal(9),
      z.literal(10),
      z.literal(11),
      z.literal(12),
      z.literal(13),
      z.literal(14),
      z.literal(15),
    ])
    .optional(),
  frame_images: z.array(zFrameImage).optional(),
  input_references: z.array(zInputReference).optional(),
  model: z.enum(['x-ai/grok-imagine-video']),
  prompt: z.string(),
  provider: z
    .object({
      options: zProviderOptions.and(z.unknown()).optional(),
    })
    .optional(),
  resolution: z.enum(['480p', '720p']).optional(),
  size: z
    .enum([
      '854x480',
      '1280x720',
      '480x854',
      '720x1280',
      '480x480',
      '720x720',
      '640x480',
      '960x720',
      '480x640',
      '720x960',
      '720x480',
      '1080x720',
      '480x720',
      '720x1080',
    ])
    .optional(),
})

/**
 * Usage and cost information for the video generation. Available once the job has completed.
 */
export const zVideoGenerationUsage = z.object({
  cost: z.number().nullish(),
  is_byok: z.boolean().optional(),
})

export const zVideoGenerationResponse = z.object({
  error: z.string().optional(),
  generation_id: z.string().optional(),
  id: z.string(),
  polling_url: z.string(),
  status: z.enum([
    'pending',
    'in_progress',
    'completed',
    'failed',
    'cancelled',
    'expired',
  ]),
  unsigned_urls: z.array(z.string()).optional(),
  usage: zVideoGenerationUsage.optional(),
})

export const zCreateVideosBody = zVideoGenerationRequest

/**
 * Video generation request accepted
 */
export const zCreateVideosResponse = zVideoGenerationResponse

export const zCreateVideoAlibabaWan26Body = zVideoGenerationRequestAlibabaWan26

/**
 * Video generation request accepted
 */
export const zCreateVideoAlibabaWan26Response = zVideoGenerationResponse

export const zCreateVideoAlibabaWan27Body = zVideoGenerationRequestAlibabaWan27

/**
 * Video generation request accepted
 */
export const zCreateVideoAlibabaWan27Response = zVideoGenerationResponse

export const zCreateVideoBytedanceSeedance15ProBody =
  zVideoGenerationRequestBytedanceSeedance15Pro

/**
 * Video generation request accepted
 */
export const zCreateVideoBytedanceSeedance15ProResponse =
  zVideoGenerationResponse

export const zCreateVideoBytedanceSeedance20Body =
  zVideoGenerationRequestBytedanceSeedance20

/**
 * Video generation request accepted
 */
export const zCreateVideoBytedanceSeedance20Response = zVideoGenerationResponse

export const zCreateVideoBytedanceSeedance20FastBody =
  zVideoGenerationRequestBytedanceSeedance20Fast

/**
 * Video generation request accepted
 */
export const zCreateVideoBytedanceSeedance20FastResponse =
  zVideoGenerationResponse

export const zCreateVideoGoogleVeo31Body = zVideoGenerationRequestGoogleVeo31

/**
 * Video generation request accepted
 */
export const zCreateVideoGoogleVeo31Response = zVideoGenerationResponse

export const zCreateVideoGoogleVeo31FastBody =
  zVideoGenerationRequestGoogleVeo31Fast

/**
 * Video generation request accepted
 */
export const zCreateVideoGoogleVeo31FastResponse = zVideoGenerationResponse

export const zCreateVideoGoogleVeo31LiteBody =
  zVideoGenerationRequestGoogleVeo31Lite

/**
 * Video generation request accepted
 */
export const zCreateVideoGoogleVeo31LiteResponse = zVideoGenerationResponse

export const zCreateVideoKwaivgiKlingV30ProBody =
  zVideoGenerationRequestKwaivgiKlingV30Pro

/**
 * Video generation request accepted
 */
export const zCreateVideoKwaivgiKlingV30ProResponse = zVideoGenerationResponse

export const zCreateVideoKwaivgiKlingV30StdBody =
  zVideoGenerationRequestKwaivgiKlingV30Std

/**
 * Video generation request accepted
 */
export const zCreateVideoKwaivgiKlingV30StdResponse = zVideoGenerationResponse

export const zCreateVideoKwaivgiKlingVideoO1Body =
  zVideoGenerationRequestKwaivgiKlingVideoO1

/**
 * Video generation request accepted
 */
export const zCreateVideoKwaivgiKlingVideoO1Response = zVideoGenerationResponse

export const zCreateVideoMinimaxHailuo23Body =
  zVideoGenerationRequestMinimaxHailuo23

/**
 * Video generation request accepted
 */
export const zCreateVideoMinimaxHailuo23Response = zVideoGenerationResponse

export const zCreateVideoOpenaiSora2ProBody =
  zVideoGenerationRequestOpenaiSora2Pro

/**
 * Video generation request accepted
 */
export const zCreateVideoOpenaiSora2ProResponse = zVideoGenerationResponse

export const zCreateVideoXAiGrokImagineVideoBody =
  zVideoGenerationRequestXAiGrokImagineVideo

/**
 * Video generation request accepted
 */
export const zCreateVideoXAiGrokImagineVideoResponse = zVideoGenerationResponse
