// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod'

/**
 * Error data for BadGatewayResponse
 */
export const zBadGatewayResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Bad Gateway - Provider/upstream API failure
 */
export const zBadGatewayResponse = z.object({
  error: zBadGatewayResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

/**
 * Error data for BadRequestResponse
 */
export const zBadRequestResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Bad Request - Invalid request parameters or malformed input
 */
export const zBadRequestResponse = z.object({
  error: zBadRequestResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

/**
 * Error data for EdgeNetworkTimeoutResponse
 */
export const zEdgeNetworkTimeoutResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Infrastructure Timeout - Provider request timed out at edge network
 */
export const zEdgeNetworkTimeoutResponse = z.object({
  error: zEdgeNetworkTimeoutResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

/**
 * Error data for InternalServerResponse
 */
export const zInternalServerResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Internal Server Error - Unexpected server error
 */
export const zInternalServerResponse = z.object({
  error: zInternalServerResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

/**
 * Error data for NotFoundResponse
 */
export const zNotFoundResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Not Found - Resource does not exist
 */
export const zNotFoundResponse = z.object({
  error: zNotFoundResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

/**
 * Error data for PaymentRequiredResponse
 */
export const zPaymentRequiredResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Payment Required - Insufficient credits or quota to complete request
 */
export const zPaymentRequiredResponse = z.object({
  error: zPaymentRequiredResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

/**
 * Provider-specific options keyed by provider slug. The options for the matched provider are spread into the upstream request body.
 */
export const zProviderOptions = z.object({
  '01ai': z.record(z.string(), z.unknown()).optional(),
  ai21: z.record(z.string(), z.unknown()).optional(),
  'aion-labs': z.record(z.string(), z.unknown()).optional(),
  akashml: z.record(z.string(), z.unknown()).optional(),
  alibaba: z.record(z.string(), z.unknown()).optional(),
  'amazon-bedrock': z.record(z.string(), z.unknown()).optional(),
  'amazon-nova': z.record(z.string(), z.unknown()).optional(),
  ambient: z.record(z.string(), z.unknown()).optional(),
  anthropic: z.record(z.string(), z.unknown()).optional(),
  anyscale: z.record(z.string(), z.unknown()).optional(),
  'arcee-ai': z.record(z.string(), z.unknown()).optional(),
  'atlas-cloud': z.record(z.string(), z.unknown()).optional(),
  atoma: z.record(z.string(), z.unknown()).optional(),
  avian: z.record(z.string(), z.unknown()).optional(),
  azure: z.record(z.string(), z.unknown()).optional(),
  baidu: z.record(z.string(), z.unknown()).optional(),
  baseten: z.record(z.string(), z.unknown()).optional(),
  'black-forest-labs': z.record(z.string(), z.unknown()).optional(),
  byteplus: z.record(z.string(), z.unknown()).optional(),
  centml: z.record(z.string(), z.unknown()).optional(),
  cerebras: z.record(z.string(), z.unknown()).optional(),
  chutes: z.record(z.string(), z.unknown()).optional(),
  cirrascale: z.record(z.string(), z.unknown()).optional(),
  clarifai: z.record(z.string(), z.unknown()).optional(),
  cloudflare: z.record(z.string(), z.unknown()).optional(),
  cohere: z.record(z.string(), z.unknown()).optional(),
  crofai: z.record(z.string(), z.unknown()).optional(),
  crucible: z.record(z.string(), z.unknown()).optional(),
  crusoe: z.record(z.string(), z.unknown()).optional(),
  darkbloom: z.record(z.string(), z.unknown()).optional(),
  decart: z.record(z.string(), z.unknown()).optional(),
  deepinfra: z.record(z.string(), z.unknown()).optional(),
  deepseek: z.record(z.string(), z.unknown()).optional(),
  dekallm: z.record(z.string(), z.unknown()).optional(),
  digitalocean: z.record(z.string(), z.unknown()).optional(),
  enfer: z.record(z.string(), z.unknown()).optional(),
  'fake-provider': z.record(z.string(), z.unknown()).optional(),
  featherless: z.record(z.string(), z.unknown()).optional(),
  fireworks: z.record(z.string(), z.unknown()).optional(),
  friendli: z.record(z.string(), z.unknown()).optional(),
  gmicloud: z.record(z.string(), z.unknown()).optional(),
  'google-ai-studio': z.record(z.string(), z.unknown()).optional(),
  'google-vertex': z.record(z.string(), z.unknown()).optional(),
  gopomelo: z.record(z.string(), z.unknown()).optional(),
  groq: z.record(z.string(), z.unknown()).optional(),
  huggingface: z.record(z.string(), z.unknown()).optional(),
  hyperbolic: z.record(z.string(), z.unknown()).optional(),
  'hyperbolic-quantized': z.record(z.string(), z.unknown()).optional(),
  inception: z.record(z.string(), z.unknown()).optional(),
  inceptron: z.record(z.string(), z.unknown()).optional(),
  'inference-net': z.record(z.string(), z.unknown()).optional(),
  infermatic: z.record(z.string(), z.unknown()).optional(),
  inflection: z.record(z.string(), z.unknown()).optional(),
  inocloud: z.record(z.string(), z.unknown()).optional(),
  'io-net': z.record(z.string(), z.unknown()).optional(),
  ionstream: z.record(z.string(), z.unknown()).optional(),
  klusterai: z.record(z.string(), z.unknown()).optional(),
  lambda: z.record(z.string(), z.unknown()).optional(),
  lepton: z.record(z.string(), z.unknown()).optional(),
  liquid: z.record(z.string(), z.unknown()).optional(),
  lynn: z.record(z.string(), z.unknown()).optional(),
  'lynn-private': z.record(z.string(), z.unknown()).optional(),
  mancer: z.record(z.string(), z.unknown()).optional(),
  'mancer-old': z.record(z.string(), z.unknown()).optional(),
  mara: z.record(z.string(), z.unknown()).optional(),
  meta: z.record(z.string(), z.unknown()).optional(),
  minimax: z.record(z.string(), z.unknown()).optional(),
  mistral: z.record(z.string(), z.unknown()).optional(),
  modal: z.record(z.string(), z.unknown()).optional(),
  modelrun: z.record(z.string(), z.unknown()).optional(),
  modular: z.record(z.string(), z.unknown()).optional(),
  moonshotai: z.record(z.string(), z.unknown()).optional(),
  morph: z.record(z.string(), z.unknown()).optional(),
  ncompass: z.record(z.string(), z.unknown()).optional(),
  nebius: z.record(z.string(), z.unknown()).optional(),
  'nex-agi': z.record(z.string(), z.unknown()).optional(),
  nextbit: z.record(z.string(), z.unknown()).optional(),
  nineteen: z.record(z.string(), z.unknown()).optional(),
  novita: z.record(z.string(), z.unknown()).optional(),
  nvidia: z.record(z.string(), z.unknown()).optional(),
  octoai: z.record(z.string(), z.unknown()).optional(),
  'open-inference': z.record(z.string(), z.unknown()).optional(),
  openai: z.record(z.string(), z.unknown()).optional(),
  parasail: z.record(z.string(), z.unknown()).optional(),
  perceptron: z.record(z.string(), z.unknown()).optional(),
  perplexity: z.record(z.string(), z.unknown()).optional(),
  phala: z.record(z.string(), z.unknown()).optional(),
  poolside: z.record(z.string(), z.unknown()).optional(),
  recraft: z.record(z.string(), z.unknown()).optional(),
  recursal: z.record(z.string(), z.unknown()).optional(),
  reflection: z.record(z.string(), z.unknown()).optional(),
  reka: z.record(z.string(), z.unknown()).optional(),
  relace: z.record(z.string(), z.unknown()).optional(),
  replicate: z.record(z.string(), z.unknown()).optional(),
  sambanova: z.record(z.string(), z.unknown()).optional(),
  'sambanova-cloaked': z.record(z.string(), z.unknown()).optional(),
  seed: z.record(z.string(), z.unknown()).optional(),
  'sf-compute': z.record(z.string(), z.unknown()).optional(),
  siliconflow: z.record(z.string(), z.unknown()).optional(),
  sourceful: z.record(z.string(), z.unknown()).optional(),
  stealth: z.record(z.string(), z.unknown()).optional(),
  stepfun: z.record(z.string(), z.unknown()).optional(),
  streamlake: z.record(z.string(), z.unknown()).optional(),
  switchpoint: z.record(z.string(), z.unknown()).optional(),
  targon: z.record(z.string(), z.unknown()).optional(),
  together: z.record(z.string(), z.unknown()).optional(),
  'together-lite': z.record(z.string(), z.unknown()).optional(),
  ubicloud: z.record(z.string(), z.unknown()).optional(),
  upstage: z.record(z.string(), z.unknown()).optional(),
  venice: z.record(z.string(), z.unknown()).optional(),
  wafer: z.record(z.string(), z.unknown()).optional(),
  wandb: z.record(z.string(), z.unknown()).optional(),
  xai: z.record(z.string(), z.unknown()).optional(),
  xiaomi: z.record(z.string(), z.unknown()).optional(),
  'z-ai': z.record(z.string(), z.unknown()).optional(),
})

/**
 * Error data for ProviderOverloadedResponse
 */
export const zProviderOverloadedResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Provider Overloaded - Provider is temporarily overloaded
 */
export const zProviderOverloadedResponse = z.object({
  error: zProviderOverloadedResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

/**
 * Error data for ServiceUnavailableResponse
 */
export const zServiceUnavailableResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Service Unavailable - Service temporarily unavailable
 */
export const zServiceUnavailableResponse = z.object({
  error: zServiceUnavailableResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

/**
 * Text-to-speech request input
 */
export const zSpeechRequest = z.object({
  input: z.string(),
  model: z.string(),
  provider: z
    .object({
      options: zProviderOptions.optional(),
    })
    .optional(),
  response_format: z.enum(['mp3', 'pcm']).optional().default('pcm'),
  speed: z.number().optional(),
  voice: z.string(),
})

/**
 * Base64-encoded audio to transcribe
 */
export const zSttInputAudio = z.object({
  data: z.string(),
  format: z.string(),
})

/**
 * Speech-to-text request input. Accepts a JSON body with input_audio containing base64-encoded audio.
 */
export const zSttRequest = z.object({
  input_audio: zSttInputAudio,
  language: z.string().optional(),
  model: z.string(),
  provider: z
    .object({
      options: zProviderOptions.optional(),
    })
    .optional(),
  temperature: z.number().optional(),
})

/**
 * Aggregated usage statistics for the request
 */
export const zSttUsage = z.object({
  cost: z.number().optional(),
  input_tokens: z.int().optional(),
  output_tokens: z.int().optional(),
  seconds: z.number().optional(),
  total_tokens: z.int().optional(),
})

/**
 * STT response containing transcribed text and optional usage statistics
 */
export const zSttResponse = z.object({
  text: z.string(),
  usage: zSttUsage.optional(),
})

/**
 * Error data for TooManyRequestsResponse
 */
export const zTooManyRequestsResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Too Many Requests - Rate limit exceeded
 */
export const zTooManyRequestsResponse = z.object({
  error: zTooManyRequestsResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

/**
 * Error data for UnauthorizedResponse
 */
export const zUnauthorizedResponseErrorData = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.record(z.string(), z.unknown()).nullish(),
})

/**
 * Unauthorized - Authentication required or invalid credentials
 */
export const zUnauthorizedResponse = z.object({
  error: zUnauthorizedResponseErrorData,
  openrouter_metadata: z.record(z.string(), z.unknown()).nullish(),
  user_id: z.string().nullish(),
})

export const zCreateAudioSpeechBody = zSpeechRequest

/**
 * Raw audio bytestream. Content-Type varies by requested format (audio/mpeg for mp3, audio/pcm for pcm — 16-bit little-endian).
 */
export const zCreateAudioSpeechResponse = z.string()

export const zCreateAudioTranscriptionsBody = zSttRequest

/**
 * Transcription result
 */
export const zCreateAudioTranscriptionsResponse = zSttResponse
