// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod'

/**
 * Aesthetics
 */
export const zAesthetics = z.object({
  color_scheme: z.union([z.string(), z.unknown()]).optional(),
  mood_atmosphere: z.union([z.string(), z.unknown()]).optional(),
  composition: z.union([z.string(), z.unknown()]).optional(),
})

/**
 * AestheticsDetails
 *
 * Aesthetic analysis of the image.
 */
export const zAestheticsDetails = z.object({
  mood_atmosphere: z.string(),
  preference_score: z.string(),
  composition: z.string(),
  aesthetic_score: z.string(),
  color_scheme: z.string(),
})

/**
 * Aesthetics
 */
export const zAestheticsType2 = z.object({
  preference_score: z.string(),
  composition: z.union([z.string(), z.unknown()]).optional(),
  mood_atmosphere: z.union([z.string(), z.unknown()]).optional(),
  aesthetic_score: z.string(),
  color_scheme: z.union([z.string(), z.unknown()]).optional(),
})

/**
 * Audio
 */
export const zAudio = z.object({
  bitrate: z.int(),
  file_name: z.string(),
  content_type: z.string(),
  url: z.string(),
  channels: z.int(),
  duration: z.number(),
  sample_rate: z.int(),
  file_size: z.int(),
  media_type: z.string().optional().default('audio'),
  container: z.string(),
  codec: z.string(),
})

/**
 * AudioTrack
 */
export const zAudioTrack = z.object({
  bitrate: z.int(),
  codec: z.string(),
  sample_rate: z.int(),
  channels: z.int(),
})

/**
 * ImageUnderstandingInput
 */
export const zBagelUnderstandInput = z.object({
  prompt: z.string(),
  image_url: z.string(),
  seed: z.int().optional(),
})

/**
 * TextOutput
 */
export const zBagelUnderstandOutput = z.object({
  text: z.string(),
  prompt: z.string(),
  seed: z.int(),
  timings: z.record(z.string(), z.unknown()),
})

/**
 * LoudnormInput
 */
export const zFfmpegApiLoudnormInput = z.object({
  loudness_range: z.number().gte(1).lte(20).optional().default(7),
  measured_tp: z.union([z.number().gte(-99).lte(99), z.unknown()]).optional(),
  true_peak: z.number().gte(-9).lte(0).optional().default(-0.1),
  measured_i: z.union([z.number().gte(-99).lte(0), z.unknown()]).optional(),
  offset: z.number().gte(-99).lte(99).optional().default(0),
  audio_url: z.string(),
  integrated_loudness: z.number().gte(-70).lte(-5).optional().default(-18),
  linear: z.boolean().optional().default(false),
  print_summary: z.boolean().optional().default(false),
  measured_lra: z.union([z.number().gte(0).lte(99), z.unknown()]).optional(),
  measured_thresh: z
    .union([z.number().gte(-99).lte(0), z.unknown()])
    .optional(),
  dual_mono: z.boolean().optional().default(false),
})

/**
 * MetadataInput
 */
export const zFfmpegApiMetadataInput = z.object({
  media_url: z.string(),
  extract_frames: z.boolean().optional().default(false),
})

/**
 * WaveformInput
 */
export const zFfmpegApiWaveformInput = z.object({
  media_url: z.string(),
  precision: z.int().gte(1).lte(6).optional().default(2),
  points_per_second: z.number().gte(1).lte(10).optional().default(4),
  smoothing_window: z.int().gte(1).lte(21).optional().default(3),
})

/**
 * WaveformOutput
 */
export const zFfmpegApiWaveformOutput = z.object({
  precision: z.int(),
  duration: z.number(),
  waveform: z.array(z.number()),
  points: z.int(),
})

/**
 * StructuredInstructionInputModel
 */
export const zFiboEditEditStructuredInstructionInput = z.object({
  seed: z.int().optional().default(5555),
  image_url: z.union([z.string(), z.unknown()]).optional(),
  mask_url: z.union([z.string(), z.unknown()]).optional(),
  sync_mode: z.boolean().optional().default(false),
  instruction: z.union([z.string(), z.unknown()]).optional(),
})

export const zFiboEditEditStructuredInstructionOutput = z.unknown()

export const zFiboGenerateStructuredPromptOutput = z.unknown()

export const zFiboLiteGenerateStructuredPromptLiteOutput = z.unknown()

export const zFiboLiteGenerateStructuredPromptOutput = z.unknown()

/**
 * File
 */
export const zFile = z.object({
  file_size: z.union([z.int(), z.unknown()]).optional(),
  file_name: z.union([z.string(), z.unknown()]).optional(),
  content_type: z.union([z.string(), z.unknown()]).optional(),
  url: z.string(),
})

/**
 * Lighting
 */
export const zLighting = z.object({
  conditions: z.union([z.string(), z.unknown()]).optional(),
  direction: z.union([z.string(), z.unknown()]).optional(),
  shadows: z.union([z.string(), z.unknown()]).optional(),
})

/**
 * LightingDetails
 *
 * Lighting information for the image.
 */
export const zLightingDetails = z.object({
  conditions: z.string(),
  direction: z.string(),
  shadows: z.union([z.string(), z.unknown()]).optional(),
})

/**
 * LoudnormSummary
 */
export const zLoudnormSummary = z.object({
  normalization_type: z.union([z.string(), z.unknown()]).optional(),
  input_true_peak: z.union([z.number(), z.unknown()]).optional(),
  output_integrated: z.union([z.number(), z.unknown()]).optional(),
  input_integrated: z.union([z.number(), z.unknown()]).optional(),
  output_threshold: z.union([z.number(), z.unknown()]).optional(),
  target_offset: z.union([z.number(), z.unknown()]).optional(),
  input_threshold: z.union([z.number(), z.unknown()]).optional(),
  output_lra: z.union([z.number(), z.unknown()]).optional(),
  input_lra: z.union([z.number(), z.unknown()]).optional(),
  output_true_peak: z.union([z.number(), z.unknown()]).optional(),
})

/**
 * LoudnormOutput
 */
export const zFfmpegApiLoudnormOutput = z.object({
  summary: z.union([zLoudnormSummary, z.unknown()]).optional(),
  audio: zFile,
})

/**
 * ObjectDescription
 *
 * Detailed object description with all attributes.
 */
export const zObjectDescription = z.object({
  pose: z.union([z.string(), z.unknown()]).optional(),
  number_of_objects: z.union([z.int(), z.unknown()]).optional(),
  action: z.union([z.string(), z.unknown()]).optional(),
  expression: z.union([z.string(), z.unknown()]).optional(),
  gender: z.union([z.string(), z.unknown()]).optional(),
  description: z.string(),
  clothing: z.union([z.string(), z.unknown()]).optional(),
  orientation: z.union([z.string(), z.unknown()]).optional(),
  skin_tone_and_texture: z.union([z.string(), z.unknown()]).optional(),
  shape_and_color: z.union([z.string(), z.unknown()]).optional(),
  location: z.string(),
  relationship: z.string(),
  appearance_details: z.union([z.string(), z.unknown()]).optional(),
  texture: z.union([z.string(), z.unknown()]).optional(),
  relative_size: z.union([z.string(), z.unknown()]).optional(),
})

/**
 * ImageToLottieInput
 */
export const zOmnilottieImageToLottieInput = z.object({
  image_url: z.string(),
  top_p: z.number().gte(0).lte(1).optional().default(0.25),
  temperature: z.number().gte(0).lte(2).optional().default(0.9),
  max_tokens: z.int().gte(256).lte(8192).optional().default(4096),
  prompt: z.string().max(2000),
  top_k: z.int().gte(1).lte(100).optional().default(5),
})

/**
 * LottieOutput
 */
export const zOmnilottieImageToLottieOutput = z.object({
  lottie_file: zFile,
})

/**
 * TextToLottieInput
 */
export const zOmnilottieInput = z.object({
  max_tokens: z.int().gte(256).lte(8192).optional().default(4096),
  top_p: z.number().gte(0).lte(1).optional().default(0.25),
  temperature: z.number().gte(0).lte(2).optional().default(0.9),
  prompt: z.string().max(2000),
  top_k: z.int().gte(1).lte(100).optional().default(5),
})

/**
 * LottieOutput
 */
export const zOmnilottieOutput = z.object({
  lottie_file: zFile,
})

/**
 * VideoToLottieInput
 */
export const zOmnilottieVideoToLottieInput = z.object({
  max_tokens: z.int().gte(256).lte(8192).optional().default(4096),
  top_p: z.number().gte(0).lte(1).optional().default(0.25),
  temperature: z.number().gte(0).lte(2).optional().default(0.9),
  prompt: z.union([z.string().max(2000), z.unknown()]).optional(),
  video_url: z.string(),
  top_k: z.int().gte(1).lte(100).optional().default(5),
})

/**
 * LottieOutput
 */
export const zOmnilottieVideoToLottieOutput = z.object({
  lottie_file: zFile,
})

/**
 * PhotographicCharacteristics
 */
export const zPhotographicCharacteristics = z.object({
  camera_angle: z.union([z.string(), z.unknown()]).optional(),
  focus: z.union([z.string(), z.unknown()]).optional(),
  lens_focal_length: z.union([z.string(), z.unknown()]).optional(),
  depth_of_field: z.union([z.string(), z.unknown()]).optional(),
})

/**
 * PhotographicCharacteristicsDetails
 *
 * Photographic characteristics of the image.
 */
export const zPhotographicCharacteristicsDetails = z.object({
  lens_focal_length: z.string(),
  camera_angle: z.string(),
  depth_of_field: z.string(),
  focus: z.string(),
})

/**
 * PromptObject
 */
export const zPromptObject = z.object({
  number_of_objects: z.union([z.int(), z.unknown()]).optional(),
  clothing: z.union([z.string(), z.unknown()]).optional(),
  description: z.union([z.string(), z.unknown()]).optional(),
  relative_size: z.union([z.string(), z.unknown()]).optional(),
  skin_tone_and_texture: z.union([z.string(), z.unknown()]).optional(),
  texture: z.union([z.string(), z.unknown()]).optional(),
  expression: z.union([z.string(), z.unknown()]).optional(),
  action: z.union([z.string(), z.unknown()]).optional(),
  pose: z.union([z.string(), z.unknown()]).optional(),
  appearance_details: z.union([z.string(), z.unknown()]).optional(),
  gender: z.union([z.string(), z.unknown()]).optional(),
  relationship: z.string(),
  location: z.union([z.string(), z.unknown()]).optional(),
  orientation: z.union([z.string(), z.unknown()]).optional(),
  shape_and_color: z.union([z.string(), z.unknown()]).optional(),
})

/**
 * StructuredPrompt
 */
export const zBriaFiboVlmStructuredPrompt = z.object({
  background_setting: z.union([z.string(), z.unknown()]).optional(),
  artistic_style: z.union([z.string(), z.unknown()]).optional(),
  style_medium: z.union([z.string(), z.unknown()]).optional(),
  text_render: z.union([z.array(z.unknown()), z.unknown()]).optional(),
  objects: z.union([z.array(zPromptObject), z.unknown()]).optional(),
  context: z.union([z.string(), z.unknown()]).optional(),
  photographic_characteristics: z
    .union([zPhotographicCharacteristics, z.unknown()])
    .optional(),
  aesthetics: z.union([zAestheticsType2, z.unknown()]).optional(),
  lighting: z.union([zLighting, z.unknown()]).optional(),
  short_description: z.union([z.string(), z.unknown()]).optional(),
})

/**
 * StructuredPromptModel
 */
export const zFiboLiteGenerateStructuredPromptLiteInput = z.object({
  prompt: z.union([z.string(), z.unknown()]).optional(),
  seed: z.int().optional().default(5555),
  structured_prompt: z
    .union([zBriaFiboVlmStructuredPrompt, z.unknown()])
    .optional(),
  image_url: z.union([z.string(), z.unknown()]).optional(),
})

export const zQueueStatus = z.object({
  status: z.enum(['IN_QUEUE', 'IN_PROGRESS', 'COMPLETED']),
  request_id: z.string(),
  response_url: z.string().optional(),
  status_url: z.string().optional(),
  cancel_url: z.string().optional(),
  logs: z.record(z.string(), z.unknown()).optional(),
  metrics: z.record(z.string(), z.unknown()).optional(),
  queue_position: z.int().optional(),
})

/**
 * Resolution
 */
export const zResolution = z.object({
  aspect_ratio: z.string(),
  height: z.int(),
  width: z.int(),
})

/**
 * StructuredPrompt
 */
export const zStructuredPrompt = z.object({
  objects: z.union([z.array(zPromptObject), z.unknown()]).optional(),
  text_render: z.union([z.array(z.unknown()), z.unknown()]).optional(),
  style_medium: z.union([z.string(), z.unknown()]).optional(),
  background_setting: z.union([z.string(), z.unknown()]).optional(),
  artistic_style: z.union([z.string(), z.unknown()]).optional(),
  context: z.union([z.string(), z.unknown()]).optional(),
  photographic_characteristics: z
    .union([zPhotographicCharacteristics, z.unknown()])
    .optional(),
  aesthetics: z.union([zAesthetics, z.unknown()]).optional(),
  short_description: z.union([z.string(), z.unknown()]).optional(),
  lighting: z.union([zLighting, z.unknown()]).optional(),
})

/**
 * StructuredPromptModel
 */
export const zFiboGenerateStructuredPromptInput = z.object({
  structured_prompt: z.union([zStructuredPrompt, z.unknown()]).optional(),
  prompt: z.union([z.string(), z.unknown()]).optional(),
  image_url: z.union([z.string(), z.unknown()]).optional(),
  seed: z.int().optional().default(5555),
})

/**
 * TextRender
 *
 * Text rendering information in the image.
 */
export const zTextRender = z.object({
  color: z.string(),
  font: z.string(),
  appearance_details: z.union([z.string(), z.unknown()]).optional(),
  size: z.string(),
  text: z.string(),
  location: z.string(),
})

/**
 * StructuredPrompt
 */
export const zStructuredPromptType2 = z.object({
  background_setting: z.string(),
  short_description: z.string(),
  subject_emotions: z.union([z.string(), z.unknown()]).optional(),
  lighting: zLightingDetails,
  photographic_characteristics: z
    .union([zPhotographicCharacteristicsDetails, z.unknown()])
    .optional(),
  objects: z.array(zObjectDescription),
  aesthetics: zAestheticsDetails,
  context: z.string(),
  text_render: z.union([z.array(zTextRender), z.unknown()]).optional(),
  artistic_style: z.string(),
  style_medium: z.union([z.string(), z.unknown()]).optional(),
})

/**
 * StructuredPromptInput
 */
export const zFiboLiteGenerateStructuredPromptInput = z.object({
  image_url: z.union([z.string(), z.unknown()]).optional(),
  prompt: z.union([z.string(), z.unknown()]).optional(),
  structured_prompt: z.union([zStructuredPromptType2, z.unknown()]).optional(),
  seed: z.int().optional().default(7),
})

/**
 * VideoFormat
 */
export const zVideoFormat = z.object({
  bitrate: z.int(),
  video_codec: z.string(),
  container: z.string(),
  profile: z.string(),
  level: z.number(),
  pixel_format: z.string(),
})

/**
 * Video
 */
export const zVideo = z.object({
  frame_count: z.int(),
  file_size: z.int(),
  fps: z.int(),
  bitrate: z.int(),
  url: z.string(),
  format: zVideoFormat,
  codec: z.string(),
  container: z.string(),
  start_frame_url: z.union([z.string(), z.unknown()]).optional(),
  file_name: z.string(),
  audio: z.union([zAudioTrack, z.unknown()]).optional(),
  content_type: z.string(),
  end_frame_url: z.union([z.string(), z.unknown()]).optional(),
  duration: z.number(),
  timebase: z.string(),
  resolution: zResolution,
  media_type: z.string().optional().default('video'),
})

/**
 * MetadataOutput
 */
export const zFfmpegApiMetadataOutput = z.object({
  media: z.union([zVideo, zAudio]),
})

export const zPostBriaFiboEditEditStructuredInstructionBody =
  zFiboEditEditStructuredInstructionInput

/**
 * The request status.
 */
export const zPostBriaFiboEditEditStructuredInstructionResponse = zQueueStatus

export const zGetBriaFiboEditEditStructuredInstructionRequestsByRequestIdPath =
  z.object({
    request_id: z.string(),
  })

/**
 * Result of the request.
 */
export const zGetBriaFiboEditEditStructuredInstructionRequestsByRequestIdResponse =
  zFiboEditEditStructuredInstructionOutput

export const zPutBriaFiboEditEditStructuredInstructionRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string(),
  })

/**
 * The request was cancelled.
 */
export const zPutBriaFiboEditEditStructuredInstructionRequestsByRequestIdCancelResponse =
  z.object({
    success: z.boolean().optional(),
  })

export const zGetBriaFiboEditEditStructuredInstructionRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string(),
  })

export const zGetBriaFiboEditEditStructuredInstructionRequestsByRequestIdStatusQuery =
  z.object({
    logs: z.number().optional(),
  })

/**
 * The request status.
 */
export const zGetBriaFiboEditEditStructuredInstructionRequestsByRequestIdStatusResponse =
  zQueueStatus

export const zPostBriaFiboLiteGenerateStructuredPromptBody =
  zFiboLiteGenerateStructuredPromptInput

/**
 * The request status.
 */
export const zPostBriaFiboLiteGenerateStructuredPromptResponse = zQueueStatus

export const zPostBriaFiboLiteGenerateStructuredPromptLiteBody =
  zFiboLiteGenerateStructuredPromptLiteInput

/**
 * The request status.
 */
export const zPostBriaFiboLiteGenerateStructuredPromptLiteResponse =
  zQueueStatus

export const zGetBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdPath =
  z.object({
    request_id: z.string(),
  })

/**
 * Result of the request.
 */
export const zGetBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdResponse =
  zFiboLiteGenerateStructuredPromptLiteOutput

export const zPutBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string(),
  })

/**
 * The request was cancelled.
 */
export const zPutBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdCancelResponse =
  z.object({
    success: z.boolean().optional(),
  })

export const zGetBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string(),
  })

export const zGetBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdStatusQuery =
  z.object({
    logs: z.number().optional(),
  })

/**
 * The request status.
 */
export const zGetBriaFiboLiteGenerateStructuredPromptLiteRequestsByRequestIdStatusResponse =
  zQueueStatus

export const zGetBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdPath =
  z.object({
    request_id: z.string(),
  })

/**
 * Result of the request.
 */
export const zGetBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdResponse =
  zFiboLiteGenerateStructuredPromptOutput

export const zPutBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string(),
  })

/**
 * The request was cancelled.
 */
export const zPutBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdCancelResponse =
  z.object({
    success: z.boolean().optional(),
  })

export const zGetBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string(),
  })

export const zGetBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdStatusQuery =
  z.object({
    logs: z.number().optional(),
  })

/**
 * The request status.
 */
export const zGetBriaFiboLiteGenerateStructuredPromptRequestsByRequestIdStatusResponse =
  zQueueStatus

export const zPostBriaFiboGenerateStructuredPromptBody =
  zFiboGenerateStructuredPromptInput

/**
 * The request status.
 */
export const zPostBriaFiboGenerateStructuredPromptResponse = zQueueStatus

export const zGetBriaFiboGenerateStructuredPromptRequestsByRequestIdPath =
  z.object({
    request_id: z.string(),
  })

/**
 * Result of the request.
 */
export const zGetBriaFiboGenerateStructuredPromptRequestsByRequestIdResponse =
  zFiboGenerateStructuredPromptOutput

export const zPutBriaFiboGenerateStructuredPromptRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string(),
  })

/**
 * The request was cancelled.
 */
export const zPutBriaFiboGenerateStructuredPromptRequestsByRequestIdCancelResponse =
  z.object({
    success: z.boolean().optional(),
  })

export const zGetBriaFiboGenerateStructuredPromptRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string(),
  })

export const zGetBriaFiboGenerateStructuredPromptRequestsByRequestIdStatusQuery =
  z.object({
    logs: z.number().optional(),
  })

/**
 * The request status.
 */
export const zGetBriaFiboGenerateStructuredPromptRequestsByRequestIdStatusResponse =
  zQueueStatus

export const zPostFalAiBagelUnderstandBody = zBagelUnderstandInput

/**
 * The request status.
 */
export const zPostFalAiBagelUnderstandResponse = zQueueStatus

export const zGetFalAiBagelUnderstandRequestsByRequestIdPath = z.object({
  request_id: z.string(),
})

/**
 * Result of the request.
 */
export const zGetFalAiBagelUnderstandRequestsByRequestIdResponse =
  zBagelUnderstandOutput

export const zPutFalAiBagelUnderstandRequestsByRequestIdCancelPath = z.object({
  request_id: z.string(),
})

/**
 * The request was cancelled.
 */
export const zPutFalAiBagelUnderstandRequestsByRequestIdCancelResponse =
  z.object({
    success: z.boolean().optional(),
  })

export const zGetFalAiBagelUnderstandRequestsByRequestIdStatusPath = z.object({
  request_id: z.string(),
})

export const zGetFalAiBagelUnderstandRequestsByRequestIdStatusQuery = z.object({
  logs: z.number().optional(),
})

/**
 * The request status.
 */
export const zGetFalAiBagelUnderstandRequestsByRequestIdStatusResponse =
  zQueueStatus

export const zPostFalAiFfmpegApiLoudnormBody = zFfmpegApiLoudnormInput

/**
 * The request status.
 */
export const zPostFalAiFfmpegApiLoudnormResponse = zQueueStatus

export const zGetFalAiFfmpegApiLoudnormRequestsByRequestIdPath = z.object({
  request_id: z.string(),
})

/**
 * Result of the request.
 */
export const zGetFalAiFfmpegApiLoudnormRequestsByRequestIdResponse =
  zFfmpegApiLoudnormOutput

export const zPutFalAiFfmpegApiLoudnormRequestsByRequestIdCancelPath = z.object(
  {
    request_id: z.string(),
  },
)

/**
 * The request was cancelled.
 */
export const zPutFalAiFfmpegApiLoudnormRequestsByRequestIdCancelResponse =
  z.object({
    success: z.boolean().optional(),
  })

export const zGetFalAiFfmpegApiLoudnormRequestsByRequestIdStatusPath = z.object(
  {
    request_id: z.string(),
  },
)

export const zGetFalAiFfmpegApiLoudnormRequestsByRequestIdStatusQuery =
  z.object({
    logs: z.number().optional(),
  })

/**
 * The request status.
 */
export const zGetFalAiFfmpegApiLoudnormRequestsByRequestIdStatusResponse =
  zQueueStatus

export const zPostFalAiFfmpegApiMetadataBody = zFfmpegApiMetadataInput

/**
 * The request status.
 */
export const zPostFalAiFfmpegApiMetadataResponse = zQueueStatus

export const zGetFalAiFfmpegApiMetadataRequestsByRequestIdPath = z.object({
  request_id: z.string(),
})

/**
 * Result of the request.
 */
export const zGetFalAiFfmpegApiMetadataRequestsByRequestIdResponse =
  zFfmpegApiMetadataOutput

export const zPutFalAiFfmpegApiMetadataRequestsByRequestIdCancelPath = z.object(
  {
    request_id: z.string(),
  },
)

/**
 * The request was cancelled.
 */
export const zPutFalAiFfmpegApiMetadataRequestsByRequestIdCancelResponse =
  z.object({
    success: z.boolean().optional(),
  })

export const zGetFalAiFfmpegApiMetadataRequestsByRequestIdStatusPath = z.object(
  {
    request_id: z.string(),
  },
)

export const zGetFalAiFfmpegApiMetadataRequestsByRequestIdStatusQuery =
  z.object({
    logs: z.number().optional(),
  })

/**
 * The request status.
 */
export const zGetFalAiFfmpegApiMetadataRequestsByRequestIdStatusResponse =
  zQueueStatus

export const zPostFalAiFfmpegApiWaveformBody = zFfmpegApiWaveformInput

/**
 * The request status.
 */
export const zPostFalAiFfmpegApiWaveformResponse = zQueueStatus

export const zGetFalAiFfmpegApiWaveformRequestsByRequestIdPath = z.object({
  request_id: z.string(),
})

/**
 * Result of the request.
 */
export const zGetFalAiFfmpegApiWaveformRequestsByRequestIdResponse =
  zFfmpegApiWaveformOutput

export const zPutFalAiFfmpegApiWaveformRequestsByRequestIdCancelPath = z.object(
  {
    request_id: z.string(),
  },
)

/**
 * The request was cancelled.
 */
export const zPutFalAiFfmpegApiWaveformRequestsByRequestIdCancelResponse =
  z.object({
    success: z.boolean().optional(),
  })

export const zGetFalAiFfmpegApiWaveformRequestsByRequestIdStatusPath = z.object(
  {
    request_id: z.string(),
  },
)

export const zGetFalAiFfmpegApiWaveformRequestsByRequestIdStatusQuery =
  z.object({
    logs: z.number().optional(),
  })

/**
 * The request status.
 */
export const zGetFalAiFfmpegApiWaveformRequestsByRequestIdStatusResponse =
  zQueueStatus

export const zPostFalAiOmnilottieBody = zOmnilottieInput

/**
 * The request status.
 */
export const zPostFalAiOmnilottieResponse = zQueueStatus

export const zPostFalAiOmnilottieImageToLottieBody =
  zOmnilottieImageToLottieInput

/**
 * The request status.
 */
export const zPostFalAiOmnilottieImageToLottieResponse = zQueueStatus

export const zGetFalAiOmnilottieImageToLottieRequestsByRequestIdPath = z.object(
  {
    request_id: z.string(),
  },
)

/**
 * Result of the request.
 */
export const zGetFalAiOmnilottieImageToLottieRequestsByRequestIdResponse =
  zOmnilottieImageToLottieOutput

export const zPutFalAiOmnilottieImageToLottieRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string(),
  })

/**
 * The request was cancelled.
 */
export const zPutFalAiOmnilottieImageToLottieRequestsByRequestIdCancelResponse =
  z.object({
    success: z.boolean().optional(),
  })

export const zGetFalAiOmnilottieImageToLottieRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string(),
  })

export const zGetFalAiOmnilottieImageToLottieRequestsByRequestIdStatusQuery =
  z.object({
    logs: z.number().optional(),
  })

/**
 * The request status.
 */
export const zGetFalAiOmnilottieImageToLottieRequestsByRequestIdStatusResponse =
  zQueueStatus

export const zGetFalAiOmnilottieRequestsByRequestIdPath = z.object({
  request_id: z.string(),
})

/**
 * Result of the request.
 */
export const zGetFalAiOmnilottieRequestsByRequestIdResponse = zOmnilottieOutput

export const zPutFalAiOmnilottieRequestsByRequestIdCancelPath = z.object({
  request_id: z.string(),
})

/**
 * The request was cancelled.
 */
export const zPutFalAiOmnilottieRequestsByRequestIdCancelResponse = z.object({
  success: z.boolean().optional(),
})

export const zGetFalAiOmnilottieRequestsByRequestIdStatusPath = z.object({
  request_id: z.string(),
})

export const zGetFalAiOmnilottieRequestsByRequestIdStatusQuery = z.object({
  logs: z.number().optional(),
})

/**
 * The request status.
 */
export const zGetFalAiOmnilottieRequestsByRequestIdStatusResponse = zQueueStatus

export const zPostFalAiOmnilottieVideoToLottieBody =
  zOmnilottieVideoToLottieInput

/**
 * The request status.
 */
export const zPostFalAiOmnilottieVideoToLottieResponse = zQueueStatus

export const zGetFalAiOmnilottieVideoToLottieRequestsByRequestIdPath = z.object(
  {
    request_id: z.string(),
  },
)

/**
 * Result of the request.
 */
export const zGetFalAiOmnilottieVideoToLottieRequestsByRequestIdResponse =
  zOmnilottieVideoToLottieOutput

export const zPutFalAiOmnilottieVideoToLottieRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string(),
  })

/**
 * The request was cancelled.
 */
export const zPutFalAiOmnilottieVideoToLottieRequestsByRequestIdCancelResponse =
  z.object({
    success: z.boolean().optional(),
  })

export const zGetFalAiOmnilottieVideoToLottieRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string(),
  })

export const zGetFalAiOmnilottieVideoToLottieRequestsByRequestIdStatusQuery =
  z.object({
    logs: z.number().optional(),
  })

/**
 * The request status.
 */
export const zGetFalAiOmnilottieVideoToLottieRequestsByRequestIdStatusResponse =
  zQueueStatus
